### ISSUE TITLE
Access to raw camera data in ARCore session?

### ISSUE THREAD

**Issue by seanadkinson** [viromedia/virocore#10]
Hi there, thanks for this project!

Is it possible to get access to the raw camera data during an ARCore session?  I created an [issue with the arcore team](https://github.com/google-ar/arcore-android-sdk/issues/65) for the same functionality, and they suggest using a separate surface, and reading the data from there.  They even provide an example [TextureReader](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/computervision/app/src/main/java/com/google/ar/core/examples/java/computervision/utility/TextureReader.java) that could be used, as long as you have the `textureId`.

If ViroCore doesn't provide this functionality, does (or can it) provide a reference to the background texture, so that I can use the `TextureReader` above?

**Comment by radvani** [comment]
Hi Sean,

While we don't currently provide access to the AR camera's texture ID, we will include this in our next release, which you can then use with the TextureReader from the ARCore Preview 2 example. This release is slated for mid-January. We'll keep this issue open until that release is public. Thanks for using Viro!

**Comment by seanadkinson** [comment]
Thanks @radvani, I'll look forward to that release.

I'd love to starting experimenting in the meantime though.  Any chance you could point me to the class and field where the texture id currently resides?  Then I can use reflection to get access until it is publicly available.

**Comment by radvani** [comment]
Unfortunately that texture ID is created in native code and passed directly to the ARCore Session via JNI, so there's no clear way to expose it via reflection, unless you know how to grab it from the ARCore Session (using ARCore Preview 1). The ARCore Session is in the private variable mSession in ViroViewARCore.

**Comment by radvani** [comment]
Hi Sean, with ViroCore 1.2 [(available now](https://virocore.viromedia.com/docs/releases), you can access the underlying camera texture ID via [ViroViewARCore.getCameraTextureName()](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewARCore.html#getCameraTextureName()).

**Comment by seanadkinson** [comment]
Hey @radvani, thanks for putting this in the 1.2 release.  I really appreciate it.

Seems that using the `TextureReader` (referenced above) conflicts with Viro's code, as the camera doesn't render when using the `TextureReader` code.  The culprit seems to be [this line](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/computervision/app/src/main/java/com/google/ar/core/examples/java/computervision/utility/TextureReader.java#L180), where it registers a frame buffer for read/draw.  I tried changing that line to just READ, but no luck.

Any other ideas of how to access the raw camera data?  I'll keep looking and trying things, and report back here if I find anything.  Thanks.

**Comment by seanadkinson** [comment]
Hey @radvani, I actually just got this working.  In order to use the `TextureReader`, you need to call its method's from the GL thread, so I had to hack in two integration points to Viro using reflection.

Specifically, I needed to initialize the `TextureReader` on/after `onSurfaceCreated`, so I had to access `ViroVireARCore.mSurfaceView` and call `queueEvent`.  Then I also needed code to be called `onDrawFrame` so I could read the texture, so I added a listener to `ViroVireARCore.mFrameListeners` as well.  The latter seems riskier, because I'm pretty sure I saw a cast to `VideoSink` somewhere, and that would fail with my code.

Would be nice for these two integration points to be available in the public API, or for some other mechanism that let's me do what I need to do.

Anyway, not blocked anymore.  Thanks!

**Comment by radvani** [comment]
Hi @seanadkinson thanks for the update and the details on the workaround. We're working on making a more bulletproof and easy to use API for getting the raw screen data now.

**Comment by yasithacd** [comment]
@radvani , As you've mentioned in one of your previous comments, 

> The ARCore Session is in the private variable `mSession` in `ViroViewARCore`.

However, I don't see that `mSession` variable in the latest version of `ViroViewARCore`. Is there any way to access ARCore Session?

**Comment by radvani** [comment]
We've migrated to using the native (C-based) ARCore so the mSession is no longer available. However, in our next release (early next week), we're offering a new API for retrieving raw camera data and camera intrinsics. Is that what you're looking for, or do you need the mSession for something else?

**Comment by yasithacd** [comment]
Thanks @radvani , after further digging in to code I've realised that you are using native ARCore.

My intention is to show plane detection animation as recommended by Google AR design guidelines [here](https://designguidelines.withgoogle.com/ar-design/assets/1x-G9W5a2R6-mgypHY6w27Xt-QzRoiKFT/plane-detection.gif). I've tried plane detection in ViroCore to achieve something similar and outcome is not as interactive as what is shown in the link above. 

Therefore, I wanted to integrate ArCore example given [here](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/common/rendering/PlaneRenderer.java) in to my app. In order to integrate it I wanted to get all ArCore tracked planes and camera Pose using ArCore session. 

Appreciate if you can give some directions to achieve this using ViroCore or some other means.
