### ISSUE TITLE
Error initializing AR [Please install ARCore on this device to use AR features]

### ISSUE THREAD

**Issue by amirhrezf** [viromedia/virocore#102]
I tested everything and arcore ver 4.4 is installed in my samsung note8 phone but i cant run tesla and black panther image target project.
I tryied other viro ar sample and they are working but these two are not
2018-04-29 23:36:06.202 18464-18464/com.example.virosample.arcore E/ViroActivityAR: Error initializing AR [Please install ARCore on this device to use AR features]

**Comment by VikAdvani** [comment]
Hi @amirhrezf, ARCore is on version 1.1, not 4.4. Did you install the ARCore app on your device listed here: https://play.google.com/store/apps/details?id=com.google.ar.core. Make sure you updated to the latest ARCore app if you did install it before.

You'll need that to be installed first so ARCore is installed on the phone. If you installed the above and are still running into issues let us know. 

What are the other samples that are working? Are you seeing objects track properly in the other samples? Do does the message "Please install ARCore on this device.." message show up on the others samples as well?

**Comment by amirhrezf** [comment]
Sorry for the version.
Im sure arcore 1.1 is installed. I test the project on samsung note8. My device is android oreo.
I told you i have only problem with tesla and Black Panther And i said when app lunches i have an black screen and than in log this message
2018-04-29 23:36:06.202 18464-18464/com.example.virosample.arcore E/ViroActivityAR: Error initializing AR [Please install ARCore on this device to use AR features]
Other Virocore projects are working greate. The part i dont understand is if Ar core is not installed it should pop up and say install or update.

**Comment by VikAdvani** [comment]
Hi @amirhrezf did you put the your API Key in the black panther and tesla demo like you did for the ARRetail Demo? The key would go under ARTesla/app/src/main/AndroidManifest.xml within the application block. Replace the string ```Your-api-key-here``` with your API key.

 While this would explain the black screen issue it doesn't explain the "ARCore not installed message".  

If that doesn't work, can you try copying over the app-viro_core-release.aar from the ARRetail sample( /ARRetail/viro_core/app-viro_core-release.aar) over to ARTesla/viro_core/(replacing the existing file).


Also copy over the /ARRetail/arcore_client/core-1.1.0.aar to ARTesla/arcore_client/core-1.1.0.aar.

This will copy the Viro and AR libs that have been proven to work over to the tesla demo. Let us know if any of the above fix the issue and if you still get the black screen.

**Comment by siddhesh-boppo** [comment]
getting same issue for android 12, after updating ar core dependency to    
implementation 'com.google.ar:core:1.30.0'

this AR play store popup is gone but black screen is shown up
