### ISSUE TITLE
Virocore for Unreal Engine

### ISSUE THREAD

**Issue by sambuev** [viromedia/virocore#104]
Hello, I use Unreal Engine ARCore to develop AR for mobile phones (Samsung S8) and I looking for image-based tracking solution, ARCore doesn't have this option, can you please make a plugin for Unreal Engine where I can use an image as a tracking point? Please make as a blueprint solution, because in Unreal most of the people use blueprints. 

Thank you.

**Comment by dthian** [comment]
Requests for ARCore to Unreal Engine integration is un-related to the ViroCore Engine - we do not control any code specific to Unreal or ARCore, nor can we edit or modify them. You can contact either Google or Unreal (the owners of the above components) in their respective github repository issues for such a request. 

However, it is important to note that ViroCore does use ARCore 1.2 that supports image recognition now. So you can effectively use Viro for image-based tracking solutions. 

As we can’t do anything from our end ( we are not owners of the above components like Unreal / ARCore), I am closing this issue.
