### ISSUE TITLE
How to access vertices?

### ISSUE THREAD

**Issue by koopoo87** [viromedia/virocore#105]
Hello,

I'm a newbie to Virocore, and have been stuck with figuring out how to access the vertices of mesh data. I've looked into Object 3D, but could not find any reference / function to get mesh data.

 I would like to estimate the volume of the mesh with the following algorithm. 
https://stackoverflow.com/questions/1406029/how-to-calculate-the-volume-of-a-3d-mesh-object-the-surface-of-which-is-made-up-t

Thank you for your help in advance !

**Comment by radvani** [comment]
Hi @koopoo87, we actually don't have an API at the moment to extract the raw vertex data from a loaded 3D model. I've added this issue to our backlog so we can investigate adding this to our next release. Thanks!

**Comment by dthian** [comment]
Accessing vertices from mesh data should be supported in the latest version of ViroCore, as such resolving.
