### ISSUE TITLE
Supported Devices with ARCore 1.2.0

### ISSUE THREAD

**Issue by nuudles** [viromedia/virocore#119]
I was wondering what the timeframe was for a new release of ViroCore with ARCore 1.2.0. My device (Galaxy S9) is currently not supported by ARCore 1.1.0, but should be supported with 1.2.0. My company is very interested in testing ViroCore for viability in our app, but we haven't been able to do that yet. If the release is far off, is it possible to drop in the new version of ARCore to the existing 1.6.0 release of ViroCore?

**Comment by dam00n** [comment]
We are actively working on ARCore 1.2 integration. We plan to have it released by 5/25, possibly sooner. Will update this issue with more info/timeframes if anything changes.

**Comment by dthian** [comment]
This has been fixed in the latest release of ViroCore 1.7.2. Please checkout the update instructions here: https://virocore.viromedia.com/docs/releases
