### ISSUE TITLE
recorder black screen 

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#127]
first     record  video it is work , when I agian record , the video is black screen

**Comment by 544531645** [comment]
public void recordVideo(){
        ViroMediaRecorder recorder = mViroView.getRecorder();
        recorder.startRecordingAsync(System.currentTimeMillis()+"movie", true, new ViroMediaRecorder.RecordingErrorListener() {
            @Override
            public void onRecordingFailed(ViroMediaRecorder.Error error) {
                Log.i("asdasd ",error.toString());

            }
        });

    }

**Comment by 544531645** [comment]
public void recordVideo(){
        ViroMediaRecorder recorder = mViroView.getRecorder();
        recorder.startRecordingAsync(System.currentTimeMillis()+"movie", true, new ViroMediaRecorder.RecordingErrorListener() {
            @Override
            public void onRecordingFailed(ViroMediaRecorder.Error error) {
                Log.i("asdasd ",error.toString());

            }
        });

    }

**Comment by radvani** [comment]
Hi @544531645, we actually identified this issue in the last few weeks and have it fixed for our next release, which should be out later this week. Thanks for the report.

**Comment by dthian** [comment]
This has been fixed in the latest release of ViroCore 1.7.2. Please checkout the update instructions here: https://virocore.viromedia.com/docs/releases
