### ISSUE TITLE
Change materials of loaded .obj file at runtime

### ISSUE THREAD

**Issue by dam00n** [viromedia/virocore#13]
Github Issue to track a developer feature request.

"I am trying to change parts of a loaded .obj file at runtime. The textures are loaded first via an .mtl file. Whenever I try to get a reference to the materials to change them at runtime the materials are null.

What I would like to achieve:I would like to only change one texture of the loaded 3dObject, not the diffuseColor or the diffuseTexture. How can this be achieved?"

**Comment by dthian** [comment]
With Virocore 1.3, you can now dynamically reference and change textures that are loaded from FBX / OBJ 3D models. Simply call getMaterials() on a loaded Object3D, and that should return a unique list of materials that are being used for that Fbx / Obj. You can search through that list of materials by the name that you've defined in Maya/Blender/etc, and then modify them on the fly (for example, changing it's diffuse color).
