### ISSUE TITLE
Distance measure

### ISSUE THREAD

**Issue by hasanOryx** [viromedia/virocore#134]
Not sure if such thing available in the API, couldn't find it, I need to measure the distance between my mobile and the object targeted in the camera, also measuring the distance between 2 points at that object.
Not sure if this is the correct place to raise such concern, appreciate your support, looking for vrioNative support.

**Comment by dam00n** [comment]
Hi @hasanOryx, this thread might help you answer your question -> https://github.com/viromedia/viro/issues/54
