### ISSUE TITLE
Fill node with texture with repeating

### ISSUE THREAD

**Issue by iTruff** [viromedia/virocore#14]
Hi there. I need to apply some bitmap texture to the node but do not stretch my bitmap to fill node's width and height. I want to place few such images to fill all node's surface with this texture. How can i achieve this?

**Comment by VikAdvani** [comment]
Hi @iTruff,
Currently we don't expose the texture UV coordinates to allow this. However, we've added this to our backlog and hope to get this feature added in an upcoming release. We'll update this issue here when we add it.

**Comment by iTruff** [comment]
@VikAdvani Thanks for feedback. Looking forward to see this feature.

**Comment by iTruff** [comment]
I saw new methods in documentation for Texture class. 

`void setWrapS (Texture.WrapMode wrapS)
Set the horizontal Texture.WrapMode. This determines what happens when the texture coordinates extend outside the [0.0, 1.0] in the X direction of the Texture.`

`void setWrapT (Texture.WrapMode wrapT)
Set the vertical Texture.WrapMode. This determines what happens when the texture coordinates extend outside the [0.0, 1.0] in the Y direction of the Texture.`

Is it something I was asking for in my question?

**Comment by dam00n** [comment]
Yes, you can now tile textures in ViroCore. We updated ViroCore last night and was gonna go through the github issues this morning, but I guess you were faster than us :) 

Full release notes and upgrade instructions for ViroCore 1.3 here -> https://virocore.viromedia.com/docs/releases

**Comment by iTruff** [comment]
Can you please provide some examples of how it should be done. Because I tried to use this feature in sample app and I cant achieve repeating.

This is my code:

`@Override
        public void onAnchorFound(ARAnchor arAnchor, ARNode arNode) {
            // Spawn a visual plane if a PlaneAnchor was found
            if (arAnchor.getType() == ARAnchor.Type.PLANE) {
                ARPlaneAnchor planeAnchor = (ARPlaneAnchor) arAnchor;

                // Create the visual geometry representing this plane
                Vector dimensions = planeAnchor.getExtent();
                Surface plane = new Surface(1, 1);
                plane.setWidth(dimensions.x);
                plane.setHeight(dimensions.z);


                final Texture texture = new Texture(
                        ViroHelper.getBitmapFromAsset(mCurrentActivityWeak.get(), "grid_bg.jpg"),
                        Texture.Format.RGBA8,
                        true,
                        true);

                texture.setWrapS(Texture.WrapMode.REPEAT);
                texture.setWrapT(Texture.WrapMode.REPEAT);

                final Material material = new Material();
                material.setDiffuseTexture(texture);

                plane.setMaterials(Collections.singletonList(material));

                // Attach it to the node
                Node planeNode = new Node();
                planeNode.setGeometry(plane);
                planeNode.setRotation(new Vector(-Math.toRadians(90.0), 0, 0));
                planeNode.setPosition(planeAnchor.getCenter());

                // Attach this planeNode to the anchor's arNode
                arNode.addChildNode(planeNode);
                surfaces.put(arAnchor.getAnchorId(), planeNode);

                // Attach click listeners to be notified upon a plane onClick.
                planeNode.setClickListener(new ClickListener() {

                    int ii = 0;

                    @Override
                    public void onClick(int i, Node node, Vector vector) {
                        for (ClickListener listener : mPlaneClickListeners) {
                            listener.onClick(i, node, vector);
                        }
                    }

                    @Override
                    public void onClickState(int i, Node node, ClickState clickState, Vector vector) {
                        //No-op
                    }
                });

                // Finally, hide isTracking UI if we haven't done so already.
                hideIsTrackingLayoutUI();
            }
        }`

What I'm doing wrong?

**Comment by dthian** [comment]
Hey @iTruff, you would need to use the new Surface constructor API to achieve the visual tilling effect. Check out our documentation here with regards to tiling surfaces:
https://developer.viromedia.com/virocore/reference/com/viro/core/Surface.html

```
Surface (float width, 
                float height, 
                float u0, 
                float v0, 
                float u1, 
                float v1)
```

As mentioned:
> Specifying greater than 1.0 on either the U or V axis will cause the tile to repeat itself or clamp, depending on the Texture's setWrapS(Texture.WrapMode). Specifying less than 1.0 on the U or V axis will render that texture partially over the entire surface.

For example, specifying u0,v0 as (0,0) and (u1,v2) as (2,2) will tile the Texture twice over the width and height of the Surface, effectively displaying 4 textures on the Surface. Alternatively, setting (u1,v1) as (0.5, 0.5) will display a quarter of the texture over the entire surface.

**Comment by iTruff** [comment]
@dthian Thanks a lot for your help. I will try.

**Comment by iTruff** [comment]
Works as expected, thanks. Closed I think.

**Comment by SurendiranParasu** [comment]
how to add multiple textures for a single 3D object. do the needful.

**
material.setDiffuseTexture(texture)------> Here I have to add multiple texture to show an object
