### ISSUE TITLE
replace so much time , model become black 

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#142]

**Comment by 544531645** [comment]
1. I replace over 20 times 
2 replace code: 
 if (object3D == null) {
            object3D = new Object3D();
        }
        // object3D.setPosition(position);

        if (mProductModelGroup == null) {
            mProductModelGroup = new Node();
            Spotlight spotLight = new Spotlight();
            spotLight.setInfluenceBitMask(1);
            spotLight.setPosition(new Vector(0, 2.5, 0));
            spotLight.setCastsShadow(true);
            shadowNode = new Node();
            spotLight.setDirection(new Vector(0, -0.01, 0));
            spotLight.setIntensity(5000);
            spotLight.setShadowOpacity(1.1f);
            mProductModelGroup.addLight(spotLight);

            // Create a mock shadow plane in AR

            Surface shadowSurface = new Surface(5, 5);
            Material material = new Material();
           // material.setDiffuseColor(Color.parseColor("#00000000"));
            material.setShadowMode(Material.ShadowMode.TRANSPARENT);
            material.setLightingModel(Material.LightingModel.LAMBERT);
            shadowSurface.setMaterials(Arrays.asList(material));
            shadowNode.setGeometry(shadowSurface);
            shadowNode.setLightReceivingBitMask(1);
            shadowNode.setPosition(new Vector(0, -0.02, 0.01));
            shadowNode.setRotation(new Vector(-1.5708, 0, 0));
            // We want the shadow node to ignore all events because it contains a surface of size 20x20
            // meters and causes this to capture events which will bubble up to the mProductModelGroup node.
            shadowNode.setIgnoreEventHandling(true);

            mProductModelGroup.addChildNode(shadowNode);


            mProductModelGroup.setOpacity(1);

            mProductModelGroup.setScale(new Vector(0.9, 0.9, 0.9));
        } else {
            mProductModelGroup.removeAllChildNodes();
            mProductModelGroup.addChildNode(shadowNode);
        }
        //  object3D.setRotation(new Vector(1,1,1));
        mScene.getRootNode().removeAllChildNodes();

        EnumSet<Node.TransformBehavior> transformBehavior =
                EnumSet.of(Node.TransformBehavior.BILLBOARD_Y);
        object3D.setTransformBehaviors(transformBehavior);
        mProductModelGroup.setPosition(position);
        object3D.setScale(new Vector(0.026f, 0.026f, 0.026f));
        mProductModelGroup.addChildNode(object3D);
        mScene.getRootNode().addChildNode(mProductModelGroup);
        object3D.loadModel(mViroView.getViroContext(), uri, Object3D.Type.FBX, new AsyncObject3DListener() {}  ......

**Comment by dthian** [comment]
Hey @544531645, this will be fix in the upcoming release (sometime next week). We'll update this github issue once it has been deployed. Thanks for your patience!

**Comment by dam00n** [comment]
This has been fixed in the latest release, ViroCore 1.9

Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases
