### ISSUE TITLE
mViroView.getRecorder().takeScreenShotAsync return a black image?

### ISSUE THREAD

**Issue by scolar** [viromedia/virocore#144]
mViroView.getRecorder().takeScreenShotAsync return a black image?
my device is Huawei P20, android version is 8.1
my code ：
![4 h9qdvrzso 6jt j pie5](https://user-images.githubusercontent.com/11267256/41216217-f6fdfa2e-6d85-11e8-9bcb-cf3e55837a04.png)
image:
![screenshot](https://user-images.githubusercontent.com/11267256/41216143-a9144354-6d85-11e8-8c73-b10a90673b6e.png)

**Comment by manbod** [comment]
Hi @scolar ,
Thanks for reaching out to us and reporting this. This seems related to a bug in our platform wrt. devices with Mali GPUs. Huawei P20 has Mali-G72 MP12 from what we know. We have another bug logged on us tracking this [here](https://github.com/viromedia/viro/issues/305), and are actively looking to fix this in an upcoming release. Apologies for the inconvenience.

Thanks

**Comment by scolar** [comment]
Hi @manbod , virocore 1.8.2 still has the bug, is there a plan to fix this bug.

**Comment by radvani** [comment]
Hi @scolar, this bug has been fixed and will be available in our next release (mid-August). Thanks!

**Comment by dam00n** [comment]
This has been fixed in the latest release, ViroCore 1.9

release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases
