### ISSUE TITLE
node drag issue?

### ISSUE THREAD

**Issue by scolar** [viromedia/virocore#145]
my code is the demo of virocore 1.7.2 as follow:
![image](https://user-images.githubusercontent.com/11267256/41268413-83c54096-6e32-11e8-84f4-e8c36f0caf4a.png)

while draging the node ,sometimes,the model become very small,
![image](https://user-images.githubusercontent.com/11267256/41268501-f7ee9d64-6e32-11e8-8a0c-dc19f235ea51.png)

sometimes,the model become very big.
![image](https://user-images.githubusercontent.com/11267256/41268521-0b11d988-6e33-11e8-96e9-b66aecc339e1.png)

while draging the model node,do not change the model size.
and I find that the demo of virocore 1.6 no this issue.

**Comment by scolar** [comment]
I find that the demo of virocore 1.6 has no this issue.Only virocore 1.7.2 has this issue.

**Comment by VikAdvani** [comment]
Hi @scolar, I have reproduced this issue. We'll look into this and update this bug once when we have a fix.

**Comment by dthian** [comment]
Hey @scolar, I've just patched up and updated the ARRetail application of our Viro Samples. It should now be properly using our AR Anchoring system when placing the lamp. Could you give it a shot and let us know if you still see the issue on your end? And if you do could you use [AZ Screen Recorder](https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free&hl=en_US) to visually identify the issue? Much thanks!
