### ISSUE TITLE
(AR Tesla example) 3D object position change in image detection example

### ISSUE THREAD

**Issue by mistrydarshan99** [viromedia/virocore#147]
Hello,
I have tested AR Tesla sample app in Samsung Galaxy S8. I have to found one issue regarding 3D object position Change in the real world.

Step to reproduce the issue:
1) Scan Tesla image and load 3D model.
2) After successfully load 3D model move device camera fast around the real world.
3) As you move camera fast in the real world some time 3D object position change and also sometimes 3D model disappear from its position.

So, my question is how to fix this issue regarding position change in the real world?

**Comment by VikAdvani** [comment]
HI @mistrydarshan99,
Are you able to send a video to us so we can better see the position change? 

One thing you may want to try is to wait for AR to initialize using the ```onTrackingUpdated``` callback in ViroARScene to see if that improves things.

So in your scene you'd have the following:
```
<ViroARScene onTrackingUpdated={this._onTrackingUpdated}>
             {renderIf(this.state.hasARInitialized, this.renderMarker())}
</ViroARScene>
```

```onTrackingUpdated()``` would look like this:

```
_onTrackingUpdated(state, reason) {
    // if the state changes to "TRACKING_NORMAL" for the first time, then
    // that means the AR session has initialized!
    if (!this.state.hasARInitialized && state == ViroConstants.TRACKING_NORMAL) {
      this.setState({
        hasARInitialized : true,
        text : "Hello World!"
      });
    }
  },
```


```renderIf()``` would be a method imported from a separate file that looks like the following:
```
export default function renderIf(condition, content) {
    if (condition) {
        return content;
    } else {
        return null;
    }
}
```

This way, the app logic is at least waiting for the AR tracking to initialize before tracking the market.

**Comment by croccio** [comment]
how do u solved this problem in native? car is moving when i go around it. always s8
