### ISSUE TITLE
Not proper description for portal scene.

### ISSUE THREAD

**Issue by mistrydarshan99** [viromedia/virocore#15]
There is not a single example related to the portal scene in virocore sdk. Can you explain how to use portal scene using this SDK ?

I have read a document of virocore sdk but there is no proper description found for a portal scene in android.

Referred URL: https://virocore.viromedia.com/docs/augmented-reality-ar

**Comment by radvani** [comment]
Hi @mistrydarshan99, thanks for pointing this out. We've added an example of how to use the Portal API to our [ViroCore AR guide](https://virocore.viromedia.com/v1.2.0/docs/augmented-reality-ar).
