### ISSUE TITLE
A/art: art/runtime/indirect_reference_table.cc:128] JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by variux** [viromedia/virocore#163]
Hi, I was trying to use the example of ARRetail after trying to use my own model (I attached it) I get the error

`A/art: art/runtime/indirect_reference_table.cc:128] JNI ERROR (app bug): local reference table overflow (max=512)`

I look at old references and it was fixed on version 1.4 but I checked it and I'm using v 1.8.0 so I don't know if is a problem related to the 3D model in specific.

Thank you.

[Here's all the model and the converted vrx](https://drive.google.com/drive/folders/1gTEn9CzXsWEvNLdJVqPJsFtZAdxUM2BG?usp=sharing)

**Comment by VikAdvani** [comment]
Hi @variux, thanks for reporting this. Have you tried the previous version of virocore(virocore 1.7.2) to see if it works for you. Others have reported this issue and it seems to occur when the 3d model many children. We will provide a fix in the next release.

**Comment by variux** [comment]
No, I didn't try cause is the example but there's a guide for downgrading?

**Comment by munjliew** [comment]
Do we know when the fix will come out for 1.8?  I need the nodes that were created for the 3D models, which was only leveraged in 1.8

**Comment by VikAdvani** [comment]
Hi @munjliew, this has now been fixed, so it'll definitely be in our next release. I'll discuss with the team next week if we are able to release a hot fix sometime soon.

**Comment by VikAdvani** [comment]
Hi @munjliew, @variux, this has been fixed in our latest release v.1.8.2. You can download it here:
https://s3-us-west-2.amazonaws.com/virocore/1_8_2/virocore-release-v_1_8_2.aar

**Comment by amiradbi** [comment]
Hi @VikAdvani ,
I am using v 1.8.2 and still can see the problem 

`07-23 13:44:47.199 1948-2164 I/Viro: OBJ # of vertices  = 2108
    OBJ # of normals   = 1071
    OBJ # of texcoords = 2283
    OBJ # of materials = 2
    OBJ # of shapes    = 2
07-23 13:44:47.204 1948-2164 I/Viro: OBJ bounding box    =  x(-0.976005 0.972488) y(0.005164 2.602606) z(-0.076711 0.076711)
07-23 13:44:47.219 1948-2164 I/Viro:    MTL files read, loading OBJ
07-23 13:44:47.244 1948-2164 I/Viro: OBJ # of vertices  = 2108
    OBJ # of normals   = 1071
    OBJ # of texcoords = 2283
    OBJ # of materials = 2
    OBJ # of shapes    = 2
07-23 13:44:47.244 1948-2422 I/native: arcore_feature_extractor_wrapper.cc:29 Extracting features using  ArcoreFeatureExtractorWrapper.
    arcore_feature_extractor_wrapper.cc:32 Extracting FREAK descriptors.
07-23 13:44:47.247 1948-2164 I/Viro: OBJ bounding box    =  x(-0.976005 0.972488) y(0.005164 2.602606) z(-0.076711 0.076711)
07-23 13:44:47.255 1948-2164 I/Viro:    MTL files read, loading OBJ
07-23 13:44:47.276 1948-2164 I/Viro: OBJ # of vertices  = 2108
    OBJ # of normals   = 1071
    OBJ # of texcoords = 2283
    OBJ # of materials = 2
    OBJ # of shapes    = 2
07-23 13:44:47.281 1948-2164 I/Viro: OBJ bounding box    =  x(-0.976005 0.972488) y(0.005164 2.602606) z(-0.076711 0.076711)
07-23 13:44:47.289 1948-2164 I/Viro:    MTL files read, loading OBJ
07-23 13:44:47.294 1948-2422 V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 79.)
    JniHelper: thread already attached. (Called from line 79.)
    ~JniHelper: did not need to detach thread. (Called from line 79.)
07-23 13:44:47.294 1948-2422 I/Viro: Successfully configured AR session [lighting 1, planes 1, update 0]
07-23 13:44:47.294 1948-2422 I/native: session.cc:417 Entering Session::Resume.
07-23 13:44:47.294 1948-2422 V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 44.)
    JniHelper: thread already attached. (Called from line 44.)
    ~JniHelper: did not need to detach thread. (Called from line 44.)
07-23 13:44:47.294 1948-2422 I/native: session.cc:423 Session::Resume returning OK.
07-23 13:44:47.308 1948-2164 I/Viro: OBJ # of vertices  = 2108
07-23 13:44:47.309 1948-2164 I/Viro: OBJ # of normals   = 1071
07-23 13:44:47.310 1948-2164 I/Viro: OBJ # of texcoords = 2283
    OBJ # of materials = 2
    OBJ # of shapes    = 2
07-23 13:44:47.314 1948-2164 I/Viro: OBJ bounding box    =  x(-0.976005 0.972488) y(0.005164 2.602606) z(-0.076711 0.076711)
07-23 13:44:47.321 1948-2164 I/Viro:    MTL files read, loading OBJ
07-23 13:44:47.335 1948-2164 I/Viro: OBJ # of vertices  = 2108
    OBJ # of normals   = 1071
    OBJ # of texcoords = 2283
    OBJ # of materials = 2
    OBJ # of shapes    = 2
07-23 13:44:47.339 1948-2164 I/Viro: OBJ bounding box    =  x(-0.976005 0.972488) y(0.005164 2.602606) z(-0.076711 0.076711)
07-23 13:44:47.343 1948-1948 W/art: Attempt to remove non-JNI local reference, dumping thread
07-23 13:44:47.345 1948-2164 I/Viro:    MTL files read, loading OBJ
07-23 13:44:47.356 1948-2164 I/Viro: OBJ # of vertices  = 2108
    OBJ # of normals   = 1071
    OBJ # of texcoords = 2283
    OBJ # of materials = 2
    OBJ # of shapes    = 2
07-23 13:44:47.358 1948-2164 I/Viro: OBJ bounding box    =  x(-0.976005 0.972488) y(0.005164 2.602606) z(-0.076711 0.076711)
07-23 13:44:47.365 1948-1948 A/art: art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): local reference table overflow (max=512)
    art/runtime/indirect_reference_table.cc:132] local reference table dump:
    art/runtime/indirect_reference_table.cc:132]   Last 10 entries (of 507):
    art/runtime/indirect_reference_table.cc:132]       506: 0x130446d0 java.lang.Class<com.viro.core.Texture>
    art/runtime/indirect_reference_table.cc:132]       505: 0x130446d0 java.lang.Class<com.viro.core.Texture>
    art/runtime/indirect_reference_table.cc:132]       504: 0x130446d0 java.lang.Class<com.viro.core.Texture>
    art/runtime/indirect_reference_table.cc:132]       503: 0x130446d0 java.lang.Class<com.viro.core.Texture>
    art/runtime/indirect_reference_table.cc:132]       502: 0x130446d0 java.lang.Class<com.viro.core.Texture>
    art/runtime/indirect_reference_table.cc:132]       501: 0x130f5800 java.lang.Class<com.viro.core.Material>
    art/runtime/indirect_reference_table.cc:132]       500: 0x130f5800 java.lang.Class<com.viro.core.Material>
    art/runtime/indirect_reference_table.cc:132]       499: 0x130f5800 java.lang.Class<com.viro.core.Material>
    art/runtime/indirect_reference_table.cc:132]       498: 0x130f5800 java.lang.Class<com.viro.core.Material>
    art/runtime/indirect_reference_table.cc:132]       497: 0x130f5800 java.lang.Class<com.viro.core.Material>
    art/runtime/indirect_reference_table.cc:132]   Summary:
    art/runtime/indirect_reference_table.cc:132]       485 of java.lang.Class (6 unique instances)
    art/runtime/indirect_reference_table.cc:132]        15 of java.lang.String (15 unique instances)
    art/runtime/indirect_reference_table.cc:132]         1 of com.viro.core.Material[] (7 elements)
    art/runtime/indirect_reference_table.cc:132]         1 of com.viro.core.Geometry
    art/runtime/indirect_reference_table.cc:132]         1 of com.viro.core.Object3D
    art/runtime/indirect_reference_table.cc:132]         1 of com.viro.core.Texture
    art/runtime/indirect_reference_table.cc:132]         1 of com.viro.core.Material
    art/runtime/indirect_reference_table.cc:132]         1 of java.util.ArrayList
    art/runtime/indirect_reference_table.cc:132]         1 of java.lang.String[] (4 elements)
    art/runtime/indirect_reference_table.cc:132] 
07-23 13:44:47.447 1948-2422 I/native: arcore_feature_extractor_wrapper.cc:29 Extracting features using  ArcoreFeatureExtractorWrapper.
    arcore_feature_extractor_wrapper.cc:32 Extracting FREAK descriptors.
07-23 13:44:47.485 1948-2422 V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 79.)
    JniHelper: thread already attached. (Called from line 79.)
07-23 13:44:47.579 1948-2422 V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: did not need to detach thread. (Called from line 79.)
07-23 13:44:47.580 1948-2422 I/Viro: Successfully configured AR session [lighting 1, planes 1, update 0]
07-23 13:44:47.580 1948-2422 I/native: session.cc:417 Entering Session::Resume.
07-23 13:44:47.580 1948-2422 V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 44.)
    JniHelper: thread already attached. (Called from line 44.)
    ~JniHelper: did not need to detach thread. (Called from line 44.)
07-23 13:44:47.580 1948-2422 I/native: session.cc:423 Session::Resume returning OK.
07-23 13:44:47.582 1948-1948 A/art: art/runtime/runtime.cc:422] Runtime aborting...`

**Comment by VikAdvani** [comment]
Hi @amiradbi, thanks for reporting this. We've fixed this bug for our next release :)

**Comment by amiradbi** [comment]
Thanks for your prompt effort and fixing. Do you have any idea of next
release?

**Comment by dam00n** [comment]
This issue has been fixed in ViroCore 1.9 

Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases
