### ISSUE TITLE
3d text

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#164]
![image](https://user-images.githubusercontent.com/15622364/42684831-e06f9b8a-86c3-11e8-8186-b3605db1d905.png)
I want to do 3d text like ios ,but i dont know how can do it, i think your program it only scan support english letters , isn't it? i try many times open to chinese, but it error , i just want to confrim to you, is it support chinese or only english ?

**Comment by 544531645** [comment]
Or bitmap, but how do you do something like image that ?

**Comment by radvani** [comment]
Hi, we don't support 3D text yet, but this is an item on our backlog that we plan on building out soon. We do support Chinese characters in 2D text, which you can try like this (your phone must have the NotoSansCJK font for this example; if it doesn't, try another font that supports the characters):

```
Text text = Text.builder(viroContext).width(3.5f).height(1).build();
text.setText("This is an example of mixed text 他们赋 有理性和良心");
text.setFontFamilies("Roboto, NotoSansCJK");
```

Another option for 3D text is to create it in a 3D modeling program and import it into an Object3D.

**Comment by 544531645** [comment]
Why is the font like a transparent box, can it be eliminated

**Comment by 544531645** [comment]
runtime.cc:492]   native: #45 pc 003e02e1  /system/lib/libart.so (art_quick_to_interpreter_bridge+32)
    runtime.cc:492]   native: #46 pc 0004562b  /dev/ashmem/dalvik-jit-code-cache (deleted) (???)
    runtime.cc:492]   at com.viro.core.Texture.nativeCreateImageTextureBitmap(Native method)
    runtime.cc:492]   at com.viro.core.Texture.<init>(Texture.java:399)
    runtime.cc:492]   at com.viro.core.Texture.<init>(Texture.java:373)

**Comment by 544531645** [comment]
Texture chineseCharTexture = new Texture(bitmapFromAsset, Texture.Format.RGBA8, true, true);
 this method happend error

**Comment by radvani** [comment]
Would you mind showing me how you loaded `bitmapFromAsset`, and also sending me the image you're using? You can either attach it here or send it to support@viromedia.com. I'll see if I can reproduce the error. Thanks!

**Comment by 544531645** [comment]
public static Bitmap convertViewToBitmap(View view) {
        view.measure(View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED), View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
        view.layout(0, 0, view.getMeasuredWidth(), view.getMeasuredHeight());
        view.buildDrawingCache();
        Bitmap bitmap = view.getDrawingCache();

        return bitmap;
    }

**Comment by 544531645** [comment]
use this get .I see log ,sometiome the bitmap is null...

**Comment by radvani** [comment]
This looks like it may be an issue with view.getDrawingCache(), in that if it's returning null then creating a Texture from the null bitmap will crash. You can try this other method to get the Bitmap from a View:

```
public static Bitmap loadBitmapFromView(View v) {
     Bitmap b = Bitmap.createBitmap( v.getLayoutParams().width, v.getLayoutParams().height, Bitmap.Config.ARGB_8888);                
     Canvas c = new Canvas(b);
     v.layout(0, 0, v.getLayoutParams().width, v.getLayoutParams().height);
     v.draw(c);
     return b;
}
```

Additionally, in our next release we're introducing an AndroidViewTexture object, which will make rendering Android views in Viro much easier.

**Comment by 544531645** [comment]
I wonder when 3d Text like SceneKit will be supported

**Comment by radvani** [comment]
We are planning to have this in our next release, which should be ready mid-August.

**Comment by dam00n** [comment]
3D text has been added in our latest release, ViroCore 1.9

Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases

**Comment by 544531645** [comment]
the 3d text how to become the image ,  the image text have black 
![image](https://user-images.githubusercontent.com/15622364/43821146-dd6c5a7a-9b1a-11e8-9a56-86362b88adc8.png)

**Comment by 544531645** [comment]
setOuterStroke this method ? but I test no use

**Comment by 544531645** [comment]
@dam00n

**Comment by 544531645** [comment]
![screenshot_20180808-165841](https://user-images.githubusercontent.com/15622364/43827400-5489841e-9b2c-11e8-95f8-140e6b4b4e91.png)
![screenshot_20180808-165630](https://user-images.githubusercontent.com/15622364/43827428-61f8a38c-9b2c-11e8-8e18-b066a3c69923.png)

**Comment by radvani** [comment]
Hi, for 3D text do not use setOuterStroke, instead use setExtrusionDepth. To set the colors like you want them (blue front, black sides), you can use:

```
text.setExtrusionDepth(2);

Material frontMaterial = new Material();
frontMaterial.setDiffuseColor(Color.BLUE);
     
Material  backMaterial = new Material();
backMaterial.setDiffuseColor(Color.BLUE);
     
Material sideMaterial = new Material();
sideMaterial.setDiffuseColor(Color.BLACK); 

List<Material> materials = Arrays.asList(frontMaterial, backMaterial, sideMaterial);
text.setMaterials(materials);
```
