### ISSUE TITLE
OpenGL Dev. Question

### ISSUE THREAD

**Issue by rgipd** [viromedia/virocore#165]
Hello,

  This is a developer question... as an OpenGL developer.

  I know that Adrenos GPUs 330 or lower has some problems like not use struct.
  Also has problem with colors (dark than any other GPU). Can I know, if possible, how Viro team handled these Adreno 330- color problems?

  I had a lot of problems with these GPUs ans I'm really curious if you team also had.

P.S.: If you don't want to share, I will understand.

Thanks in advance!

**Comment by radvani** [comment]
Hi @rgipd, yes, we did have a number of issues with Adreno 330. Our solution was to disable all advanced rendering features on that device (we detect the device at runtime). We also had to write a special set of shaders that don't use structs. It's a very problematic GPU!
