### ISSUE TITLE
xyz

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#166]
I want to change my orientation when I turn around and re-establish the xyz direction instead of the forever initialized xyz, what should I do?

**Comment by 544531645** [comment]
@dthian can you help me for this ?

**Comment by dthian** [comment]
Hey @544531645, one possible solution is to encapsulate the items in your scene (the items you want to "Re-establish or reset" xyz direction) in a ViroNode instead. Thus you can rotate that root node and reset it to whatever the camera's current orientation is, thereby effectively achieving the above behavior.

**Comment by 544531645** [comment]
in your scene (the items you want to "Re-establish or reset" xyz direction) in a ViroNode instead. Thus you can rotate that root node and reset it to whatever the camera's current orientation is,  how I can do this , can you give me a example ? @dthian

**Comment by dthian** [comment]
Hey @544531645, to encapsulate controls in a ViroNode, you can use the [addChildNode api. ](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html#addChildNode(com.viro.core.Node)). Here is a pseudo code example of how that might be done:

```
rootOrientationNode = new Node();
// Add all the items here that were in your scene so that they are now in reference to this node
rootOrientationNode.addChildNode(.....);  
scene.getRootNode().addchildnode(rootOrientationNode);
```

You can then modify the orientation of the node to face which ever direction you want. In the above case, it sounds like you want to reset it to the camera's current orientation. You can get that with this api [here](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroView.html#getLastCameraRotationEulerRealtime()). And then simply set the orientation on the [rootOrientationNode.setRotation](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html#setRotation(com.viro.core.Vector))

**Comment by 544531645** [comment]
@dthian you mean this method ? I use crash

**Comment by 544531645** [comment]
I tell you I want show what ,when I create a 3d model , I will create a text in 3d model the right and top , should I gicve txt position is what , because the xyz is when open ar camera ,  when I create model in my right , I don't know how to give text location postiotn, don't know  do x+what or y-what etc

**Comment by dthian** [comment]
>  because the xyz created is when open ar camera , when I create model in my right, I don't know how to give text location position

So in AR, the origin of the world is determined when you first start your AR application - it will be where your AR Camera is. That is to say, when you first start your AR application, your AR camera is the (0,0,0) position of the world from which everything will be positioned in relation to.

Thus, for example, if you want to place your 3d model 1m in front of the user, 1m towards the right, and 1m vertically towards the top, you simply place your object with:

[node.setPosition(new Vector(1,1,1));
](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html#setPosition(com.viro.core.Vector))

When you do this, your node will be placed in front of the user, towards the right, and vertically 1 meter off the ground, in reference to the origin of the world. **Remember that your origin is determined by the orientation / position of your ARCamera (or device view point) when you first start the AR app.**

Hope that helps!

**Comment by 544531645** [comment]
yes ,this I know , But example I first create a  A model position (1,1,1). then I want create the motel at  A model right , Wherever I move ， Can it be achieved  。 nomarl I do new Vector(position.x + 0.3f, position.y + 0.4F, position.z + 0.2f) ， when Facing the initial creation of the camera is the right direction，  but if first create A not (1,1,1). I turn back , create A (-1.-2.1), new Vector(position.x + 0.3f, position.y + 0.4F, position.z + 0.2f) will error

**Comment by dthian** [comment]
> then I want create the motel at A model right , Wherever I move
- Do you mean to create a new model (let's say model B) that is positioned to the right side of model A, such that it is always on the right side of model A, irregardless of wherever the camera moves? 

>nomarl I do new Vector(position.x + 0.3f, position.y + 0.4F, position.z + 0.2f) ， when Facing the initial creation of the camera is the right direction，
- Where does the "position" variable come from? Does it represent the position of model A? 
- How are you setting it in code? 
- To what model (is it the second model that you are trying to place next to model A) are you applying the above new Vector to?

>but if first create A not (1,1,1). I turn back , create A (-1.-2.1), new Vector(position.x + 0.3f, position.y + 0.4F, position.z + 0.2f) will error
- To which object are you applying the "new Vector(position.x + 0.3f, position.y + 0.4F, position.z + 0.2f)" to? Is this onto the second model that you are trying to place next to model A? 
- What do you mean by "will error?"
- Sorry, I can hardly understand what you are trying to explain above. Can you provide a video recording of the error?

**Comment by 544531645** [comment]
I send the video to "support"<support@viromedia.com>; , you can check it  @dthian

**Comment by dthian** [comment]
Hey @544531645, thanks for sending the video. When you mention:
> the video ,first show the userimage in right , second time not in right ?
By "userimage" do you mean the purple circle that is positioned underneath the shark model?

In the video this seems like there is a bug in your application in the positioning of the userimage purple circle. Can you share the code representing the construction of the subtree of the shark + purple circle + portal, and as well as how you are setting the new Vector above?

**Comment by 544531645** [comment]
position is form ARHitTestListenerCrossHair,    shark create in postion , circle crate use      mTextNode.setPosition(new Vector(position.x + 0.1f, position.y - 0.06F, position.z));  I think my method is error , but how to create right vector , let circle at shark right and bottom

**Comment by 544531645** [comment]
@dthian my method only I face the first open camera is work good

**Comment by dthian** [comment]
Hm, can you please share the code on how you are creating / parenting the subtree that includes your shark and the "userimage" circle? 

The above approach does not work - with the given world space position from ARHitTestListenerCrossHair, you are attempting to place the "userimage" circle in world space - this only works for certain viewing angles this may work (like when you first open the camera), but as soon as your camera perspective changes, **this will not work.**

Instead of placing the "userimage" circle in world space, I recommend positioning it relative to the rotation of the shark (or the rotation of the parent node that rotates the shark). Thus, instead of using the position value from ARHitTestListener, you should just parent the node with the "userimage" circle geometry, under the shark node (or parent node containing the shark node, whichever does the rotation of the shark towards the user), with the "userimag" circle then placed at (0.1, -0.06, 0). This will gurantee that the circle will always be place in front of the shark.

Thus, I think that would be the solution - please let me know if that doesn't work for you. If not, I need to see the actual code of how you are constructing the subtree of your shark + "userimage" circle.

**Comment by 544531645** [comment]
I change code to              mProductModelGroup = new Node();        mProductModelGroup.setPosition(position);
mProductModelGroup.addChildNode(shark_model);
 userimageNode.setPosition(new Vector( 0.1f,  - 0.06f,0));
       mProductModelGroup.addChildNode(userimageNode);
 no use , same before video

**Comment by 544531645** [comment]
@dthian position is ARHitTestListener

**Comment by dthian** [comment]
@544531645, the above solution **should** have work. I've tried your code above by placing a red box at (0,0,0) under mProductModelGroup - notice that it **always** positions itself in front of the star, relative to the parent node.

![ezgif-1-7f909cff42](https://user-images.githubusercontent.com/1904934/43289929-4e2e52d4-90e1-11e8-8eca-c67c6ceb829e.gif)


Please verify that your shark model is at the origin (or (0,0,0) of it's parent node (in this case the mProductModelGroup. This is because both your shark and your userImage circle is parented and therefore placed in relation to mProductModelGroup. Thus, if the shark is not centered in mProductModelGroup, then it may look as if the userImage circle is "moving" around the shark (when actually what is happening is that the shark itself is "moving" around the origin of the mProductModelGroup). 

If that doesn't work for you, I need to see your **_full code_** representing the node subtree where you have constructed and parented the shark so that i can help debug the issue.

**Comment by 544531645** [comment]
Your method requires me to always look in the same direction and rotate it? This method doesn't help me, because I keep the shark facing me forever, so it's not always on the right, and I'm not only adding useriamge, but I'm also adding a lot around the shark on the left or on the right and so on, and I need to have a fixed position

**Comment by 544531645** [comment]
private void createDroidAtPosition(final Vector position, final boolean with_User, Uri uri, final Message message) {
        // Create a droid on the surface
        mScene.getRootNode().removeAllChildNodes();

        mScene.getRootNode().addChildNode(root_node);

        if (object3D == null) {
            object3D = new Object3D();
        }
        if (object3D_animotion==null) {
            object3D_animotion = new Object3D();
            object3D_animotion.setShadowCastingBitMask(2);
        }
        hand_hint.setVisibility(View.GONE);
        if (mProductModelGroup == null) {

            mProductModelGroup = new Node();
            spotLight = new DirectionalLight();
   
            Vector vector = new Vector(0, 1, 0);
            spotLight.setShadowOrthographicPosition(vector);
            spotLight.setShadowOrthographicSize(0.5f);
            spotLight.setInfluenceBitMask(3);
            spotLight.setDirection(new Vector(0, -1, 0));
            spotLight.setCastsShadow(true);
            shadowNode = new Node();
            //   spotLight.setDirection(new Vector(0, -0.04, 0));
            spotLight.setIntensity(1500);

            spotLight.setShadowMapSize(2048);
            spotLight.setColor(Color.WHITE);
            spotLight.setShadowOpacity(0f);
            mProductModelGroup.addLight(spotLight);

            // Create a mock shadow plane in AR

            Surface shadowSurface = new Surface(2, 2);
            Material material = new Material();

            // material.setDiffuseColor(Color.parseColor("#00000000"));
            material.setShadowMode(Material.ShadowMode.TRANSPARENT);
            material.setLightingModel(Material.LightingModel.LAMBERT);

            shadowSurface.setMaterials(Arrays.asList(material));
            shadowNode.setGeometry(shadowSurface);

            shadowNode.setPosition(new Vector(0,-0.06,0));
            shadowNode.setRotation(new Vector((float) -Math.PI / 2.0f, 0, 0));
            // We want the shadow node to ignore all events because it contains a surface of size 20x20
            // meters and causes this to capture events which will bubble up to the mProductModelGroup node.
            shadowNode.setIgnoreEventHandling(true);

            mProductModelGroup.addChildNode(shadowNode);


            mProductModelGroup.setOpacity(1);

            mProductModelGroup.setScale(new Vector(0.9, 0.9, 0.9));
        } else {
            spotLight.setShadowOpacity(0f);

            mProductModelGroup.removeAllChildNodes();
            mProductModelGroup.addChildNode(shadowNode);
        }
        object3D_animotion.setLightReceivingBitMask(2);

        //  object3D.setRotation(new Vector(1,1,1));
        show_animotion =10;
        final float v = position.distance(mViroView.getLastCameraPositionRealtime());
        object3D_animotion.setPosition(position);
        object3D_animotion.setScale(new Vector(0.055f*v, 0.055f*v, 0.055f*v));
        EnumSet<Node.TransformBehavior> transformBehavior1 = EnumSet.of(Node.TransformBehavior.BILLBOARD_Y);
        object3D_animotion.setTransformBehaviors(transformBehavior1);
        object3D_animotion.setOpacity(0f);
        object3D.setOpacity(0f);
        load_ok =false;
        object3D_animotion.loadModel(mViroView.getViroContext(), Uri.parse("file:///android_asset/TX.vrx"), Object3D.Type.FBX, new AsyncObject3DListener() {
            @Override
            public void onObject3DLoaded(final Object3D object, Object3D.Type type) {
                object3D_animotion.setOpacity(1f);
                object3D_animotion.setLightReceivingBitMask(2);
                object3D_animotion.getMaterials().get(0).setLightingModel(Material.LightingModel.PHYSICALLY_BASED);
                object3D_animotion.getMaterials().get(0).setRoughness(0.30f);
                object3D_animotion.getMaterials().get(0).setMetalness(0.14f);
                com.viro.core.Animation animation = object3D_animotion.getAnimation("Take 001");
                animation.play();
                final Handler handler = new Handler();
                show_model=0;
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        show_model++;

                        if (show_model<11) {
                            ambientLight.setIntensity(1000);
                            if (object3D_animotion.getOpacity()>0.4f) {
                                object3D_animotion.setOpacity(1 - show_model * 0.15f);
                            }else {
                                spotLight.setShadowOpacity(0.68f);
                                object3D_animotion.setOpacity(0f);
                            }
                            if (load_ok) {
                                object3D.setOpacity(show_model * 0.1f);
                            }
                            handler.postDelayed(this, 100);
                        }else {
                            handler.removeCallbacks(this);
                        }
                    }
                },800);
            }

            @Override
            public void onObject3DFailed(String s) {

            }
        });
        root_node.addChildNode(object3D_animotion);

        EnumSet<Node.TransformBehavior> transformBehavior =
                EnumSet.of(Node.TransformBehavior.BILLBOARD_Y);
        object3D.setTransformBehaviors(transformBehavior);

        mProductModelGroup.setPosition(position);


        if (kemoji_type.equals("banana_dance")||kemoji_type.equals("banana_tempt")){

            object3D.setScale(new Vector(0.028f*v, 0.028f*v, 0.028f*v));
        }else if (kemoji_type.equals("bama_respect")||kemoji_type.equals("bama_mindful")){
            object3D.setScale(new Vector(0.044f*v, 0.044f*v, 0.044f*v));

        }else if (kemoji_type.equals("apple_spin")||kemoji_type.equals("apple_thinking")){
            object3D.setScale(new Vector(0.028f*v, 0.028f*v, 0.028f*v));

        }   else  {
            object3D.setScale(new Vector(0.038f*v, 0.038f*v, 0.038f*v));

        }
        object3D.setPosition(new Vector(0,0,0));
        mProductModelGroup.addChildNode(object3D);
        root_node.addChildNode(mProductModelGroup);
        //  mScene.getRootNode().addChildNode(object3D);
        // Load the Android model asynchronously.
        object3D.loadModel(mViroView.getViroContext(), uri, Object3D.Type.FBX, new AsyncObject3DListener() {
            @Override
            public void onObject3DLoaded(final Object3D object, final Object3D.Type type) {
                load_ok =true;

                hand_hint.setVisibility(View.GONE);

                com.viro.core.Animation animation = object.getAnimation("Take 001");
                animation.setLoop(true);
                animation.play();
                object3D.setLightReceivingBitMask(2);
                object.getMaterials().get(0).setLightingModel(Material.LightingModel.PHYSICALLY_BASED);
                object.getMaterials().get(0).setRoughness(0.30f);
                object.getMaterials().get(0).setMetalness(0.14f);
                //object.getMaterials().get(0).setLightingModel(Material.LightingModel.BLINN);

                if (with_User) {
                    if (message != null){

                        if (message.isIsAnonymous()&&message.getOriginalSender()!=SharedPreferencesKey.getinfo(getActivity()).getId()){
                            user_image.setVisibility(View.VISIBLE);
                            user_text_image.setVisibility(View.GONE);
                            user_image.setImageResource(R.drawable.defalut_image_anoymous);
                            showModle(position);
                        }else {

                            avatarUrl =message.getAvatarUrl();
                            List<Contasnts> telFirend = SharedPreferencesKey.getFirend(getActivity());
                            if (telFirend!=null) {
                                for (int i = 0; i < telFirend.size(); i++) {
                                    if (message.getFrom() == telFirend.get(i).getId()) {
                                        avatarUrl = telFirend.get(i).getAvatarUrl();
                                        break;
                                    }
                                }
                            }
                            if (TextUtils.isEmpty(avatarUrl)) {
                                user_image.setVisibility(View.GONE);
                                user_text_image.setVisibility(View.VISIBLE);
                                user_text_image.setText(message.getFromname().charAt(0) + "");
                                showModle(position);
                            }else {

                                user_image.setVisibility(View.VISIBLE);
                                user_text_image.setVisibility(View.GONE);
                                ImageLoader.getInstance().displayImage(avatarUrl, user_image, new ImageLoadingListener() {
                                    @Override
                                    public void onLoadingStarted(String s, View view) {

                                    }

                                    @Override
                                    public void onLoadingFailed(String s, View view, FailReason failReason) {
                                        showModle(position);

                                    }

                                    @Override
                                    public void onLoadingComplete(String s, View view, Bitmap bitmap) {
                                        showModle(position);

                                    }

                                    @Override
                                    public void onLoadingCancelled(String s, View view) {

                                    }
                                });


                            }
                        }
                    }else {

                        if (((notification_json.getNotificationType().equals("anonymous_message"))&&Integer.valueOf(notification_json.getOriginalSender())!=SharedPreferencesKey.getinfo(getActivity()).getId()) || notification_json.getNotificationType().equals("minigame_mentioned") || (notification_json.getNotificationType().equals("minigame_friend_mentioned"))) {
                            user_image.setVisibility(View.VISIBLE);
                            user_text_image.setVisibility(View.GONE);
                            user_image.setImageResource(R.drawable.defalut_image_anoymous);
                            showModle(position);

                        } else {
                            user_image.setImageResource(R.drawable.default_profile);
                            if (TextUtils.isEmpty(avatarUrl)) {
                                List<Contasnts> telFirend = SharedPreferencesKey.getFirend(getActivity());
                                if (telFirend!=null) {
                                    for (int i = 0; i < telFirend.size(); i++) {
                                        if (notification_json.getFrom() == telFirend.get(i).getId()) {
                                            avatarUrl = telFirend.get(i).getAvatarUrl();
                                            break;
                                        }
                                    }
                                }
                                if (TextUtils.isEmpty(avatarUrl)) {
                                    user_image.setVisibility(View.GONE);
                                    user_text_image.setVisibility(View.VISIBLE);
                                    String name = null;
                                    for (int i = 0; i < telFirend.size(); i++) {
                                        if (notification_json.getFrom() == telFirend.get(i).getId()) {
                                            name = telFirend.get(i).getFirstName() + telFirend.get(i).getLastName();
                                            break;
                                        }
                                    }
                                    if (TextUtils.isEmpty(name)) {
                                        name = notification_json.getContents().getSenderX().getUsername();
                                    }
                                    user_text_image.setText(name.charAt(0) + "");
                                    showModle(position);

                                } else {
                                    user_image.setVisibility(View.VISIBLE);
                                    user_text_image.setVisibility(View.GONE);
                                    ImageLoader.getInstance().displayImage(avatarUrl, user_image, new ImageLoadingListener() {
                                        @Override
                                        public void onLoadingStarted(String s, View view) {

                                        }

                                        @Override
                                        public void onLoadingFailed(String s, View view, FailReason failReason) {
                                            showModle(position);

                                        }

                                        @Override
                                        public void onLoadingComplete(String s, View view, Bitmap bitmap) {
                                            showModle(position);

                                        }

                                        @Override
                                        public void onLoadingCancelled(String s, View view) {

                                        }
                                    });

                                }
                            } else {
                                List<Contasnts> telFirend = SharedPreferencesKey.getFirend(getActivity());
                                if (telFirend!=null) {
                                    for (int i = 0; i < telFirend.size(); i++) {
                                        if (notification_json.getFrom() == telFirend.get(i).getId()) {
                                            avatarUrl = telFirend.get(i).getAvatarUrl();
                                            break;
                                        }
                                    }
                                }
                                user_image.setVisibility(View.VISIBLE);
                                user_text_image.setVisibility(View.GONE);
                                ImageLoader.getInstance().displayImage(avatarUrl, user_image, new ImageLoadingListener() {
                                    @Override
                                    public void onLoadingStarted(String s, View view) {

                                    }

                                    @Override
                                    public void onLoadingFailed(String s, View view, FailReason failReason) {
                                        showModle(position);

                                    }

                                    @Override
                                    public void onLoadingComplete(String s, View view, Bitmap bitmap) {
                                        showModle(position);
                                    }

                                    @Override
                                    public void onLoadingCancelled(String s, View view) {

                                    }
                                });
                            }
                        }
                    }
                } else {
                    setState(1);
                    mCrosshairModel = null;
                    rippleBackground.setVisibility(View.VISIBLE);
                    rippleBackground.startRippleAnimation();
                    rippleBackground_send.setVisibility(View.VISIBLE);
                    rippleBackground_send.startRippleAnimation();
                    restartRecord();
                }
            }

            @Override
            public void onObject3DFailed(String s) {

            }
        });
        mProductModelGroup.setDragType(Node.DragType.FIXED_TO_WORLD);
        mProductModelGroup.setDragListener(new DragListener() {
            @Override
            public void onDrag(int i, Node node, Vector vector, Vector vector1) {
                // No-op
            }
        });


    }

**Comment by 544531645** [comment]
public void  showModle (Vector position){
        Bitmap bitmapFromAsset = convertViewToBitmap(dialog_view);
        // Bitmap bitmapFromAsset = ViroHelper.getBitmapFromAsset(this, "andy.png");
        Texture chineseCharTexture = new Texture(bitmapFromAsset, Texture.Format.RGBA8, true, true);
        Material material1 = new Material();
        material1.setDiffuseTexture(chineseCharTexture);
        material1.setLightingModel(Material.LightingModel.CONSTANT);
        float v = position.distance(mViroView.getLastCameraPositionRealtime());
        Surface surface = new Surface(0.1f, 0.1f);
        surface.setMaterials(Arrays.asList(material1));
        Node mTextNode = new Node();
        EnumSet<Node.TransformBehavior> transformBehavior =
                EnumSet.of(Node.TransformBehavior.BILLBOARD);
        mTextNode.setLightReceivingBitMask(0);
        mTextNode.setTransformBehaviors(transformBehavior);
        mTextNode.setScale(new Vector(1.2 * v, 1.2 * v, 1.2 * v));

        mTextNode.setPosition(new Vector( 0.1f,  - 0.06f,0)); //move this around to get into the lower right, maybe (.2, 0,0) would work better.
        mTextNode.setGeometry(surface);
        dialog_view.destroyDrawingCache();
        object3D.getParentNode().addChildNode(mTextNode);

    }

**Comment by 544531645** [comment]
this code

**Comment by 544531645** [comment]
if (result == null) {                        Vector add = mViroView.getLastCameraForwardRealtime().normalize().add(cameraPos);
 mCrosshairModel.setPosition(add);
}  else {  mCrosshairModel.setPosition(result.getPosition());
}
this createDroidAtPosition(final Vector position, ) the  position

**Comment by 544531645** [comment]
I see that your video is rotating 3d. How can you do that without rotating? Enumsets < Node. TransformBehavior > transformBehavior1 = enumsets. Of (Node. TransformBehavior. BILLBOARD_Y);

My shark added this,

**Comment by 544531645** [comment]
In video you rotate the model to the right, does this have to be done manually?

**Comment by dthian** [comment]
> In video you rotate the model to the right, does this have to be done manually?
Nope, you **don't have to do this manually.** Like what you have done above, you can simply set a transformBehavior on your mProductModelGroup with a BillBoard_Y configuration, so as to keep your entire layout (including the userimageNode circle, or other objects in that group, placed in reference to the shark) billboarded / fixed facing towards you. 

I've tried that and it still works, as show in the video below (imagine that the red box is your imageUser circle). 
![ezgif-5-77fce12081](https://user-images.githubusercontent.com/1904934/43415735-3af539be-93eb-11e8-9441-66708ce200e9.gif)

As such, to re-iterate the solution explained above, 
> Instead of placing the "userimage" circle node in world space, I recommend positioning it relative to the rotation of the shark (or the rotation of the parent node that rotates the shark). ... .... you should just parent the node with the "userimage" circle geometry, under the shark node (**or parent node containing the shark node, whichever does the rotation of the shark towards the user**) ... This will gurantee that the circle will always be place in front of the shark.

Thus, as seen in the video gif above, I've parented both the star model, and as well as my red box (this can be you "userimage" circle), both parented under **mProductModelGroup** (as mentioned in the solution above, to parent them under a node that controls the rotation of the shark towards the user). Thus, in this case the node that contains both my red box and Star is mProductModelGroup, and it controls the rotation in the sense of **billboarding of configuration BILLBOARD_Y controls the rotation of the shark towards the user.**

So for your project, you will need to parent both your Shark model, and as well as the node that contains your "userimage" circle under the node that controls the rotation of the shark (i think this is mProductModelGroup for your project, but correct me if i'm wrong here). You haven't yet answered the question below, so i'm not sure which node "userImage" circle corresponds to.

Can you also please answer the question below:
> Is userimageNode named something else in the example you have provided?

**Comment by 544531645** [comment]
before I add mScene.getRootNode.addChildNode(userimageNode);
showModle ()
the mTextNode is userimageNode

**Comment by 544531645** [comment]
i give mProductModelGroup. billboarding configuration BILLBOARD_Y work , before I give shark and useriamge add is not work .    thank you

**Comment by dthian** [comment]
So to confirm, has the main issue been fixed? (Sorry, I'm not sure if I understood the last comment correctly).

**Comment by 544531645** [comment]
yes , fixed  thank you , I will close this issue
