### ISSUE TITLE
Object3D not shown in ViroViewScene

### ISSUE THREAD

**Issue by LiamLuUW** [viromedia/virocore#173]
Hello, I have a ViroViewScene on top on another view and I want to show a Object3D with some animation. However, the Object3D is not rendered on the UI. I can show Box, Text on the UI by attach them to the rootNode, but if I attach object3D to the rootNode, it does not show. Any suggestions is appreciated. Thank you!

**Comment by achuvm** [comment]
Hi @LiamLuUW,

Have you seen the `Model Not Appearing?` callout on our `Viro3DObject` documentation page here: https://docs.viromedia.com/docs/viro3dobject

Most likely you haven't added a light to your scene and as a result, your object isn't lit up.

Thanks,
