### ISSUE TITLE
[Question][Feature Req] Culling Plane / Mask MaterialBlendMode

### ISSUE THREAD

**Issue by CesarCid** [viromedia/virocore#176]
I've been trying to achieve a visual effect in which an animated 3D dolphin is rendered differently when it goes under a plane or a certain Y position value.

I'd like to either have it dynamically rendered with a lower opacity (so as to look like it's underwater) or disappear completely in relation to it's current Y position, but I couldn't do it with the tools currently available.

That culling actually happens in ViroCore's Black Panther example gif, in this case from the wall/poster so it looks like he's emerging from it:
[https://github.com/viromedia/virocore/raw/master/ARBlackPanther/viro_black_panther_marker_demo.gif](url)
But when I test the one I've compiled the culling doesn't happen, so I couldn't use it as a guide.

I think that visual effect would be possible with either:
- a Culling Plane which blocks 3D Objects rendering. Similar to what currently happens with a 3D object when it's overlapping with a Portal entrance, but would still allow the camera image to be shown behind it.
- or some kind of Mask BlendMode on a material which would modify only the alpha value of what's rendered behind it, or would write on the Z buffer without rendering any color, similar to what's possible with ARKit's colorBufferWriteMask.

**Comment by CesarCid** [comment]
I just noticed that the bug in #51 is very close to one of the solutions I'm looking for, a material that blocks the rendering of what's behind it, but still allows the camera to be rendered

**Comment by radvani** [comment]
Hi @CesarCid, this is something that's on our near-term backlog. We'll try to get this in for our next release. Thank you for the input!

**Comment by radvani** [comment]
BTW, I believe what you're requesting is similar to this as well: https://github.com/viromedia/viro/issues/261

**Comment by dam00n** [comment]
This has been fixed/enabled in the latest release, ViroCore v1.11.0

Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases
