### ISSUE TITLE
Make "Bitmap" screenshot without saving to file

### ISSUE THREAD

**Issue by vanatka** [viromedia/virocore#18]
Hello Dear Viro team,
is there any way to make screenshot without save to file chain?
I just found only ViroMediaRecorder and recorder.takeScreenShotAsync method.
I need to have a bitmap. Is there any another public API or plans to provide it?

**Comment by dthian** [comment]
Hi @vanatka, currently we don't have an api that directly passes back a Bitmap object. However, you should be able to access the file on the device storage and convert that to a bitmap object to use (something similar to BitmapFactory.decodeFile()). Would that work for your use case? If not could you explain why and what your use case is? Thanks!

**Comment by vanatka** [comment]
@dthian many thanks for answer.
Actually I'm looking for ability to make a screenshot faster, because of recorder.takeScreenShotAsync takes time, then I'm decoding Bitmap from file system what takes time too. 
I have my own overlay & frame above the picture from camera with 3d model. 
So I want take bitmap, put overlay over "picture" from Viro and save it..without extra work with filesystem.

**Comment by dthian** [comment]
Thanks @vanatka! We've created a story to track this task of providing a Bitmap back. I'll update this thread once it has been pushed in the latest released of ViroCore.

**Comment by vanatka** [comment]
Many thanks, @dthian ! If you have any ETA and can share it, it will be super sexy, we'll plan our release accordingly. Many thanks, kind regards, Ivan

**Comment by achuvm** [comment]
Hi @vanatka,

We updated ViroCore to version 1.3 and have updated the API to also return a Bitmap:
https://developer.viromedia.com/virocore/reference/com/viro/core/ViroMediaRecorder.ScreenshotFinishListener.html

Instructions for updating can be found here: https://virocore.viromedia.com/docs/releases#section-upgrade-instructions

Let us know if this works for you.

**Comment by vanatka** [comment]
hello @achuvm , many thanks, for update!
Is there a way to receive bitmap without filepath? 
Because of if you are providing and file path, that means that you are writing something to the storage and it is additional performance consumption, so I wanted make it with the best performance, without io to file system. 

Many thanks, kind regards, Ivan

**Comment by achuvm** [comment]
Hi @vanatka,

Sorry, we missed this request for our release yesterday (ViroCore) and today (React).

We'll add this to our backlog for our next release.

Thanks again,

**Comment by dam00n** [comment]
@vanatka this has been fixed in our latest release ViroCore 1.4.1

You can find release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases#virocore-v141
