### ISSUE TITLE
Quad cornerRadius

### ISSUE THREAD

**Issue by browniefed** [viromedia/virocore#181]
In iOS SceneKit a node can have a `cornerRadius` to rounded the corners. I can't seem to find a way to do that with ViroCore except possibly using `Polygon` with a lot of verticies?

Any help would be appreciated

**Comment by dam00n** [comment]
Hi @browniefed, correct, we don't support rounded corners at this time. You can use Polygon with a lot of verts to create it yourself as you mentioned. I have added this to our backlog as a feature request and will update this issue when we have more info on the feature.

**Comment by browniefed** [comment]
Thanks, looking forward to it.

**Comment by dam00n** [comment]
Let's leave this open so we can track the feature request and update with more info later.
