### ISSUE TITLE
Origin/Pivot Point of Node Position

### ISSUE THREAD

**Issue by browniefed** [viromedia/virocore#183]
Hello, I looked around and didn't seem to see any reference material on the topic for Viro.

I was wondering what the origin point / pivot point of a node was. Is it the center of the node, bottom left, top right? Specifically when the geometry is a text element.

Thank you

**Comment by achuvm** [comment]
Hi @browniefed,

The default pivot is the center of the object.

If you want to change the pivot, check out `setRotationPivot()` on the `Node.java` object:

https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html#setRotationPivot(com.viro.core.Vector)

Hope that helps,

- Andy

**Comment by browniefed** [comment]
Thanks for the information
