### ISSUE TITLE
[Feature Request] Space-efficient image recognition format

### ISSUE THREAD

**Issue by ryan-hodgman** [viromedia/virocore#184]
Hey there, our team is working on usecases that require storage of potentially hundreds of image targets in a cloud instance. We're beginning to hit limits with our current approach of storing images remotely as PNGs, facing downloads approaching 250MBs. This is obviously going to severely impact our user's experience, so we're seeking more efficient storage formats.

https://developers.google.com/ar/develop/java/augmented-images/

> The database stores a compressed representation of the reference images. Each image occupies ~6KB.

It would seem that under the hood ARCore has a means of compressing the specified image targets into a minimal data format for image recognition. Do you have any ability to extract and expose this data format for us to be able to store elsewhere? We would specifically want to mirror the ARCore data in order to avoid any degradation in image recognition performance.

If this is an issue we need to escalate to the ARCore team, that's fine, I just wanted to check what was possible with the [AugmentedImageDatabase](https://developers.google.com/ar/reference/java/com/google/ar/core/AugmentedImageDatabase) that they already expose.

**Comment by achuvm** [comment]
Hi @ryan-hodgman,

Thanks for this feature request, unfortunately it's not something we currently support. However we'll add it to our backlog as this does sound like a feature we should support.

Thanks,

**Comment by dam00n** [comment]
Support for augmented images added in ViroCore v.1.10.0

Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases
