### ISSUE TITLE
new version don't find method setExtrusionDepth(float extrusionDepth)

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#185]
I update to 1.9.0 , but Text no have this method

**Comment by 544531645** [comment]
AndroidViewTexture
I also not found

**Comment by radvani** [comment]
Hi, ViroCore 1.9.0 was released last night, but the Hello World examples we use in the 'Getting Started' guide were only updated this morning, so it's possible you still have 1.8.2. You can check by looking at the viro-core AAR file: the filename should be `virocore-release-v_1_9_0.aar` if you're on 1.9.0.

**Comment by radvani** [comment]
Also, if you're updating an existing project to ViroCore 1.9.0, make sure you update your project's gradle file to point to the 1.9.0 AAR file.

**Comment by 544531645** [comment]
![image](https://user-images.githubusercontent.com/15622364/43814070-1648d4a6-9afb-11e8-9ec2-febdbe7dc7e0.png)
![image](https://user-images.githubusercontent.com/15622364/43814075-1c0020ca-9afb-11e8-9f44-652bc7a08f68.png)

**Comment by 544531645** [comment]
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package com.viro.core;

public class Text extends Geometry {
    private static final String DEFAULT_FONT_FAMILY = "Roboto";
    private static final int DEFAULT_FONT_SIZE = 12;
    private static final Text.FontStyle DEFAULT_FONT_STYLE;
    private static final Text.FontWeight DEFAULT_FONT_WEIGHT;
    private static final long DEFAULT_COLOR = -1L;
    private static final Text.HorizontalAlignment DEFAULT_HORIZONTAL_ALIGNMENT;
    private static final Text.VerticalAlignment DEFAULT_VERTICAL_ALIGNMENT;
    private static final Text.LineBreakMode DEFAULT_LINE_BREAK_MODE;
    private static final Text.ClipMode DEFAULT_CLIP_MODE;
    private static final int DEFAULT_MAX_LINES = 0;
    private ViroContext mViroContext;
    private String mText;
    private float mWidth;
    private float mHeight;
    private String mFontFamilyName;
    private int mFontSize;
    private Text.FontStyle mFontStyle;
    private Text.FontWeight mFontWeight;
    private long mColor;
    private Text.HorizontalAlignment mHorizontalAlignment;
    private Text.VerticalAlignment mVerticalAlignment;
    private Text.LineBreakMode mLineBreakMode;
    private Text.ClipMode mClipMode;
    private int mMaxLines;

    public Text(ViroContext viroContext, String text, float width, float height) {
        this(viroContext, text, "Roboto", 12, DEFAULT_FONT_STYLE, DEFAULT_FONT_WEIGHT, -1L, width, height, DEFAULT_HORIZONTAL_ALIGNMENT, DEFAULT_VERTICAL_ALIGNMENT, DEFAULT_LINE_BREAK_MODE, DEFAULT_CLIP_MODE, 0);
    }

    /** @deprecated */
    @Deprecated
    public Text(ViroContext viroContext, String text, String fontFamilies, int size, long color, float width, float height, Text.HorizontalAlignment horizontalAlignment, Text.VerticalAlignment verticalAlignment, Text.LineBreakMode lineBreakMode, Text.ClipMode clipMode, int maxLines) {
        this(viroContext, text, fontFamilies, size, DEFAULT_FONT_STYLE, DEFAULT_FONT_WEIGHT, color, width, height, horizontalAlignment, verticalAlignment, lineBreakMode, clipMode, maxLines);
    }

    private Text(ViroContext viroContext, String text, String fontFamilies, int size, Text.FontStyle fontStyle, Text.FontWeight fontWeight, long color, float width, float height, Text.HorizontalAlignment horizontalAlignment, Text.VerticalAlignment verticalAlignment, Text.LineBreakMode lineBreakMode, Text.ClipMode clipMode, int maxLines) {
        this.mFontFamilyName = "Roboto";
        this.mFontSize = 12;
        this.mFontStyle = DEFAULT_FONT_STYLE;
        this.mFontWeight = DEFAULT_FONT_WEIGHT;
        this.mColor = -1L;
        this.mHorizontalAlignment = DEFAULT_HORIZONTAL_ALIGNMENT;
        this.mVerticalAlignment = DEFAULT_VERTICAL_ALIGNMENT;
        this.mLineBreakMode = DEFAULT_LINE_BREAK_MODE;
        this.mClipMode = DEFAULT_CLIP_MODE;
        this.mMaxLines = 0;
        this.mViroContext = viroContext;
        this.mText = text;
        this.mFontFamilyName = fontFamilies;
        this.mFontSize = size;
        this.mFontStyle = fontStyle;
        this.mFontWeight = fontWeight;
        this.mColor = color;
        this.mWidth = width;
        this.mHeight = height;
        this.mHorizontalAlignment = horizontalAlignment;
        this.mVerticalAlignment = verticalAlignment;
        this.mLineBreakMode = lineBreakMode;
        this.mClipMode = clipMode;
        this.mMaxLines = maxLines;
        this.mNativeRef = this.nativeCreateText(this.mViroContext.mNativeRef, this.mText, this.mFontFamilyName, this.mFontSize, this.mFontStyle.getIntValue(), this.mFontWeight.getIntValue(), this.mColor, this.mWidth, this.mHeight, this.mHorizontalAlignment.getStringValue(), this.mVerticalAlignment.getStringValue(), this.mLineBreakMode.getStringValue(), this.mClipMode.getStringValue(), this.mMaxLines);
    }

    protected void finalize() throws Throwable {
        try {
            this.dispose();
        } finally {
            super.finalize();
        }

    }

    public void dispose() {
        if (this.mNativeRef != 0L) {
            this.nativeDestroyText(this.mNativeRef);
            this.mNativeRef = 0L;
        }

    }

    public String getText() {
        return this.mText;
    }

    public void setText(String textString) {
        this.mText = textString;
        this.nativeSetText(this.mNativeRef, textString);
    }

    /** @deprecated */
    @Deprecated
    public String getFontFamilyName() {
        return this.mFontFamilyName;
    }

    public String getFontFamilies() {
        return this.mFontFamilyName;
    }

    /** @deprecated */
    @Deprecated
    public void setFontFamilyName(String fontFamily) {
        this.mFontFamilyName = fontFamily;
        this.nativeSetFont(this.mViroContext.mNativeRef, this.mNativeRef, this.mFontFamilyName, this.mFontSize, this.mFontStyle.getIntValue(), this.mFontWeight.getIntValue());
    }

    public void setFontFamilies(String fontFamilies) {
        this.mFontFamilyName = fontFamilies;
        this.nativeSetFont(this.mViroContext.mNativeRef, this.mNativeRef, this.mFontFamilyName, this.mFontSize, this.mFontStyle.getIntValue(), this.mFontWeight.getIntValue());
    }

    public int getFontSize() {
        return this.mFontSize;
    }

    public void setFontSize(int fontSize) {
        this.mFontSize = fontSize;
        this.nativeSetFont(this.mViroContext.mNativeRef, this.mNativeRef, this.mFontFamilyName, this.mFontSize, this.mFontStyle.getIntValue(), this.mFontWeight.getIntValue());
    }

    public Text.FontStyle getFontStyle() {
        return this.mFontStyle;
    }

    public void setFontStyle(Text.FontStyle fontStyle) {
        this.mFontStyle = fontStyle;
        this.nativeSetFont(this.mViroContext.mNativeRef, this.mNativeRef, this.mFontFamilyName, this.mFontSize, this.mFontStyle.getIntValue(), this.mFontWeight.getIntValue());
    }

    public Text.FontWeight getFontWeight() {
        return this.mFontWeight;
    }

    public void setFontWeight(Text.FontWeight fontWeight) {
        this.mFontWeight = fontWeight;
        this.nativeSetFont(this.mViroContext.mNativeRef, this.mNativeRef, this.mFontFamilyName, this.mFontSize, this.mFontStyle.getIntValue(), this.mFontWeight.getIntValue());
    }

    public long getColor() {
        return this.mColor;
    }

    public void setColor(long color) {
        this.mColor = color;
        this.nativeSetColor(this.mNativeRef, color);
    }

    public float getWidth() {
        return this.mWidth;
    }

    public void setWidth(float width) {
        this.mWidth = width;
        this.nativeSetWidth(this.mNativeRef, width);
    }

    public float getHeight() {
        return this.mHeight;
    }

    public void setHeight(float height) {
        this.mHeight = height;
        this.nativeSetHeight(this.mNativeRef, height);
    }

    public Text.HorizontalAlignment getHorizontalAlignment() {
        return this.mHorizontalAlignment;
    }

    public void setHorizontalAlignment(Text.HorizontalAlignment horizontalAlignment) {
        this.mHorizontalAlignment = horizontalAlignment;
        this.nativeSetHorizontalAlignment(this.mNativeRef, horizontalAlignment.getStringValue());
    }

    public Text.VerticalAlignment getVerticalAlignment() {
        return this.mVerticalAlignment;
    }

    public void setVerticalAlignment(Text.VerticalAlignment verticalAlignment) {
        this.mVerticalAlignment = verticalAlignment;
        this.nativeSetVerticalAlignment(this.mNativeRef, verticalAlignment.getStringValue());
    }

    public Text.LineBreakMode getLineBreakMode() {
        return this.mLineBreakMode;
    }

    public void setLineBreakMode(Text.LineBreakMode lineBreakMode) {
        this.mLineBreakMode = lineBreakMode;
        this.nativeSetLineBreakMode(this.mNativeRef, lineBreakMode.getStringValue());
    }

    public Text.ClipMode getClipMode() {
        return this.mClipMode;
    }

    public void setClipMode(Text.ClipMode clipMode) {
        this.mClipMode = clipMode;
        this.nativeSetClipMode(this.mNativeRef, clipMode.getStringValue());
    }

    public int getMaxLines() {
        return this.mMaxLines;
    }

    public void setMaxLines(int maxLines) {
        this.mMaxLines = maxLines;
        this.nativeSetMaxLines(this.mNativeRef, maxLines);
    }

    private native long nativeCreateText(long var1, String var3, String var4, int var5, int var6, int var7, long var8, float var10, float var11, String var12, String var13, String var14, String var15, int var16);

    private native void nativeDestroyText(long var1);

    private native void nativeSetText(long var1, String var3);

    private native void nativeSetFont(long var1, long var3, String var5, int var6, int var7, int var8);

    private native void nativeSetColor(long var1, long var3);

    private native void nativeSetWidth(long var1, float var3);

    private native void nativeSetHeight(long var1, float var3);

    private native void nativeSetHorizontalAlignment(long var1, String var3);

    private native void nativeSetVerticalAlignment(long var1, String var3);

    private native void nativeSetLineBreakMode(long var1, String var3);

    private native void nativeSetClipMode(long var1, String var3);

    private native void nativeSetMaxLines(long var1, int var3);

    public static Text.TextBuilder builder() {
        return new Text.TextBuilder();
    }

    static {
        DEFAULT_FONT_STYLE = Text.FontStyle.Normal;
        DEFAULT_FONT_WEIGHT = Text.FontWeight.Regular;
        DEFAULT_HORIZONTAL_ALIGNMENT = Text.HorizontalAlignment.CENTER;
        DEFAULT_VERTICAL_ALIGNMENT = Text.VerticalAlignment.CENTER;
        DEFAULT_LINE_BREAK_MODE = Text.LineBreakMode.WORD_WRAP;
        DEFAULT_CLIP_MODE = Text.ClipMode.CLIP_TO_BOUNDS;
    }

    public static class TextBuilder {
        private ViroContext mViroContext;
        private String mText;
        private float mWidth;
        private float mHeight;
        private String mFontFamilyName = "Roboto";
        private int mFontSize = 12;
        private Text.FontStyle mFontStyle;
        private Text.FontWeight mFontWeight;
        private long mColor;
        private Text.HorizontalAlignment mHorizontalAlignment;
        private Text.VerticalAlignment mVerticalAlignment;
        private Text.LineBreakMode mLineBreakMode;
        private Text.ClipMode mClipMode;
        private int mMaxLines;

        public TextBuilder() {
            this.mFontStyle = Text.DEFAULT_FONT_STYLE;
            this.mFontWeight = Text.DEFAULT_FONT_WEIGHT;
            this.mColor = -1L;
            this.mHorizontalAlignment = Text.DEFAULT_HORIZONTAL_ALIGNMENT;
            this.mVerticalAlignment = Text.DEFAULT_VERTICAL_ALIGNMENT;
            this.mLineBreakMode = Text.DEFAULT_LINE_BREAK_MODE;
            this.mClipMode = Text.DEFAULT_CLIP_MODE;
            this.mMaxLines = 0;
        }

        public Text.TextBuilder viroContext(ViroContext mViroContext) {
            this.mViroContext = mViroContext;
            return this;
        }

        public Text.TextBuilder textString(String mText) {
            this.mText = mText;
            return this;
        }

        /** @deprecated */
        @Deprecated
        public Text.TextBuilder fontFamilyName(String mFontFamilyName) {
            this.mFontFamilyName = mFontFamilyName;
            return this;
        }

        public Text.TextBuilder fontFamilies(String mFontFamilyName) {
            this.mFontFamilyName = mFontFamilyName;
            return this;
        }

        public Text.TextBuilder fontSize(int mFontSize) {
            this.mFontSize = mFontSize;
            return this;
        }

        public Text.TextBuilder fontStyle(Text.FontStyle style) {
            this.mFontStyle = style;
            return this;
        }

        public Text.TextBuilder fontWeight(Text.FontWeight weight) {
            this.mFontWeight = weight;
            return this;
        }

        public Text.TextBuilder color(long mColor) {
            this.mColor = mColor;
            return this;
        }

        public Text.TextBuilder width(float mWidth) {
            this.mWidth = mWidth;
            return this;
        }

        public Text.TextBuilder height(float mHeight) {
            this.mHeight = mHeight;
            return this;
        }

        public Text.TextBuilder horizontalAlignment(Text.HorizontalAlignment mHorizontalAlignment) {
            this.mHorizontalAlignment = mHorizontalAlignment;
            return this;
        }

        public Text.TextBuilder verticalAlignment(Text.VerticalAlignment mVerticalAlignment) {
            this.mVerticalAlignment = mVerticalAlignment;
            return this;
        }

        public Text.TextBuilder lineBreakMode(Text.LineBreakMode mLineBreakMode) {
            this.mLineBreakMode = mLineBreakMode;
            return this;
        }

        public Text.TextBuilder clipMode(Text.ClipMode mClipMode) {
            this.mClipMode = mClipMode;
            return this;
        }

        public Text.TextBuilder maxLines(int mMaxLines) {
            this.mMaxLines = mMaxLines;
            return this;
        }

        public Text build() {
            return new Text(this.mViroContext, this.mText, this.mFontFamilyName, this.mFontSize, this.mFontStyle, this.mFontWeight, this.mColor, this.mWidth, this.mHeight, this.mHorizontalAlignment, this.mVerticalAlignment, this.mLineBreakMode, this.mClipMode, this.mMaxLines);
        }
    }

    public static enum ClipMode {
        CLIP_TO_BOUNDS("ClipToBounds"),
        NONE("None");

        private String mStringValue;

        private ClipMode(String value) {
            this.mStringValue = value;
        }

        public String getStringValue() {
            return this.mStringValue;
        }
    }

    public static enum LineBreakMode {
        WORD_WRAP("WordWrap"),
        CHAR_WRAP("CharWrap"),
        JUSTIFY("Justify"),
        NONE("None");

        private String mStringValue;

        private LineBreakMode(String value) {
            this.mStringValue = value;
        }

        public String getStringValue() {
            return this.mStringValue;
        }
    }

    public static enum VerticalAlignment {
        TOP("Top"),
        BOTTOM("Bottom"),
        CENTER("Center");

        private String mStringValue;

        private VerticalAlignment(String value) {
            this.mStringValue = value;
        }

        public String getStringValue() {
            return this.mStringValue;
        }
    }

    public static enum HorizontalAlignment {
        LEFT("Left"),
        RIGHT("Right"),
        CENTER("Center");

        private String mStringValue;

        private HorizontalAlignment(String value) {
            this.mStringValue = value;
        }

        public String getStringValue() {
            return this.mStringValue;
        }
    }

    public static enum FontWeight {
        UltraLight(100),
        Thin(200),
        Light(300),
        Regular(400),
        Medium(500),
        Semibold(600),
        Bold(700),
        Heavy(800),
        ExtraBlack(900);

        private int mIntValue;

        private FontWeight(int value) {
            this.mIntValue = value;
        }

        public int getIntValue() {
            return this.mIntValue;
        }
    }

    public static enum FontStyle {
        Normal(0),
        Italic(1);

        private int mIntValue;

        private FontStyle(int value) {
            this.mIntValue = value;
        }

        public int getIntValue() {
            return this.mIntValue;
        }
    }
}

**Comment by 544531645** [comment]
I downland demo have , but I copy 1.9.0aar  to my project it not work ,I don't know why

**Comment by 544531645** [comment]
I find it , should cache qustion , the code not update , I copy new jar to my project root cache jar ,replace it work

**Comment by 544531645** [comment]
I set color , but always is white @radvani

**Comment by 544531645** [comment]
I change tLightReceivingBitMask ,become black ..but I set                text.setColor(Color.parseColor("#43dffd"));
