### ISSUE TITLE
Two Sided Quad

### ISSUE THREAD

**Issue by LiamLuUW** [viromedia/virocore#187]
Hi, I am wondering is there a way to make Quad be a double sided plane so user can see it regardless of the y-axis. If not, is there a way to let the nodes to follow camera's direction. Thank you!

**Comment by dam00n** [comment]
Hi @LiamLuUW you can use billboarding to make a node always face the camera -> https://developer.viromedia.com/virocore/reference/com/viro/core/Node.TransformBehavior.html

**Comment by LiamLuUW** [comment]
I noticed billboard actually clear my previous applied rotations, is there a way to avoid it?

**Comment by LiamLuUW** [comment]
Awesome, thank you for the help!
