### ISSUE TITLE
3d text space question 

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#188]
when word is "who are you " , if have space it only show who ... this how should I do

**Comment by radvani** [comment]
Hi @544531645, did you make sure the width of your text is wide enough? If it's not, then the text will cut off. Alternatively, you can also set the clip mode to NONE. For example, try:

```
Text text = Text.builder().viroContext(mViroView.getViroContext()).textString("Who are you").
                fontFamilies("Roboto").fontSize(25).color(Color.WHITE).width(2.5f).height(1f).
                horizontalAlignment(Text.HorizontalAlignment.LEFT).verticalAlignment(Text.VerticalAlignment.TOP).
                clipMode(Text.ClipMode.NONE).lineBreakMode(Text.LineBreakMode.WORD_WRAP).build();
```

**Comment by 544531645** [comment]
no space show whoareyou, have space show who , I think not width qustion @radvani

**Comment by 544531645** [comment]
chinese can show "你们你们在哪在哪“ or more word at one line  , why english only show "who" need next line @radvani

**Comment by 544531645** [comment]
How can you control the width so that the width of Chinese is the same as that of English

**Comment by 544531645** [comment]
![image](https://user-images.githubusercontent.com/15622364/44069286-9b6bb7ca-9fb0-11e8-8957-4e9019d9ee2d.png)
![image](https://user-images.githubusercontent.com/15622364/44069292-9f4dbf64-9fb0-11e8-890a-bbbf4cc1d7cc.png)

**Comment by radvani** [comment]
Hi @544531645, did you close this because you figured out a way to make it work? Or is this still an issue for you?

**Comment by 544531645** [comment]
@radvani I find a way to make it work . 
    Vecotor positionRealtime=mViroView.getLastCameraForwardRealtime().normalize().add(cameraPos);
this if is it realtime ?
