### ISSUE TITLE
Change min sdk from 21 or remove constraint

### ISSUE THREAD

**Issue by superuserdid** [viromedia/virocore#19]
Currently right now developers have to change their min sdk to 21 to use Viro. While it makes sense, this seems really short sighted as it hardly takes into account an app that is not primarily AR or already existing with users that are not on 21. 
Using `tools:overrideLibrary="com.viro.renderer"` allows for compilation but of course, still breaks when trying to use. It would seem that ideally users should be able to integrate or start with Viro fairly easily, especially to avoid having to split their project to support two apks on the play store. The current Android SDK just crashes when code is referring to features that are not supported. It allows for the developer to be able to do things like check the sdk and choose whether or not to allow the user to access that feature. 

Perhaps it is something to consider.

**Comment by achuvm** [comment]
Hi @superuserdid,

Can you explain how `tools:overrideLibrary="com.viro.renderer"` breaks when trying to use?

1. What is the SDK version of the device you're trying to run on?
2. You mention that the SDK crashes when the code is "referring" to features. Can you explain how you are "referring" to the features? ie. if you're simply doing `ViroViewARCore.class` or are you doing a `ViroViewARCore view = new ViroViewARCore()`. 

We do suspect it's a result of the static loading of libraries we have in our classes. The solution we are considering is to remove the logic from the static blocks and instead have our users invoke a static method instead. In the meantime, there might be a way to not load the Viro classes when under the minSdkVersion that we require.

**Comment by achuvm** [comment]
Hi @superuserdid,

Actually, you should be able to use the `tools:overrideLibrary="com.viro.renderer"` to bypass the `minSdkVersion 21` requirement we have on our library as long as you do not create any instances of the `ViroView*` classes. The static blocks that load the native libraries shouldn't run unless a instance of a `ViroView*` is being created.

Let us know if you're still seeing it as an issue.

Thanks,

**Comment by achuvm** [comment]
Hi @superuserdid,

I created a sample project here: https://drive.google.com/file/d/18UR8GhBFgc7ivmq7ZvJM1RnhVLd7UwAi/view?usp=sharing

If you take a look, it's our ViroCore Hello World project from our [Getting Started](https://virocore.viromedia.com/docs/getting-started).

The changes I made are as follows:

1. In `build.gradle (app)`, changed `minSdkVersion 21` to `minSdkVersion 15`.
2. In `AndroidManifest.xml`, added the line `<uses-sdk tools:overrideLibrary="com.viro.renderer, com.google.vr.cardboard"/>`
3. In `ViroActivity.java : onCreate()`, added a check `if (Build.VERSION.SDK_INT < 21) {` which returns if the current SDK version is less than 21.
4. In `ViroActivity.java`'s Activity lifecycle functions (`onCreate`, `onStop`, etc), added a null check around `mViroView`.
5. In `styles.xml`, changed the `AppTheme` to `android:Theme.Holo.Light` because the default `Material` theme is SDK 21+.

If you try it out, don't for get to add your *API_KEY* in the `AndroidManifest.xml`.

On devices with SDK version < 21, you should just see a blank application (but no crash) and on devices with SDK version > 21, it should run AR or VR (depending on your gradle build version).

We've tested this on devices with SDK version 19, 15 and 25. 

Let me know if you have any issues getting this to work!

**Comment by superuserdid** [comment]
Hi @achuvm 

It breaks because the `.so` cannot be loaded so when that line is added in the manifest, it breaks for api 21+. 

1. SDK - 21+ when it crashes. My min sdk is 16.

2. I'm using it as an instance just like you are in the sample project though I do not know the difference between yours and mine.

Correct, the issue is with the `.so` loading.

I am confused when you say don't create an instance of the class. You create an instance of the class in `onCreate()` of the sample project by doing `mViroView = new ViroViewARCore()`. I am creating one the same way but adding to a frame layout programatically. I do see yours is working though and have to look into it more about why.

**Comment by superuserdid** [comment]
I took a deeper look at the example you gave and am still unsure why yours works and mine doesn't. Im following the steps in detail. The crash I get is this:

> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.scripps.android.company-PXxTBzGAxvYG03lNgjN1fw==/base.apk"],nativeLibraryDirectories=[/data/app/com.scripps.android.company-PXxTBzGAxvYG03lNgjN1fw==/lib/arm64, /data/app/com.scripps.android.company-PXxTBzGAxvYG03lNgjN1fw==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libgvr.so"

**Comment by achuvm** [comment]
Hi @superuserdid,

The code I provided has the check `if (Build.VERSION.SDK_INT < 21)` that exits (`returns`) the `onCreate()` function before `mViroView = new ViroViewARCore()` is called if the Android SDK version is less than 21. So while the code is there, it is never executed and as a result, doesn't error out.

As for the new error you posted, that looks like your project hasn't been configured with the GVR library (as per this StackOverflow [question](https://stackoverflow.com/questions/27186726/java-lang-unsatisfiedlinkerror-dalvik-system-pathclassloader)).

If you look at the provided project's `build.gradle (Module: app)` file, you can see that we have a few dependencies, but the main ones are:

```
    ...
    compile 'com.google.android.exoplayer:exoplayer:r2.2.0'
    ...
    compile project(':gvr_common')
    compile project(':arcore_client')
    compile project(':viro_core')
    compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-ddb:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-ddb-mapper:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.+'
```

All the dependencies above that come from `com.*` are loaded from their respective maven repositories. However, the following dependencies have to be manually added to your project:

```
    compile project(':gvr_common')
    compile project(':arcore_client')
    compile project(':viro_core')
```

If you look inside the `virocore-helloworld` project, you should see these files:

```
virocore-helloworld$ ls
README.md		build.gradle		gradlew.bat		viro_core
app			gradle			gvr_common		virocore-helloworld.iml
arcore_client		gradle.properties	local.properties
build			gradlew	settings.gradle
```

You should copy over the `gvr_common`, `arcore_client` and `viro_core` directories and update your `settings.gradle` file to include the added libraries, ie. the `settings.gradle` in `virocore-helloworld` looks like the following:

```
include ':app', ':arcore_client', ':gvr_common', ':viro_core'
```

Let me know if that works for you.

**Comment by superuserdid** [comment]
Hi @achuvm,

Thank you for all your help. I figured out the issue and it would be good for others to know how to avoid. My issue was that I was compiling the added `gvr`, `arcore_client` and `viro_core` projects using 

`implementation project(path: ':gvr_common', configuration 'default')`

instead you should use

`implementation project(':gvr_common')`

If you are copy/pasting from the sample project you shouldn't run into this issue. I ran into by trying to update for Android Studio 3.0.

Hope this helps and thanks again @achuvm .

**Comment by dam00n** [comment]
Closing issue as solution has been provided. Also will update our documentation to reflect feedback
