### ISSUE TITLE
'com.viro.core.Surface' is deprecated.

### ISSUE THREAD

**Issue by HLneoh** [viromedia/virocore#196]
Hi, I am trying to import 'com.viro.core.Surface' to make AR shadow as example in below. 
![image](https://user-images.githubusercontent.com/25906607/44865434-e4f2ac80-acb4-11e8-873b-7b74998f7aab.png)

However, it showed "com.viro.core.Surface is deprecated. This inspection reports where deprecated code is used in specfic inspection scope."

**Comment by dam00n** [comment]
This class is deprecated. Use Quad in place of this class -> https://developer.viromedia.com/virocore/reference/com/viro/core/Quad.html
