### ISSUE TITLE
gif question 

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#197]
I have seen the addition of GIF in the new release. Can the GIF be loaded in the Texture or can the view of GIF be loaded in the way of AndroidView?

**Comment by dthian** [comment]
Hey @544531645, GIFs are officially supported via Textures as shown [here](https://developer.viromedia.com/virocore/reference/com/viro/core/AnimatedTexture.html).

Loading GIFs through AndroidViews aren't officially supported, but you can give it a try and see how it turns out.
