### ISSUE TITLE
How to load .mtl file of Object

### ISSUE THREAD

**Issue by mistrydarshan99** [viromedia/virocore#2]
Hello,

When I have to create 3D model, I have got .mtl file related to the 3D model. So how to load a .mtl file in virocore ?

**Comment by radvani** [comment]
Hi Darshan,

To load the MTL file, just make sure of two things:

1. If you open the OBJ file in a text editor, the MTL file should be listed inside. There should be a line of the form: 
```
mtllib {path to MTL file}.mtl
```
For example, if your MTL is named materials.mtl, you should see something like this
```
mtllib materials.mtl
```
This is just a sanity check to make sure your OBJ file is actually referencing an MTL.

2. Place the MTL file in the same directory as your OBJ file.

Now when you load the OBJ file it will automatically find the MTL. Please also note that any textures referenced by the MTL also need to be in the same directory as the OBJ (and MTL) file.

If this still doesn't work for you, you can send us your OBJ and MTL files to us at support@viromedia.com and we can dig in further to see what the issue may be.

**Comment by mistrydarshan99** [comment]
Hello,

Can you provide one sample code for in which object use MTL file ? For texture we have to used below code:

`final Bitmap bot = ViroHelper.getBitmapFromAsset(this, "andy.png");`

> 
>         object3D.loadModel(Uri.parse("file:///android_asset/ironman.obj"), Object3D.Type.OBJ, new AsyncObject3DListener() {
>             @Override
>             public void onObject3DLoaded(final Object3D object, final Object3D.Type type) {
>                 // When the model is loaded, set the texture associated with this OBJ.
>                 Texture objectTexture = new Texture(bot, Texture.Format.RGBA8, false, false);
>                 Material material = new Material();
>                 material.setDiffuseTexture(objectTexture);
>                 object3D.getGeometry().setMaterials(Arrays.asList(material));
>             }
> 
>             @Override
>             public void onObject3DFailed(String s) {
>             }
>         });

 

for MTL what we change in above code that I don't know? I have place MTL file and object file in android asset folder. But it's not used mtl file.

**Comment by radvani** [comment]
Hi Darshan,

When using an MTL file, you don't actually have to set the material yourself: the engine will do that automatically if it successfully reads the MTL. So the code would look more like this:

```
object3D.loadModel(Uri.parse("file:///android_asset/ironman.obj"), Object3D.Type.OBJ, new AsyncObject3DListener() {
        @Override
        public void onObject3DLoaded(final Object3D object, final Object3D.Type type) {
        }

        @Override
        public void onObject3DFailed(String s) {
        }
    });
```
This assumes though, that the MTL file is correctly reference by the OBJ, and that the textures being referenced by the MTL are also present in the same directory as the OBJ.

If you can't get it to appear, feel free to send me the OBJ, MTL, and texture files at support@viromedia.com and I'll see if I can make it work. Thanks!

**Comment by dam00n** [comment]
Hi Darshan, thanks for emailing over your model. We were able to get your model to load and display in ViroCore. Full code below:

`final Bitmap bot = ViroHelper.getBitmapFromAsset(this, "cactusWren_BaseColor.png");
final Object3D object3D = new Object3D();
object3D.setPosition(position);
mScene.getRootNode().addChildNode(object3D);

// Load the Android model asynchronously.
object3D.loadModel(Uri.parse("file:///android_asset/cactusWren.obj"), Object3D.Type.OBJ, new AsyncObject3DListener() {
    @Override
    public void onObject3DLoaded(final Object3D object, final Object3D.Type type) {
        // When the model is loaded, set the texture associated with this OBJ.
        Texture objectTexture = new Texture(bot, Texture.Format.RGBA8, false, false);
        Material material = new Material();
        material.setDiffuseTexture(objectTexture);
        object3D.getGeometry().setMaterials(Arrays.asList(material));
    }

    @Override
    public void onObject3DFailed(String s) {
    }
});`

The code is doing the following:

1)Loads the texture asset cactusWren_baseColor.png. You can see the ViroHelper code from the ViroCore example in github here: https://github.com/viromedia/virocore/blob/master/app/src/main/java/com/example/virosample/ViroHelper.java

2)Set the object to a world position. You can set this to whatever you want like (0,0, -5).

3)Add the object to your scene.

4)Loads the model and on completion sets the texture for the model.

Make sure the png, obj and mtl are all under your assets directory.
