### ISSUE TITLE
Is this possible to detect vertical object such as wall?

### ISSUE THREAD

**Issue by mistrydarshan99** [viromedia/virocore#20]
Hello,

Is this possible to detecting vertical plane such as walls and put an object on it. Currently using this SDK we detect horizontal surface but what about the vertical surface?

**Comment by dam00n** [comment]
No, it is not possible to detect vertical planes with ARCore at this time. Here is a link to a github issue for ARCore requesting vertical plane support -> https://github.com/google-ar/arcore-android-sdk/issues/18

Vertical planes was added in ARKit 1.5 for iOS devices. This is currently in developer preview. We will have support for ARKit 1.5 soon.

**Comment by ryan-hodgman** [comment]
To reopen this question, vertical plane detection should now be possible with ARCore 1.2, which you've supported with the 1.7 release of ViroCore ([releases](https://virocore.viromedia.com/docs/releases)).

That said, I'm unclear on the implementation of this feature. The [ARPlaneAnchor.Alignment](https://developer.viromedia.com/virocore/reference/com/viro/core/ARPlaneAnchor.Alignment.html)  enum hasn't been updated with a `ARPlaneAnchor.Alignment.VERTICAL` value, and my testing has failed to detect any instances of `ARPlaneAnchor.Alignment.NON_HORIZONTAL`, so I'm missing something.

What do we need to do to detect vertical planes with ViroCore? Can we please get some documentation on the matter?

**Comment by radvani** [comment]
Hi @ryan-hodgman, one thing that's easy to miss is setting the anchor detection types. See the code snippet below. Apologies for the lack of documentation on this; we'll add further documentation now. 

```
EnumSet<ViroViewARCore.AnchorDetectionType> types = EnumSet.of(ViroViewARCore.AnchorDetectionType.PLANES_HORIZONTAL,
                ViroViewARCore.AnchorDetectionType.PLANES_VERTICAL);
        ((ViroViewARCore) mViroView).setAnchorDetectionTypes(types);

        arScene.setListener(new ARScene.Listener() {
            @Override
            public void onAnchorFound(final ARAnchor anchor, final ARNode node) {
                if (anchor.getType() == ARAnchor.Type.PLANE) {
                    ARPlaneAnchor planeAnchor = (ARPlaneAnchor) anchor;
                    if (planeAnchor.getAlignment() == ARPlaneAnchor.Alignment.NON_HORIZONTAL) {
                        // Vertical plane detected
                    }
            }

            @Override
            public void onAnchorUpdated(final ARAnchor anchor, final ARNode node) {
            }

            @Override
            public void onAnchorRemoved(final ARAnchor anchor, final ARNode node) {
            }

            @Override
            public void onAmbientLightUpdate(final float lightIntensity, Vector lightColor) {
            }

            @Override
            public void onTrackingUpdated(ARScene.TrackingState state, ARScene.TrackingStateReason reason) {
            }

           @Override
            public void onTrackingInitialized() {
            }
        });
```

**Comment by radvani** [comment]
Our underlying tracking engine for ViroCore is ARCore, so that's probably a good question for the Google guys over there. I'll venture a theory, though: vertical surfaces tend to have fewer other recognizable features on them than horizontal surface (e.g. there are more items standing on floors than there are hanging on walls), and the lack of such features impairs the ability to identify vertical planes.

**Comment by Anandhitwilight** [comment]
Please Give proper doucumentation for detecting Vertical plane such as wall, and Horizontal plane such as floor
