### ISSUE TITLE
Hi , I use 1.4.0 release of arcore  auto focusing is work properly using config.setFocusMode.But in ViroCore this method is now working ? Please suggest me class or method i need to call for auto focusing in viro core. Thanks

### ISSUE THREAD

**Issue by Attaullah123** [viromedia/virocore#200]
- [ ] Review the documentation: https://virocore.viromedia.com/
  - [ ] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [ ] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [ ] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
1. OS: Mac, Windows, Linux
2. Version: ViroCore version 
3. Device(s): What device(s) are you are seeing the issue on (i.e. Samsung Note 8, Pixel 2 XL, etc)

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

**Comment by manbod** [comment]
Hi @Attaullah123 ,
What version of `ViroCore` are you using? We integrated arcore 1.4.0 in `ViroCore v1.10.0`. You can toggle auto-focus on/off by using `setCameraAutoFocusEnabled(boolean)` method in `ViroViewARCore`. See reference docs for [setCameraAutoFocusEnabled(boolean)](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewARCore.html#setCameraAutoFocusEnabled(boolean)) and a helper [isCameraAutoFocusEnabled()](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewARCore.html#isCameraAutoFocusEnabled()).

If you haven't yet updated to latest ViroCore v1.10.0, find upgrade instructions here -> https://virocore.viromedia.com/docs/releases

Thanks,
