### ISSUE TITLE
VR in viro core

### ISSUE THREAD

**Issue by HLneoh** [viromedia/virocore#202]
Hi guys, how can I set a HelloWorld VR scene by using viro core instead of viro react?
Can I seek for advices?

**Comment by manbod** [comment]
Hi @HLneoh ,
Have you seen our Hello World projects from our Getting Started page here -> https://virocore.viromedia.com/docs/getting-started ? If you download the HelloWorld projects [here](https://s3-us-west-2.amazonaws.com/virocore/1_10_0/virocore-helloworld.zip), you'll see we have three samples - `virocore-helloworld-vr`, `virocore-helloworld-ar` & `virocore-helloworld-scene`. You can see how to set and use a VR scene in ViroActivityVR in there.

Thanks,

**Comment by HLneoh** [comment]
Hi @manbod, thanks for the comment.

How can I replace the "HELLO WORLD" text with an image (jpg/png)? 
So that when I click on the image, I can enter a new VR scene. Is it possible to make it?
