### ISSUE TITLE
record video question

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#203]
How do you record it with a framelayout for that page (no 3dnode is created, just a simple framelayout)?
for ViroMediaRecorder

**Comment by 544531645** [comment]
example 
![image](https://user-images.githubusercontent.com/15622364/45356677-830c3e00-b5f6-11e8-86b6-921f411eb685.png)
I want the icon also in record video

**Comment by manbod** [comment]
If you want the 2D icons to be recorded as well, you'll need to use Android's MediaRecorder https://developer.android.com/reference/android/media/MediaRecorder to record the screen. Some more examples here https://github.com/googlesamples/android-MediaRecorder and https://stackoverflow.com/questions/1817742/how-can-i-record-a-video-in-my-android-app. Our `ViroMediaRecorder` is useful only to record the app's AR feed (Viro elements)

Thanks

**Comment by 544531645** [comment]
I want Viro elements and 2d together record , the mediaRecorder need a sufaceview , but I use viroview , if it can record ?

**Comment by dthian** [comment]
No, as mentioned: 
> Our ViroMediaRecorder is useful only to record the app's AR feed (Viro elements)

At this stage, Viro does **not support** recording Android UI views (the framelayout with your 2D icons). You will need to refer to Android's APIs and documentation for recording the entire screen, as mentioned above. **Again, we do not support recording Android UI views.**
