### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#204]
if virocore support two 3d node Collision detection?

**Comment by dthian** [comment]
Hey @544531645, currently viro core supports collisions within the physics engine - either between two 3d bodies that are:
- static-dynamic 
- kinematic-dynamic 
- dynamic-dynamic bodies.

**Comment by 544531645** [comment]
Can you provide a simple example of two objects falling to the ground after a collision？

**Comment by dthian** [comment]
Hey @544531645, the physics example should provide all the required information you need:
https://github.com/viromedia/viro/blob/master/js/ARPhysicsSample/BasicPhysicsSample.js

**Comment by dthian** [comment]
Hey @544531645, 

When creating a new issue in the future, 

### **Please abide by the Viro Issue Checklist Requirements that is always shown to you directly in the Viro Issue template, _before opening a new issue_!!!** 

This helps save you time in resolving your issue (like in this situation), while giving us needed background information on what is wrong and what is missing. **In the future, we'll require this to be filled out before being able to diagnose your questions!**

_For your reference, here is an example of such a checklist shown below:_

  - [ ] Review the documentation: https://virocore.viromedia.com/
  - [ ] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [ ] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [ ] Turn off Instant Run in Android Studio

**With regards to your original query:**
The physics guide documents for the API in this area should be pretty straight forward (it basically explains how collision events work). **_From it, you should be able to recreate the example you mentioned above._** You can view the guide doc [here](https://virocore.viromedia.com/docs/physics#collision-events).

Here is an example:
```
mListener = new PhysicsBody.CollisionListener() {
            @Override
            public void onCollided(String tag, Vector position, Vector normal) {
                // Do stuff on collision
            }
};

physicsBody.setCollisionListener(mListener);
```

**Comment by dthian** [comment]
Hey @544531645, 

When creating a new issue in the future, **Please abide by the Viro Issue Checklist Requirements that is always shown to you directly in the Viro Issue template, _before opening a new issue_!!!** 

This helps save you time in resolving your issue (like in this situation), while giving us needed background information on what is wrong and what is missing. **In the future, we'll require this to be filled out before being able to diagnose your questions!**

_For your reference, here is an example format on how new issues are filed (you should already be able to see the template whenever you open a new issue):_
![screen shot 2018-09-13 at 2 47 11 pm](https://user-images.githubusercontent.com/1904934/45517725-faabab80-b763-11e8-8462-85d6ae2222cc.png)

**With regards to your original query:**
The physics guide documents for the API in this area should be pretty straight forward (it basically explains how collision events work). **_From it, you should be able to recreate the example you mentioned above._** You can view the guide doc [here](https://virocore.viromedia.com/docs/physics#collision-events).

Here is an example:
```
mListener = new PhysicsBody.CollisionListener() {
            @Override
            public void onCollided(String tag, Vector position, Vector normal) {
                // Do stuff on collision
            }
};

physicsBody.setCollisionListener(mListener);
```
