### ISSUE TITLE
[VR] Adjust text position

### ISSUE THREAD

**Issue by HLneoh** [viromedia/virocore#206]
Hi, I have tried the HelloWorldVR. 

At first, the position of the textNode is new Vector[0,0,-2]

However, after I changed the position into new Vector[0,0,2], I cannot see the "HELLO WORLD" text anymore. I expected the text will appear in the opposite position of the initial position. 

Is it due to vr in viro core only supports 3DOF? Or is there a way to position the text in a VR scene in viro core?

**Comment by dthian** [comment]
Hey @HLneoh, this is because the text that is now placed behind you (at 0,0,2), you are effectively looking at the back side of the text geometry, and as such that geometry is being culled. 

You can fix this by either billboarding the text to always face the user, or by setting disabling culling on the text's material.

**Comment by HLneoh** [comment]
Hi @dthian , Thanks for the comment. I have set to disable culling on text's materials as below: 

               _Text helloWorldText = new Text.TextBuilder().viroContext(mViroView.getViroContext()).
                textString("Hello").
                fontFamilyName("Roboto").fontSize(40).
                color(Color.WHITE).
                width(4).height(2).
                horizontalAlignment(Text.HorizontalAlignment.CENTER).
                verticalAlignment(Text.VerticalAlignment.CENTER).
                lineBreakMode(Text.LineBreakMode.NONE).
                clipMode(Text.ClipMode.CLIP_TO_BOUNDS).
                maxLines(1).build();

               Material material = new Material();
               material.setCullMode(CullMode.NONE);
               helloWorldText.setMaterials(Arrays.asList(material));_

However, the text become all white and cannot show the word "Hello" in VR scene as the picture below. 

![image](https://user-images.githubusercontent.com/25906607/45535670-de764000-b831-11e8-8403-6b1310df9b4a.png)

I want to place text not only the area face to the user, but also the other areas in the 360 degree photo (e.g right hand side, left hand side and opposite side of area face to the user). 

May I know what way can I use to achieve it?

**Comment by dthian** [comment]
Hi @HLneoh, have you tried the billboarding the text as mentioned above?

**Comment by HLneoh** [comment]
Hi @dthian , it works after billboarding the text. Thank you so much. :)
