### ISSUE TITLE
[VR] Place 2D image into VR scene

### ISSUE THREAD

**Issue by HLneoh** [viromedia/virocore#207]
Hi guys, I intend to place a 2D image as icon in my VR scene. Is it possible?
If yes, may I know how to achieve?

**Comment by dam00n** [comment]
Follow the github posting guidelines. First step -> Review the documentation: https://virocore.viromedia.com/

This is clearly covered in the documentation.

**Comment by HLneoh** [comment]
Hi, I have read the documentation. However, I am unable to find any suitable classes to use to load 2D image to my node. So I wonder is there a way to achieve it?
