### ISSUE TITLE
[VR] 2D image issue

### ISSUE THREAD

**Issue by HLneoh** [viromedia/virocore#208]
I have read viro core documentation as well as searched for the existing issue. However, I am not able to find a method to load a 2D image into my VR scene. As the information that I have read are all about 3D object. May I know is there a class that can be used to load a 2D image and set the image into a node?

I know bitmap can actually load a 2D image. However, I dont know how to place the bitmap image into the node created. Hope that someone can provide some hints for me.

**Comment by dthian** [comment]
Hey @HLneoh, a bitmap contains the 2D image **data** that can be loaded onto the diffuse component of a Material. You can then set this material on a quad surface in your scene (basically a 2d image). You can then position this quad any where in the scene in relation to the camera. 

It should go along something like this:
```
Bitmap bobaBitmap = this.getBitmapFromAssets(mActivity, "boba.png");
Texture bobaTexture = new Texture(bobaBitmap, Texture.Format.RGBA8, true, true);

Material material = new Material();
material.setDiffuseTexture(bobaTexture);

Quad surface = new Quad(1, 1);
surface.setMaterials(Arrays.asList(material));
Node node = new Node();
node.setGeometry(mSurface);
mScene.getRootNode().addChildNode(node);

```

**Comment by HLneoh** [comment]
Hi @dthian , thank you so much. It works.
