### ISSUE TITLE
Framework doesn't render simple texture described in mtl 

### ISSUE THREAD

**Issue by jacobwyn** [viromedia/virocore#21]
Hi guys.
I went through this https://github.com/viromedia/virocore/issues/2 and I didn't manage to render simple texture described in mtl ...

what I do:
```
 Object3D object3D = new Object3D();
        object3D.setPosition(new Vector(0, 0, -2));
        object3D.loadModel(getUri("model.obj"), Object3D.Type.OBJ, new AsyncObject3DListener() {
            @Override
            public void onObject3DLoaded(Object3D object3D, Object3D.Type type) {
                Log.e(LOG_TAG, "loaded success");
                mArScene.getRootNode().addChildNode(object3D);
            }

            @Override
            public void onObject3DFailed(String s) {
                Log.e(LOG_TAG, s);
            }
        });
```
what I got:
![result](https://user-images.githubusercontent.com/15327844/36301269-e50f1fce-130c-11e8-9462-e572396018a4.png)

what should be:
![desiredres](https://user-images.githubusercontent.com/15327844/36301275-e9ba1402-130c-11e8-9570-3a3a85769df0.png)

Assets link https://poly.google.com/view/5vbJ5vildOq

**Comment by dthian** [comment]
Hi @jacobwyn, have you read the 3DObject guide at https://virocore.viromedia.com/docs/3d-objects? The piano in the picture provided looks really dark, you may need to add a Light to your scene. Try adding an Ambient light to see if your model appears:

AmbientLight ambient = new AmbientLight(Color.WHITE, 1000.0f);
node.addLight(ambient);

**Comment by dthian** [comment]
Hey @jacobwyn, you might hit a crash with regards to https://github.com/viromedia/virocore/issues/22

We are currently aware of this, and are working actively on a fix.

**Comment by jacobwyn** [comment]
Hi @dthian thanks for the response, adding the AmbientLight really helped. Actually, the picture with black piano is made with OmniLight, without light it will be absolute transparent.
