### ISSUE TITLE
Physics

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#211]
- [x] Review the documentation: https://virocore.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [x] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [x] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
1. OS: Mac, Windows, Linux
2. Version: ViroCore version 
3. Device(s): What device(s) are you are seeing the issue on (i.e. Samsung Note 8, Pixel 2 XL, etc)

## Description
I added physics to 3dtext, but it went straight down out of sight, not to the ground。the screen black point , he down until can't see 

the code ；
  Text.TextBuilder textBuilder = Text.builder().fontSize(30).fontFamilies("Roboto, NotoSansCJK").height(0.1f).width(0.70f).fontStyle(Text.FontStyle.Italic).maxLines(3).textString("Hello").viroContext(mViroView.getViroContext()).           
 clipMode(Text.ClipMode.NONE).color(Color.parseColor("#43dffd")).horizontalAlignment(Text.HorizontalAlignment.LEFT).verticalAlignment(Text.VerticalAlignment.TOP);
        Text  helloWorldText = textBuilder.build();
        helloWorldText.setExtrusionDepth(5.0f);
        Node textNode = new Node();
        textNode.initPhysicsBody(PhysicsBody.RigidBodyType.DYNAMIC, 0.2f, new 
        PhysicsShapeAutoCompound());
        textNode.setGeometry(helloWorldText);
        mScene.getRootNode().addChildNode(textNode);
## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.
![229374224273431970](https://user-images.githubusercontent.com/15622364/45680428-7a26e980-bb6d-11e8-87a4-622d67b32502.jpg)

**Comment by 544531645** [comment]
Maybe it can't sense where the ground is?

**Comment by dam00n** [comment]
Correct, you will need to determine where the ground is and create a plane for it, in order for the physics to know when to interact.

**Comment by dthian** [comment]
Hey @544531645, you will also need to initPhysicsBody() for the ground as well with a RigidBodyType.STATIC, similar to the example shown [here](https://virocore.viromedia.com/docs/physics).

**Comment by 544531645** [comment]
yeah I add initPhysicsBody it work , But is there a way to create a plane that's large enough that it doesn't produce multiple planes, and then I have to collide anywhere around

**Comment by 544531645** [comment]
![image](https://user-images.githubusercontent.com/15622364/45749856-9a26dd80-bc3f-11e8-8838-77483f92bedc.png)
How is the effect achieved this ?
my code 
     Material snowMaterial = new Material();
                snowMaterial.setDiffuseColor(Color.YELLOW);
                Quad quad = new Quad(0.01f, 0.01f);
                quad.setMaterials(Arrays.asList(snowMaterial));

                ParticleEmitter emitter = new ParticleEmitter(mViroView.getViroContext(),quad);
                emitter.setExplosiveImpulse(1f,new Vector(position.x,position.y-0.4,position.z),0.5f);
                emitter.setDuration(1000);
                emitter.run();
                textNode.setParticleEmitter(emitter);

**Comment by 544531645** [comment]
I wanted to achieve a simple explosion effect

**Comment by 544531645** [comment]
> Hey @544531645, you will also need to initPhysicsBody() for the ground as well with a RigidBodyType.STATIC, similar to the example shown [here](https://virocore.viromedia.com/docs/physics).

this work ,thank you .

**Comment by dthian** [comment]
Hey @544531645, next time, please file a new github if you are asking about a **different** problem (like above, when you ask about particles, instead of physics).

With regards to your question, you can actually refer to the javascript particle template in React Viro [here](https://github.com/viromedia/viro/blob/master/js/ParticleEmitters/FireworkEmitter.js). The properties in Javascript should be transferable to ViroCore Java (they should relate to each other in terms of properties).

In the template link, you would see a property called particlePhysics, which translates to setExplosiveImpulse(...) in virocore, that effectively simulates a detonation effect.

**Comment by 544531645** [comment]
okay，next I will open new

**Comment by 544531645** [comment]
I use the setExplosiveImpulse .. the screen shot 
![image](https://user-images.githubusercontent.com/15622364/45793753-267be380-bcc6-11e8-8dcd-4c38f329e7c4.png)
It just looks like yellow point  this need more node or what ?

**Comment by 544531645** [comment]
??

**Comment by dthian** [comment]
As the ViroReact particle templates are effectively a copy of the ViroCore APIs, their configuration should also work in ViroCore. If the visual result in your app is not the same, it is most likely a bug in your application where the particles are misconfigured. Please debug your application to resolve the issue.

Also, please only file bugs *only if* you have identified an issue with the platform, and the specific API that is causing the bug, and have repro steps about that bug, and code samples demonstrating why you think it is a legitimate bug.

*Please do not file github issues asking for completed code specific to your app - we are currently not a dev workshop at this time.*

Thanks!
