### ISSUE TITLE
[AR] Extra Unneeded Permissions upon upload to Google Play

### ISSUE THREAD

**Issue by keithmaxx** [viromedia/virocore#214]
## Environment
Mac, Android Studio 3.1.3, ViroCore 1.6

## Description
After applying AR Core optional and not requiring related uses-features in the Android manifest, uploading to Google Play still shows NFC and RECORD_AUDIO as app permissions, as shown here:
<img width="730" alt="screen shot 2018-10-09 at 11 07 51 am" src="https://user-images.githubusercontent.com/5824501/46644616-a0abd380-cbb3-11e8-9713-3c0922c74b72.png">

The manifest file is as follows:
[AndroidManifest-redacted.txt](https://github.com/viromedia/virocore/files/2458689/AndroidManifest-redacted.txt)

**Comment by keithmaxx** [comment]
Thanks @dthian for entertaining my inquiry.

**Comment by VikAdvani** [comment]
Hi @keithmaxx,

You can override the manifest and remove permissions you don't need(provided you don't use Viro features that require them).

So for audio and nfc add the following to your manifest:
```
<uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"/>
<uses-permission android:name="android.permission.NFC" tools:node="remove"/>
```

**Comment by keithmaxx** [comment]
So if these uses-permissions are added, do we still need to add their corresponding uses-features as well? 

I refer to the following: 
android.hardware.sensor.accelerometer
android.hardware.sensor.gyroscope
android.hardware.microphone
