### ISSUE TITLE
PlatformUtil Memory Leak

### ISSUE THREAD

**Issue by ryan-hodgman** [viromedia/virocore#215]
## Environment
1. OS: Compiled on Mac
2. Version: 1.11
3. Device(s): Pixel 2, but assumedly all Android devices

## Description
We've recently recorded a number of crashes caused by `java.lang.OutOfMemoryError`s. We installed [LeakCanary](https://github.com/square/leakcanary) to hunt down the issue and started receiving leak reports related to an internal `PlatformUtil` class and the `mContext` that it holds. 

It would seem that when an instance of `ViroViewARCore` is disposed of it only nullifies its `PlatformUtil` instance, rather than explicitly disposing of it (ViroViewARCore:348). This becomes an issue because the `PlatformUtil` has a `Context` reference that is only nullified when the `PlatformUtil` instance is finalized (PlatformUtil:95), which does not necessarily align with when the `Activity` is destroyed. The result is that the `Activity` instance is leaked beyond its destruction.

Could we please explicitly tidy up this `PlatformUtil#mContext` reference upon activity destruction? It seems to be at least contributing to the OOM exceptions we've been experiencing.

**Comment by achuvm** [comment]
Hi @ryan-hodgman,

Thanks for the very detailed bug report, we'll fix this issue in our next release.

**Comment by ryan-hodgman** [comment]
Awesome, I look forward to it. Thanks for your responsiveness. 👍

**Comment by manbod** [comment]
Hi @ryan-hodgman ,
We just released ViroCore 1.12.0. We fixed a few memory leaks in this update. Docs here -> https://virocore.viromedia.com/v1.12.0/docs/releases . Let us know if you still see the same leaks.

**Comment by ryan-hodgman** [comment]
Awesome news, thanks! 👏
