### ISSUE TITLE
Crash: JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by ssaxena0891** [viromedia/virocore#22]
The app is getting crashed when the obj file is too large. Below is the stacktrace of the crash-

02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116] JNI ERROR (app bug): local reference table overflow (max=512)
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116] local reference table dump:
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]   Last 10 entries (of 512):
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       511: 0x12c9d6a0 java.lang.Class<com.viro.core.Texture$FilterMode>
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       510: 0x12c605b0 com.viro.core.Texture$WrapMode
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       509: 0x12c9d880 java.lang.Class<com.viro.core.Texture$WrapMode>
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       508: 0x12c605b0 com.viro.core.Texture$WrapMode
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       507: 0x12c9d880 java.lang.Class<com.viro.core.Texture$WrapMode>
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       506: 0x12c542b0 com.viro.core.Texture
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       505: 0x12ddb840 java.lang.Class<com.viro.core.Texture>
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       504: 0x12c60688 com.viro.core.Texture$FilterMode
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       503: 0x12c9d6a0 java.lang.Class<com.viro.core.Texture$FilterMode>
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       502: 0x12c60688 com.viro.core.Texture$FilterMode
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]   Summary:
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         6 of com.viro.core.Material$ShadowMode (1 unique instances)
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         6 of com.viro.core.Material$CullMode (1 unique instances)
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         6 of com.viro.core.Material$TransparencyMode (1 unique instances)
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         6 of com.viro.core.Material$BlendMode (1 unique instances)
02-16 21:53:34.799 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       105 of com.viro.core.Texture$FilterMode (1 unique instances)
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]        72 of com.viro.core.Texture$WrapMode (1 unique instances)
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         1 of com.viro.core.Object3D
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         6 of com.viro.core.Material (6 unique instances)
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]        36 of com.viro.core.Texture (36 unique instances)
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         6 of com.viro.core.Material$LightingModel (2 unique instances)
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]       252 of java.lang.Class (11 unique instances)
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         9 of java.lang.String (9 unique instances)
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116]         1 of java.lang.String[] (3 elements)
02-16 21:53:34.800 17211-17211/com.example.virosample.scene A/art: art/runtime/indirect_reference_table.cc:116] 
02-16 21:53:34.963 17211-17233/com.example.virosample.scene W/Viro: [1;33m[******************************** ABORT ********************************][0m
02-16 21:53:34.963 17211-17233/com.example.virosample.scene W/Viro: [1;33m        File: /Users/vadvani/ViroReact/ViroRenderer/ViroRenderer/VROMaterialSubstrateOpenGL.cpp[0m
02-16 21:53:34.963 17211-17233/com.example.virosample.scene W/Viro: [1;33m        Line: 81[0m
02-16 21:53:34.963 17211-17233/com.example.virosample.scene W/Viro: [1;33m    Function: virtual void VROMaterialSubstrateOpenGL::bindView(VROMatrix4f, VROMatrix4f, VROMatrix4f, VROMatrix4f, VROVector3f, VROEyeType)[0m
02-16 21:53:34.963 17211-17233/com.example.virosample.scene W/Viro: [0;33m      Reason: ASSERTION FAILED
                                                                      Expression: _activeBinding != nullptr[0m
02-16 21:53:34.964 17211-17233/com.example.virosample.scene A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x308d5118 in tid 17233 (GLThread 5688)
02-16 21:53:38.212 17211-17235/? W/AudioTrack: releaseBuffer() track 0xa6c3d000 disabled due to previous underrun, restarting

**Comment by radvani** [comment]
Thanks for the stack trace. Would you mind sending us the OBJ file you're
using so we can reproduce the crash? Also, can you verify that you're using
the latest ViroCore (version 1.3). Thanks!

Raj

**Comment by ssaxena0891** [comment]
Thanks for the quick response. Please find the obj and other files at https://drive.google.com/file/d/1G3KMqzWWqixgQoSOK7RQad3yFcR92SVj/view?usp=sharing

**Comment by radvani** [comment]
Thanks! We're able to reproduce this. Will keep you updated.

**Comment by ssaxena0891** [comment]
@radvani is there any update on this?

**Comment by radvani** [comment]
Hi @ssaxena0891, yes we've identified and fixed the problem. It had to do with loading OBJs with a large number of materials. The release is scheduled for this coming Monday, 2/26. Thanks!

**Comment by ssaxena0891** [comment]
Oh great, thanks!

**Comment by ssaxena0891** [comment]
thanks @dam00n, I have updated ViroCore to v1.4 and now its working fine.
