### ISSUE TITLE
[Feature Request] A way to drag an object along a single axis

### ISSUE THREAD

**Issue by toniuyt123** [viromedia/virocore#222]
[Feature Request] A way to drag an object along a single axis

Hi,

I'm trying to make an object be dragged only along one axis. I want it to be able to get translated using some transform manupulators (like arrows) pointing in each axis similar to any 3D editor. I'm trying to do this in normal ViroViewScene, no AR/VR. Any idea if this can be done using what we have currently (version 1.11.0)? Also on the topic of transform manipulators, is there a way to make them render on top the object. Right I'm just making them long enough to extend beyond the cube.

Screenshot from a 3D editor and my scene.

![screenshot_2](https://user-images.githubusercontent.com/22353291/48283270-b1769000-e464-11e8-8f61-cefe5c7e286e.jpg)

![45824999_260654464527215_6576162003298025472_n](https://user-images.githubusercontent.com/22353291/48283627-bd168680-e465-11e8-9a7c-120d13550ff5.png)

**Comment by toniuyt123** [comment]
Update: The thing I did was that I set the dragging type to FIXED_TO_PLANE. Then I change only the x,y or z coordinate of the parent cube depending on which arrow was dragged. After that I set the arrow position back to (0,0,0) so that is stays in the center of the cube. This mostly works but sometimes a weird bug happens. After i bring the arrow back to (0,0,0) it leaves an afterimage on the position where I really dragged it. The hitbox stays on the actual arrow which is on the cube. The afterimage stays there and moves along which the cube. Here's the code I use to set a dragListener to each handle and a gif of what's happening.

`handle.setDragType(Node.DragType.FIXED_TO_PLANE);
        handle.setDragPlanePoint(new Vector(0f, 0f, 0f));
        handle.setDragPlaneNormal(planeNormal);
        handle.setDragListener(new DragListener() {
            @Override
            public void onDrag(int i, Node node, Vector local, Vector world) {
                Vector oldPos = parent.getPositionRealtime();
                Vector newPos;
                if(lineToDrag.x == 1f) {
                    newPos = new Vector(world.x, oldPos.y, oldPos.z);
                } else if(lineToDrag.y == 1f) {
                    newPos = new Vector(oldPos.x, world.y, oldPos.z);
                } else {
                    newPos = new Vector(oldPos.x, oldPos.y, world.z);
                }
                parent.setPosition(newPos);

                node.setPosition(new Vector(0f, 0f, 0f));
            }
        });`

![demo-gir](https://user-images.githubusercontent.com/22353291/48371935-c3a33900-e6c5-11e8-8d38-eb519f113100.gif)

**Comment by dthian** [comment]
He @toniuyt123, thanks for reaching out!

Currently all dragging callbacks implement their own dragging behaviors (the renderer actually drags the object). It **may** be possible to overwrite the object's position in the onDrag callback as you have done above. 

That being said, the above situation is a bit strange, could you share with us the full code? (For example, We're not sure what the handle is etc).

**Comment by toniuyt123** [comment]
Indeed that was the problem. I decided to go with this solution. I added a clickListener to the Handled so they don't transfer the event to the cube and when we have a CLICK_UP I set the it's position back to 0. It still appears away form the origin when dragging sometimes but when I release it goes back and doesn't leave a copy. I guess setting the handle position to 0 in the onDrag() function isn't enough to make it appear like it doesn't move all the time. This will do for now, however, thanks for your help.

```
handle.setClickListener(new ClickListener() {
            @Override
            public void onClick(int i, Node node, Vector vector) {

            }

            @Override
            public void onClickState(int i, Node node, ClickState clickState, Vector vector) {
                if(clickState.equals(ClickState.CLICK_UP)) {
                    node.setPosition(new Vector(0f, 0f, 0f));
                }
            }
        });
```
