### ISSUE TITLE
Error inflating class com.viro.core.ViroViewARCore if the compileSdkVersion is updated to the latest 

### ISSUE THREAD

**Issue by AnilKrishna** [viromedia/virocore#231]
- [ ] Review the documentation: https://virocore.viromedia.com/
  - [ ] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [ ] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [ ] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
1. OS: Mac
2. Version: virocore_release_1.12.0
3. Device(s): One Plus 6

## Description
I am playing with ARPlacingObjects sample, If I change the compileSdkVersion to 28 the app keeps crashing with the exception : Error inflating class com.viro.core.ViroViewARCore. I have attached the detailed logcat dump to the issue.

However, the sample works absolutely fine if the compileSdkVersion is set to 27.

## Reproducible Demo
Change the compileSdkVersion to the latest which is 28 at the moment and try to run the app, the app crashes.

[Exception Logcat.docx](https://github.com/viromedia/virocore/files/2622637/Exception.Logcat.docx)

**Comment by VikAdvani** [comment]
Hi @AnilKrishna,
I've been unable to reproduce this. Does this occur on other devices or just the OnePlus 6?

**Comment by AnilKrishna** [comment]
Hi @VikAdvani 
Thanks for the reply. After seeing your comment, I tested the same on Google Pixel 2 device to check if its something device specific but the results are same.

These are the changes I have made to the Sample:
* Converted the Java class to equivalent Kotlin version.
* Updated both ViroCore and ARCore to their latest available versions respectively.
* Changed the compiledSdkVersion from 27 to 28. 

Again as I mentioned earlier it works perfectly fine if the compiledSdkVersion is kept to 27. Please let me know if this is helpful.

**Comment by VikAdvani** [comment]
Hi @AnilKrishna, thanks for reporting this. One question for you, is this blocking you are you able to continue work on 27 for now?

**Comment by VikAdvani** [comment]
Hi @AnilKrishna, 
We were able reproduce this and the issue is with our AWS dependencies throwing errors for compileSDKVersion 28. 
See related issue here:
https://github.com/aws-amplify/aws-sdk-android/issues/476

You can fix this by upgrading your AWS dependencies to 2.7.7 in your gradle file. That should fix the issue for you :)

**Comment by AnilKrishna** [comment]
Hi @VikAdvani,

Thanks for looking into this and posting the solution. It's working perfectly fine on the latest compileSDKVersion 28 after updating the AWS dependencies. Interestingly my Gradle build didn't complain of latest version availability earlier.    
I wasn't really blocked as I could build it on 27 to move further with the experiments. Thanks for asking though. I appreciate the responsiveness. Keep up the good work.
