### ISSUE TITLE
Node position based of another one's position

### ISSUE THREAD

**Issue by Ximmgon** [viromedia/virocore#232]
- [x] Review the documentation: https://virocore.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [x] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [x] Turn off Instant Run in Android Studio

## Environment

1. OS: Android 8.0, Windows
2. Version: ViroCore the latest
3. Device(s): Samsung 7 EDGE

## Description
Hi! I have two models and I want to position one based of the position of another.
The first node with the first model(A) is parent of node with the other model(B).
I change the position of node A when an anchor is found and the 2 nodes are visible, the node B is behind the node A, and I want to change it to in front of, but if I change the position of node B it starts to move with the camera and just that node, the node A it stays, and I dont want that. I don't know how to do that...

**Comment by Ximmgon** [comment]
Thank you, it works!  Not working because I was changing the position when an anchour was found, but if I adjust the position before, it works! :D

**Comment by manbod** [comment]
Glad it started working! :)
