### ISSUE TITLE
Cannot resolve method disposeAll()

### ISSUE THREAD

**Issue by toniuyt** [viromedia/virocore#234]
For some reason the disposeAll() method doesn't show up on any of my nodes. I want to be able get rid off some nodes entirely. I am using Windows 8.1, ViroCore 1.12.0. I looked through all the methods the intellisense gives in case it was renamed somehow but i can't seem to find a similar method.

**Comment by dthian** [comment]
Hey @toniuyt, the [disposeAll(boolean recurse)](disposeAll(boolean recursive)) api should exist.
You should also be able to double check by taking a peak into the virocore-release-v_1_12_0.aar file within your workspace to double check the signature - is it not there?

**Comment by toniuyt** [comment]
Weird, it is there. Don't know why it doesn't let me use it.
