### ISSUE TITLE
Question: Creating surface between virtual objects

### ISSUE THREAD

**Issue by iTruff** [viromedia/virocore#24]
I'm new in 3d development so sorry if I'll tell something stupid :)

The question is: Can i create surface between four (or if its possible more than 4) virtual objects (by getting their vectors). For example I will place 4 objects on floor, using `ViroViewARCore.performARHitTestWithRay()` after that i will have 4 vectors of these objects. Then I want to fill area between these objects (in our case it is square) with some texture. I think that I need to create a surface and then add texture to the surface, but maybe there is another way. 

Any comments will be helpful.
Thanks.

**Comment by jacobwyn** [comment]
When you have 4 points (vectors) on the same plane you can calculate a center of gravity of imaginary quadrangle, and put there com.viro.core.Surface with position in the  center of gravity like so:
    ```
VideoTexture mVideoTexture = new VideoTexture(mViroView.getViroContext(), getUri("big_buck_bunny.mp4"));
        Material material = new Material();
        material.setDiffuseTexture(mVideoTexture);

        Surface surface = new Surface(2, 1);
        surface.setMaterials(Arrays.asList(material));
        Node surfaceNode = new Node();
        surfaceNode.setPosition(new Vector(3, 1, -3)); //in meters
        surfaceNode.setGeometry(surface);

        // Attach boxNode to the mArScene's rootNode
        mArScene.getRootNode().addChildNode(surfaceNode);
        mVideoTexture.play();
```

**Comment by iTruff** [comment]
Thanks for your help. I am doing same with 4 points, but if I will have more than 4 points, for example 6 points polygon? Any ideas ?

**Comment by jacobwyn** [comment]
I would use  only the most distant from each other points to draw imaginary rectangle and perform above mentioned calculation... In this case whatever number of points you have there will be only one algorithm.

**Comment by dam00n** [comment]
Closing this issue do to inactivity. If you still have questions, please reopen and let us know.
