### ISSUE TITLE
[AR] Image Recognition

### ISSUE THREAD

**Issue by HLneoh** [viromedia/virocore#243]
## Environment
Please provide the following information about your environment:
1. OS:  Windows, Linux
2. Device(s): Samsung A5

## Description
I intend to apply image recognition to detect a building and display 2D text about the name of building. I implemented it by using the example of Black Panther as my base. However, my phone cannot detect the building and find the anchor. I guess because viro core only can recognize 2d image? If not, may I know how to make it possible detect 3d image such as a building image?

## Reproducible Demo
Below is the picture of the building that I want to detect.

![logo3](https://user-images.githubusercontent.com/25906607/50683588-83b95c00-104d-11e9-86c8-c859ae3180af.jpg)

**Comment by dam00n** [comment]
Correct, ARCore image recognition only support 2D images. Object detection is not support. One work around might be to use the signage on a building as the marker for tracking and positioning.
