### ISSUE TITLE
gltf animation

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#248]
- [x] Review the documentation: https://virocore.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [x] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [x] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
1. OS: andorid
2. Version: ViroCore 1.12.0
3. Device(s): pixel 

## Description
Load GLTF animation and fill the display, I through
    Set<String> animationKeys = object.getAnimationKeys();Get the animation Take 001,
but GetAnimation ("Take 001");
Animation. SetLoop (true);
Animation.  play ();
 This doesn't work. Why is that?

**Comment by dthian** [comment]
Hey @544531645, could you provide the gLTF asset, and as well as **full sample code** where you are playing the animation? (The above looks like it's not sample but Pseudo code). Thanks.

**Comment by 544531645** [comment]
[a1_out.zip](https://github.com/viromedia/virocore/files/2775181/a1_out.zip)

**Comment by 544531645** [comment]
type = Object3D.Type.GLTF;
 
object3D.loadModel(mViroView.getViroContext(), uri, type, new AsyncObject3DListener() {
            @Override
            public void onObject3DLoaded(final Object3D object, final Object3D.Type type) {
                load_ok = true;
                if (object.getAnimationKeys().size()!=0) {
                animation = object.getAnimation("Take 001");
                animation.setLoop(true);
                animation.play();
                }
}

**Comment by 544531645** [comment]
[panda.zip](https://github.com/viromedia/virocore/files/2775183/panda.zip)

**Comment by 544531645** [comment]
two model both

**Comment by 544531645** [comment]
@dthian

**Comment by dthian** [comment]
Hey @544531645, the panda model seems to be invalid - could you recheck your model against http://github.khronos.org/glTF-Validator/. 

Also, I've verified that the a1_out model's animation does not play. I'll file a bug on our back log to capture this. This github issue will be updated as soon as we have determined a fix. Thanks!

**Comment by 544531645** [comment]
@dthian okay ,thankyou ,Will the issue be released after the fix?

**Comment by 544531645** [comment]
@dthian the new version if fixed animation question ?

**Comment by dthian** [comment]
Hey @544531645, apologies for the delay, the Panda model should render with animation in the next update.

**Comment by dthian** [comment]
Closing as this should be fixed in the latest release.
