### ISSUE TITLE
Hit test bug in v1.3

### ISSUE THREAD

**Issue by iTruff** [viromedia/virocore#25]
After migrating to version v1.3 I noticed that `ViroViewARCore.performARHitTestWithRay()` stopped working as before. Now vector position from `ARHitTestResult` is not camera center position. Reproduced in sample app `ViroARObjectPlacementActivity`.

v1.2
![image](https://user-images.githubusercontent.com/6223322/36378496-ad75d00c-1583-11e8-81ab-4e4cb9c93876.png)

v1.3
![image](https://user-images.githubusercontent.com/6223322/36378491-a931d3ec-1583-11e8-96f2-3d72c9e7ddcc.png)

**Comment by dthian** [comment]
Thanks @iTruff! I've managed to reproduce the issue and we have filed a bug to work on the fix. This issue will be updated as soon as the patch has been pushed to release. Thanks!

**Comment by iTruff** [comment]
Thanks, will wait 👍

**Comment by dam00n** [comment]
Hi @iTruff this has been fixed in the latest ViroCore Update, v1.4. Let us know if you have any issues. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases
