### ISSUE TITLE
ClickListener not been triggered on billboarded node

### ISSUE THREAD

**Issue by gmartinsvrf** [viromedia/virocore#252]
## Environment
Please provide the following information about your environment:
1. OS: Mac - Mojave 1.14.3
2. Version: ViroCore 1.13.0
3. Device(s): Samsung S8

## Description
I've been creating a virtual reality solar system tour using ViroCore as an experimental project. I'm using a 360 image of the universe as a background and bitmaps(planets) as node textures.

Now, the goal is to make the planets face the camera at all times. I set **transformBehaviors** to **BILLBOARD_Y**, however, given that the camera faces **(0, 0, -1)** and there are 2 planets(nodes) on the sides positioned at **(-3, 0, 0)** and **(3, 0, 0)**, it seems as if only the image is being rotated but not the actual node so **onClick** gets really hard be triggered due to the rotation of the node. Occasionally, I manage to "hit" the node but maybe 1 out of 7 attempts.

The other 3 planets/nodes that are located in front(2) and behind(1) the camera work just well. Their location are **(0, 0, 3)**, **(1, 0, -3)** and **(0, 0, -4)**.

I think the real question here is, is there any convenient way to rotate the nodes facing the camera(or any location) dynamically without involving a lot of math or complexity? It'd be nice if, say, BILLBOARD transformation also rotated the node instead of swivelling the bitmap only so clicks would be possible and more accurate regardless of node positioning.

Please, see the code snippet below:

    private fun loadPlanets(){

        var planetPosition = 0
        while (planetPosition <= 4){
            // get basic android layout
            val earthBitmap = getLayout(planetPosition)

            var planetNodePosition: Vector? = null
            var planetScale: Vector? = null
            when(planetPosition){
                0 -> {
                    planetNodePosition = Vector(0f, 0f, 3f)
                    planetScale = Vector(2f, 2f, 2f)
                }
                1 -> {
                    planetNodePosition = Vector(1f, 0f, -3f)
                    planetScale = Vector(2f, 2f, 2f)
                }
                2 -> {
                    planetNodePosition = Vector(0f, 0f, -4f)
                    planetScale = Vector(2f, 2f, 2f)
                }
                3 -> {
                    planetNodePosition = Vector(3f, 0f, 0f)
                    planetScale = Vector(2f, 2f, 2f)
                }
                4 -> {
                    planetNodePosition = Vector(-3f, 0f, 0f)
                    planetScale = Vector(2f, 2f, 2f)
                }
            }
            setupPlanetTexture(earthBitmap, planetPosition, planetNodePosition!!, planetScale!!)
            planetPosition++
        }

    }
    
    private fun setupPlanetTexture(bitmap: Bitmap, planetPosition: Int, planetNodePosition: Vector, planetScale: Vector){
        val texture = Texture(bitmap, Texture.Format.RGBA8, true, true)

        // Set the Texture to be used on our surface in 3D.
        val material = Material()
        material.diffuseTexture = texture

        val surface = Quad(1f, 1f)
        surface.materials = Arrays.asList(material)

        setupPlanetNode(surface, planetPosition, planetNodePosition, planetScale)

    }

    private fun setupPlanetNode(surface: Quad, planetPosition: Int, planetNodePosition: Vector, planetScale: Vector){
        planetNode = Node()
        planetNode!!.setPosition(planetNodePosition)
        planetNode!!.setScale(planetScale)
        planetNode!!.geometry = surface

        //set name for planet node
        planetNode!!.name = planetNames[planetPosition]

        //rotate planet facing the camera
        planetNode!!.transformBehaviors = EnumSet.of(Node.TransformBehavior.BILLBOARD_Y)
        Log.d("###", "rotation: ${planetNode!!.rotationEulerRealtime} | planetNodePosition: $planetNodePosition | position RT: ${planetNode!!.positionRealtime} | name: ${planetNode!!.name}")

        //set click listener
        planetNode!!.clickListener = NodeOnClickListener()

        //add node to scene
        scene!!.rootNode.addChildNode(planetNode)
    }

Any help is very much appreciated.

Cheers

**Comment by manbod** [comment]
Hi @gmartinsvrf ,
This might be related to a billboarding issue we already know and have been looking to fix in an upcoming release. There is currently an issue where, with billboarding, the bounding box (for click / drag / touch events) around some nodes get squished/rotated and as a result clickListeners are hard to trigger. 

While we take a look at the issue on our end, in the meantime, a potential workaround would be to make the node for each planet a composite node -> each node has a bitmap and a box as children. Apply transparent material to the box. Set the bitmap to be billboarding as you currently do, but set the  clicklistener on the box, not on the bitmap or the parent node. That way users could click on the transparent box when trying to click the bitmap. Use [setIgnoreEventHandling(boolean)](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html#setIgnoreEventHandling(boolean)) set to `true` for the bitmap. You may need to play around with [renderingOrder](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html#setRenderingOrder(int)) in case the box ends up occluding the bitmap.

Another workaround that may be easier and worth trying (although unsure if it would work for your case) is highlighted in this [issue#190](https://github.com/viromedia/virocore/issues/190).

We understand this isn't ideal. But hope one of these two workarounds work for you while we look at solving this issue internally.

Thanks

**Comment by gmartinsvrf** [comment]
@manbod Ooooooo right. I'm kinda glad to hear it's a known issue though haha. Thanks for getting back to me in a decent time frame.

The workaround you mentioned sound reasonable, however, it's not applicable to me as the planets should face the camera so I'd have to mathematically figure out how to make the rotation of each node according the position of the camera.

Thanks again. 

Great stuff! You guys rock!

**Comment by dthian** [comment]
Hey @gmartinsvrf, you should still be able to have the planets face you through billboarding (without having to figure that out mathematically, while applying the above mitigation solution as well. For example, it could be of the following:

<ViroNode container (you can set scale / position here) >
<ViroNode containing image that is billboarded> 
<ViroNode containing transparent box to capture events>
<ViroNode>

That should ideally work. Perhaps i'm missing something?

**Comment by manbod** [comment]
@gmartinsvrf If I am understanding your case correctly, you shouldn't need to mathematically rotate each node to face the camera. For every planet, you'll have one parent node (not billboarded), with two child nodes -> one for the bitmap (billboarded), another for the transparent box (not billboarded). With this setup, the bitmap should still end up facing the camera / user.

**Comment by gmartinsvrf** [comment]
@dthian @manbod humm, yea that does make sense but, shouldn't I have to rotate the transparent box to be able to click on it anyways? Since it's a child of the node that's not rotated facing the camera? Unless you are talking about a 3D box, a squared 2D image would be facing the same direction that the node is, no?

**Comment by manbod** [comment]
Ah, yes we meant a 3D box :)

**Comment by gmartinsvrf** [comment]
RIGHT! That did the trick for clicks, however, like you mentioned, I'm having some issues with rendering I think. The box shows up within the planets :(


![screenshot_20190212-155540_test](https://user-images.githubusercontent.com/46906652/52676718-ebca5000-2edf-11e9-83ec-b1c52d2210f8.jpg)

**Comment by gmartinsvrf** [comment]
ok, got it to work now. The problem was that the position of the box nodes were set to the same as the planet nodes. Now I set the boxes to be **0.05** in front of the planet nodes and it seems to be working as expected. 

Thanks a lot guys. I really appreciate your help!

**Comment by dthian** [comment]
Glad to hear it work @gmartinsvrf, for future reference, you may be able to use the renderingOrder property in a ViroNode to ensure that the planet is always rendered after the box and thus will remain visible:
```
renderingOrder

This determines the order in which this Node is rendered relative to other Nodes. Nodes with greater rendering orders are rendered last. The default rendering order is zero. For example, setting a Node's rendering order to -1 will cause the Node to be rendered before all Nodes with rendering orders greater than or equal to 0.
```
