### ISSUE TITLE
ParticleEmitter.EmissionBurst Fireworks effect for help

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#255]
- [x] Review the documentation: https://virocore.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [x] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [x] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
1. OS: Mac, Windows, Linux
2. Version: ViroCore version 
3. Device(s): What device(s) are you are seeing the issue on (i.e. Samsung Note 8, Pixel 2 XL, etc)

## Description
I want to give 3d fireworks explosion effect how to do ah, can help you. Demo is preferred

**Comment by 544531645** [comment]
@dthian

**Comment by dthian** [comment]
Hey @544531645, you can follow how fireworks emitters are done here: https://github.com/viromedia/viro/tree/master/js/ParticleEmitters
