### ISSUE TITLE
Importing models doesn't work with Uris not in asset folder

### ISSUE THREAD

**Issue by gallegos3** [viromedia/virocore#260]
- [x ] Review the documentation: https://virocore.viromedia.com/
  - [x ] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [x ] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [ x] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
1. OS: Windows 8.1
2. Version: ViroCore 1.13
3. Device(s): Huawei p10 lite

## Description
I am trying to load models with files not in assets folder. Problem seems similar to [#244](https://github.com/viromedia/virocore/issues/244) but the proposed solution doesn't work for me. It says that I should use Uris with a 'file://' notation. I tried both file and content. 
```
    public void chooseFile() {
        Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
        intent.setType("*/*");
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        try {
            startActivityForResult(
                    Intent.createChooser(intent, "Select a File to Upload"),
                    1);

        } catch (android.content.ActivityNotFoundException ex) {
            Toast.makeText(ViroActivity.getView().getContext(), "Please install a File Manager.",
                    Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        final Uri uri = data.getData();
        
        Object3D model = new Object3D();
        File modelFile = new File("/storage/emulated/0/models/monkeyobj.obj");
        Uri fileUri = Uri.fromFile(modelFile);
        Log.i("modelLoading", fileUri.toString());
        Log.i("modelLoading", uri.toString());

        //fails with both uri and fileUri
        model.loadModel(ViroActivity.getView().getViroContext(), uri, Object3D.Type.OBJ, new AsyncObject3DListener() {
            public void onObject3DFailed(String error) {
                Log.w("modelLoading", "Failed to load the model");
            }
            public void onObject3DLoaded(Object3D object, Object3D.Type type){

            }
        });
```

The code above shows an Intent that lets me choose a file. After that I get the uri from data. fileUri is the one i manually construct with the path of a file. If I select the same file from the Intent I get these logs.
```
I/modelLoading: file:///storage/emulated/0/models/monkeyobj.obj
I/modelLoading: content://media/external/file/59863
W/Viro: No file found at URL [file:///storage/emulated/0/models/monkeyobj.obj], not copying to temporary file
W/modelLoading: Failed to load the model/external/file/59863
```

**Comment by dam00n** [comment]
Do you have an extra / in your file path?

**Comment by toniuyt123** [comment]
You are talking about fileUri.toString() I suppose. I have an extra one yes. You can see it on the second snippet.
`file:///storage/emulated/0/models/monkeyobj.obj`

**Comment by dthian** [comment]
Hey @toniuyt123, the above sounds more like an issue with saving / loading from the Android file system. Can you confirm that the created file **actually exists** at the uri location above, and that you have **read/write** access to it?

Instead of doing the above hack, **I strongly recommend** adhering to Android's [recommendations of file access and storage](https://developer.android.com/training/data-storage/files). Do let us know if you are experiencing any issues even after then.

**Comment by toniuyt123** [comment]
Sorry, but I am a little confused on how to use the link you provided. It shows how to save/open/delete files within the internal directory for my app or external directories. What I want is to be able to select any file and get it's Uri in such a way that I can use it in the loadModel function. So far I've been using the method provided [here](https://developer.android.com/guide/topics/providers/document-provider), also part of Android's dev guide. 
Also I've confirmed that the file exists and I can read it using the Uri i get from Intent data.
As a side not, I tried changing the Intent from GET_CONTENT to OPEN_DOCUMENT but it didn't work. And it shouldn't be a problem with the model itself as  I've tried with ones I can load from assets.

**Comment by dthian** [comment]
> Also I've confirmed that the file exists and I can read it using the Uri i get from Intent data
It looks like the uri returned from the intent is a "content type" - content://media/external/file/59863.

Thus, content uri **doesn't necessarily represent the absolute file path of your 3d object on the device**, and instead is handled by the content provided / resolver that you have used to persist the data. 

As such, you'll need to resolve the data through [content resolvers](https://developer.android.com/reference/android/content/ContentResolver) to a known local file location on the device. Looking at the link you've provided, you will have to probably see what resolvers Android's Storage Access Framework uses apply that here.

At the end of the day, the above doesn't sound like a Viro issue, but an Android issue with your application. **Viro essentially needs a full uri / file path to the local file on your device**, and it should work.

**Comment by toniuyt123** [comment]
It turned out to be a problem with the permissions. I thought that everything is fine with them as I had declared them in the manifest file. What I did was enable storage access permissions from the app manager in settings and it worked with a "file:///" type uri.
