### ISSUE TITLE
object persistency in AR

### ISSUE THREAD

**Issue by souravmind** [viromedia/virocore#28]
I want to create an application that store the position,rotation and scale of multiple object and when i close application and reopen than all the stored object must be at there respective position.

I am able to place object with the stored position but issue is that i can't place than at correct position as earlier.
the object are overlapping with each other. 

Do you have any solution around that.I am looking for android app side.

**Comment by dam00n** [comment]
We currently don't have a solution for this. This is a new area of AR that people are trying to solve, some are calling it AR Cloud -> https://medium.com/super-ventures-blog/arkit-and-arcore-will-not-usher-massive-adoption-of-mobile-ar-da3d87f7e5ad

Here are some companies that are working on solutions for persistent AR/AR Cloud. We have not tried them ourselves but they might be what you are looking for:

Sturfee -> https://sturfee.com/
6D.ai -> https://twitter.com/6d_ai
