### ISSUE TITLE
Remove Transform Behaviors from Node

### ISSUE THREAD

**Issue by YudizMohitS** [viromedia/virocore#287]
As per in this issue [https://github.com/viromedia/virocore/issues/122#issuecomment-392103964](url) **@dthian** comment that we can remove any set transform behaviors on an object, you can simply set an empty set.

So how is this possible? If anyone having any idea regarding this plz help me.

I am using transform behaviors like this

`portalScene.transformBehaviors = EnumSet.of(Node.TransformBehavior.BILLBOARD_Y)`

for some reason, I want to **remove** that so is it possible?

Thanks

**Comment by dthian** [comment]
@YudizMohitS you can remove behaviors like in the following:
         gltfModelBase64.setTransformBehaviors(EnumSet.noneOf(Node.TransformBehavior.class));

**Comment by YudizMohitS** [comment]
Thanks @dthian
