### ISSUE TITLE
GPU memory issue ?

### ISSUE THREAD

**Issue by dbathily** [viromedia/virocore#289]
- [X] Review the documentation: https://virocore.viromedia.com/
  - [X] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [X] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [X] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
1. OS: Mac, Windows
2. Version: 1.14.0
3. Device(s): One+ 6, Galaxy S9

## Description

This GLTF model causes a GPU memory issue while working easily on babylonjs and iOS.

[https://www.dropbox.com/s/fbknfg1j2i1kyy2/test-texture-v2.glb?dl=1](https://www.dropbox.com/s/fbknfg1j2i1kyy2/test-texture-v2.glb?dl=1)

Is it a bug or this kind of model is too "heavy" for viro?

**Comment by radvani** [comment]
Thanks for pointing this out; we've identified that this is indeed a bug and are working on a fix.

**Comment by radvani** [comment]
We've fixed this issue for our next release, and I confirm this model loads correctly now (see attached). Thanks.

![IMG_5035](https://user-images.githubusercontent.com/14915051/60627814-29068000-9da4-11e9-92d5-238796c47480.PNG)

**Comment by dam00n** [comment]
This issue has been fixed in the latest release, ViroCore 1.15

Release notes -> https://virocore.viromedia.com/docs/releases
