### ISSUE TITLE
It is possible to combine the library with location services ?

### ISSUE THREAD

**Issue by aplachykau** [viromedia/virocore#29]
Hello. I am wondering is there any options for combining the library and static gps coordinates. I need to spawn objects in real world coordinates. I found many examples on Unity. but for android I can't find some useful information. Virocore has good API but I can't find any options too

**Comment by dam00n** [comment]
Hi @aplachykau, take a look at this answer by Raj Advani on stackoverflow regarding this question. This should help you get started with Viro and GPS -> https://stackoverflow.com/questions/47419496/augmented-reality-with-react-native-points-of-interest-over-the-camera/47463980#47463980
