### ISSUE TITLE
#608 SIGBUS/SIGSEGV crash in libsceneform_animation.so when loading models

### ISSUE THREAD

**Issue by suryanadiminti99** [viromedia/virocore#291]
I am using Sceneform 1.8.0 and OPENGL 3.2 . I have faced same issue . i am adding .sfb format animated models in my scene . It crashes sometimes . Not all the time .

Sceneform randomly crashes with SIGBUS or SIGSEGV when loading certain models, for example the fox model from the augmentedface example.

ModelRenderable.builder()
.setSource(this, Uri.parse("helicopter.sfb")).setRegistryId("helicopter.sfb").build()
.thenAccept(renderable -> {andyRenderable = renderable;})
.exceptionally(
throwable -> {
Toast toast =
Toast.makeText(this, "Unable to load andy renderable", Toast.LENGTH_LONG);
toast.setGravity(Gravity.CENTER, 0, 0);
toast.show();
return null;
});

**Comment by dthian** [comment]
Please file this issue instead with [SceneForm](https://github.com/google-ar/sceneform-android-sdk), thanks!
