### ISSUE TITLE
Add support for Autofocus once ARCore enables it

### ISSUE THREAD

**Issue by trikko** [viromedia/virocore#32]
Virocore seems to miss autofocus on camera. Focus is fixed. Can I set autofocus just like on android camera app?

**Comment by radvani** [comment]
Hi @trikko, this is currently a limitation of ARCore, which does not yet support any API for autofocus. As soon as this support is added to ARCore we will enable it on Viro.

**Comment by dam00n** [comment]
Github Issue on ARCore where this feature request is being tracked -> https://github.com/google-ar/arcore-android-sdk/issues/153

**Comment by inio** [comment]
Good news!  ARCore 1.4 supports auto-focus.

**Comment by jeveloper** [comment]
From what i understand, ARKit also supports autofocus and custom focus , version 1.5+ 

Curious when arcore1.4 will be baked into virocore :)) it's currently at 1.2

**Comment by dam00n** [comment]
ViroCore 1.9 supports ARCore 1.3

We are currently working on integrating ARCore 1.4 and will have it available in our next release which is tentatively scheduled for availability at the end of August.

**Comment by jeveloper** [comment]
Hopefully you'll get RN 57 supported (yes master branch is totally fine on mac/linux and a small issue for windows as usual) @dam00n  thanks Danny

**Comment by dam00n** [comment]
ViroCore 1.10 now supports ARCore 1.4 which includes autofocus. Release notes and upgrade instructions located here -> https://virocore.viromedia.com/docs/releases
