### ISSUE TITLE
PBR dosen't work properly

### ISSUE THREAD

**Issue by jungmal** [viromedia/virocore#33]
I used PBR on viro 1.03
but I think it dosn't work properly on 1.04 even sample code at https://virocore.viromedia.com/v1.4.0/docs/physically-based-rendering

Am I wrong? or 1.04 has some bug?

**Comment by radvani** [comment]
Hi @jungmal, we just re-tested and found the example is working on our devices. Could you show us the code you're using. Also, I've added a link to the HDR image used in the example. This image must be placed in your app's assets folder for it to load properly. You can find the image [here](http://dq0qxqxzgyp27.cloudfront.net/virocore/readme_example_assets/portal_example_assets.zip).

**Comment by jungmal** [comment]
I used same code and HDR file, but rendered objects are different.
![pbr_err](https://user-images.githubusercontent.com/36752883/36880785-daf2b4fe-1e0d-11e8-8d2b-8a00462dbc55.png)

This is ViroARHelloWorldActivity.java code of each projects.
[pbr_err.zip](https://github.com/viromedia/virocore/files/1773502/pbr_err.zip)

`
public void onRendererStart() {
        // Create the 3d ar scene, and display the point clouds.
        mScene = new ARScene();
        mScene.displayPointCloud(true);

        // Create an TrackedPlanesController to visually display tracked planes
        TrackedPlanesController controller = new TrackedPlanesController(this, mViroView);

        // Spawn a 3D Droid on the position where the user has clicked on a tracked plane.
        controller.addOnPlaneClickListener(new ClickListener() {
            @Override
            public void onClick(int i, Node node, Vector clickPosition) {
                createDroidAtPosition(clickPosition);
            }

            @Override
            public void onClickState(int i, Node node, ClickState clickState, Vector vector) {
                //No-op
            }
        });

        mScene.setListener(controller);
        mViroView.setScene(mScene);

        Node rootNode = mScene.getRootNode();

        List<Vector> lightPositions = new ArrayList<Vector>();
        lightPositions.add(new Vector(-10,  10, 1));
        lightPositions.add(new Vector(10,  10, 1));
        lightPositions.add(new Vector(-10, -10, 1));
        lightPositions.add(new Vector( 10, -10, 1));

        float intensity = 300;
        List<Integer> lightColors = new ArrayList<Integer>();
        lightColors.add(Color.WHITE);
        lightColors.add(Color.WHITE);
        lightColors.add(Color.WHITE);
        lightColors.add(Color.WHITE);

        for (int i = 0; i < lightPositions.size(); i++) {
            OmniLight light = new OmniLight();
            light.setColor(lightColors.get(i));
            light.setPosition(lightPositions.get(i));
            light.setAttenuationStartDistance(20);
            light.setAttenuationEndDistance(30);
            light.setIntensity(intensity);
            rootNode.addLight(light);
        }

        Texture environment = Texture.loadRadianceHDRTexture(Uri.parse("file:///android_asset/environment.hdr"));
        mScene.setLightingEnvironment(environment);
    }
`

`
private void createDroidAtPosition(Vector position){
        // Create a droid on the surface
        final Bitmap bot = ViroHelper.getBitmapFromAsset(this, "andy.png");
        final Object3D object3D = new Object3D();
        object3D.setPosition(position);
        mScene.getRootNode().addChildNode(object3D);

        // Load the Android model asynchronously.
        object3D.loadModel(Uri.parse("file:///android_asset/andy.obj"), Object3D.Type.OBJ, new AsyncObject3DListener() {
            @Override
            public void onObject3DLoaded(final Object3D object, final Object3D.Type type) {
                // When the model is loaded, set the texture associated with this OBJ.
                Texture objectTexture = new Texture(bot, Texture.Format.RGBA8, false, false);
                Material material = new Material();
                material.setDiffuseTexture(objectTexture);
                material.setRoughness(0.23f);
                material.setMetalness(0.7f);
                material.setLightingModel(Material.LightingModel.PHYSICALLY_BASED);
                object3D.getGeometry().setMaterials(Arrays.asList(material));
            }

            @Override
            public void onObject3DFailed(String s) {
            }
        });

        // Make the object draggable.
        object3D.setDragListener(new DragListener() {
            @Override
            public void onDrag(int i, Node node, Vector vector, Vector vector1) {
                // No-op.
            }
        });
        object3D.setDragType(Node.DragType.FIXED_DISTANCE);
    }
`

**Comment by radvani** [comment]
Hi @jungmal, I recreated your scene and the results look correct, they resemble your "1.3" screenshot with PBR rendering working. I added PBR to the Hello World AR sample directly, so you can try it out yourself if you pull the latest AR [code samples](https://github.com/viromedia/virocore). 

If your results still resemble the non-PBR version, then it may be an issue with the way our PBR renderer is working with your device and GPU. In that case, can you send us the name of the device you're using (e.g. Galaxy 8, Pixel 1), etc, and the version of the Android OS installed? Additionally, can you send us the GPU type? Viro reports the GPU type in the logs, a line like the following will be printed when you create a ViroARCoreView:
```
GPU vendor [XYZ], renderer [XYZ]
```
Thanks!

**Comment by jungmal** [comment]
Hi **@radvani**. Unfortunately, PBR still dosen't work.
I'm using Galaxy S8(SM-G950N) and Android OS version is 7.0.
GPU type in the log is
> 03-06 15:48:41.777 11072-11089/com.example.virosample I/Viro: GPU vendor [ARM], renderer [Mali-G71]

**Comment by radvani** [comment]
Hi @jungmal, we've identified the issue and this will be fixed with a forthcoming minor update.

**Comment by dam00n** [comment]
@jungmal this issue has been fixed in ViroCore 1.4.1, you can find release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases#virocore-v141
