### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by sebztas** [viromedia/virocore#4]
Do you have any plans to support GIFs?

**Comment by dam00n** [comment]
Gif support is on our backlog but we do not yet have a timeframe for when it will be available. Will update this issue once we can provide better dates. Is your interest mainly in animated Gifs? - Danny

**Comment by sebztas** [comment]
Yes, I am interested mainly in animated Gifs and more precisely I would like to place as many different gifs as possible in the scene and measure the performance.

**Comment by dthian** [comment]
GIFs are now supported in the latest version of ViroCore > 1.10. 
As such, resolving issue.
