### ISSUE TITLE
I am calculating X,Y,Z by using Latitude and Longitude

### ISSUE THREAD

**Issue by deshmukhrohit11** [viromedia/virocore#41]
Hi, I am calculating [X, Y, Z]by using Latitude and Longitude. I want to place text node in that position now. But when I place the object in those positions, I am not able to view the text node. 

Should I need to reset my current position using the same method used for objects? How to reset current position of the camera to specific XYZ position?

Link used to calculate XYZ by lat and long: https://github.com/mattholl/geo-to-cartesian/blob/master/index.js

Note: I convert link code into Java.

**Comment by VikAdvani** [comment]
Hi @deshmukhrohit11, 
It seems like the link you provided translates lat/long into 2d projected coordinates. Do you know if those coordinates are in meters? If so, you'll need to take those coordinates and translate them again into AR space to properly have it display.

To do this you you'll need to do the same transformation of the devices location and it's lat/long
Then you'll subtract the position of your object in cartesian coords from the the device cartesian position to get the location in AR space in meters. 

So the math would like something below.
```
// translate object card to xy 
var objPos = geoToCartesian.fromLatLngToPoint({lat: -27.470127, lng: 153.0147027});
 
// translate current device position to a lat/lng 
var currentDevicePos = geoToCartesian.fromLatLngPoint({lat:currentDeviceLat, lng:currentDeviceLong});

var objFinalPosX = objPos.x - currentDevicePos.x;
var objFinalPosY = objPos.y - currentDevicePos.y;

// now you'll have to calibrate around the the initial compass of the device and rotate the obj final pos to appropriately account for that. 
```
Let me know if this helps or you need more info. Thanks!

**Comment by deshmukhrohit11** [comment]
@VikAdvani : Thank you for your help. 

Can you please tell me how change camera position to some specific location? When I change the position of the object. I am not able to see the object.

**Comment by hhong0326** [comment]
Hello @deshmukhrohit11 
How do you convert @VikAdvani 's suggestion? 
Could you show me?

**Comment by ManigandanRaamanathan** [comment]
@VikAdvani @deshmukhrohit11  can you explain about the device compass degree? How do I get it? what library do I use to get it?

**Comment by ManigandanRaamanathan** [comment]
Fixed my issue, I used magneto meter and wrong my custom logic to get the compass heading degree.

**Comment by jjfster** [comment]
> Fixed my issue, I used magneto meter and wrong my custom logic to get the compass heading degree.

I have a heck of a time getting good compass results in Android.  Can you tell me what you used to get a good result?  I've tried rotation_vector, magneto, etc.

Also, can you tell me how you translated the compass heading degree to fix the position properly for objects, camera, etc?
