### ISSUE TITLE
when happend SURFACE_NOT_FOUND

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#48]
Whether virocore can identify the current scene without light.

**Comment by dam00n** [comment]
Can you provide more details for this issue? You need to add lights to your scene to make objects visible. Here is our Lighting guide that explains this concept in detail -> https://virocore.viromedia.com/docs/3d-scene-lighting

**Comment by 544531645** [comment]
I think I know, I can give hellowword demo ARHitTestListenerCrossHair was added to distinguish whether the recognition success, this is ok?

**Comment by 544531645** [comment]
when happend SURFACE_NOT_FOUND

**Comment by 544531645** [comment]
Can you change the color and radius of the point cloud in the recognition process?

**Comment by dthian** [comment]
Hi @544531645, unfortunately without the context / more info, I don't have enough data to answer your question above. To better diagnose your issue please provide:
1. Your Java code that reproduces the issue.
2. What you were doing to reproduce the issue. 
3. Error logs / crashes / stack traces if any.

**Comment by 544531645** [comment]
What I'm going to do is when the recognition plane shows a state, when I'm looking for a state, when I can't find a state.
![image](https://user-images.githubusercontent.com/15622364/37500856-a0de6e94-2906-11e8-86c0-9eb54a761dd9.png)

**Comment by 544531645** [comment]
When looking for the icon is white, when the plane is found, the icon disappears, showing the plane.

**Comment by dam00n** [comment]
The ViroCore renderer will show a black screen until ARCore is initialized. In our experience, ARCore is usually very quick to initialize but it sounds like you are running into issues. It sounds like you want to show camera view from the start. We will make this change and add it to our next release, targeting end of this month.

**Comment by 544531645** [comment]
yes this a question, but I also want know     private enum TRACK_STATUS{
        FINDING_SURFACE,
        SURFACE_NOT_FOUND,
        SURFACE_FOUND,
        SELECTED_SURFACE;
    }  When there will be more than four kinds of condition, I only see the application of two kinds of state in the demo

**Comment by dthian** [comment]
Hi @544531645, ah... you meant the states within the demo. These are actually states specific to the demo via ARHitTestListener callbacks, where: 

FINDING_SURFACE - ARSession has initialized and user is looking around. 
SURFACE_FOUND - User has gazed upon an actual feature point, show crosshair. 
SELECTED_SURFACE - User has clicked on cross hair to enter the selected surface state. 

Not that these are mainly only for demo purposes - they are **not** the main ARScene listeners used for surface callbacks as seen [here](https://virocore.viromedia.com/docs/augmented-reality-ar#section-ar-scenes-and-anchors), where the actual detection of Anchors and planes are done by the renderer. 

Finally, it seems that SURFACE_NOT_FOUND enum isn't used in this demo. For the ARRetail demo, we simply look for the surface, find it, and select it - it's not needed and redundant. I'll remove this enum from the demo to avoid further confusion in the future.
