### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by jacobwyn** [viromedia/virocore#51]
I have a problem while rendering this car https://www.turbosquid.com/FullPreview/Index.cfm/ID/1117798
![screenshot_20180316-121106](https://user-images.githubusercontent.com/15327844/37520799-21c08086-2927-11e8-88ad-6ac025cfab73.png)
![screenshot_20180316-120406](https://user-images.githubusercontent.com/15327844/37520802-23743c2e-2927-11e8-9292-3fd954614c76.png)
There is no any errors or warnings in  the log. It happens average in 20% of cases .

**Comment by dthian** [comment]
Hey @jacobwyn, a few quick questions:

1) By 20%, do you mean 20% of the times you have loaded this car, or did you mean instead 20% of the total number of models that you have?

2) Are you loading loading the VRX model of this car (when converted from FBX), or the OBJ model of this car? Ideally the VRX version should have failed ideally, as the latest release of ViroCore has a bug in it where texture names with spaces errors out (unless you've modified the model to not have spaces). 

Thanks!

**Comment by jacobwyn** [comment]
Hi @dthian :
1. On each ~5th attempt  rendering is failed like on the pic. 2
2. I load VRX, converted from FBX. I am aware about bug with white spaces in assets names... I thought if error mentioned above happens I do not get onObject3DLoaded callback... thanks for advice, will check it.

**Comment by dthian** [comment]
Hey @jacobwyn, thanks for explaining. 

Looking at the screenshots above, this is a bug on the ViroCore renderer, where we have a render order issue when handling Transparency and rendering objects behind them (like the windows, headlight glass, etc). Effectively the renderer believes that there is nothing behind the glass during the depth check, and doesn't render the rest of the internal car (bug). I'll file a bug on our backlog and we'll update this issue as soon as it has been pushed to release.

As a mitigation, one can make the car windows opaque (seems like the creator / artist of the car pretty much ignored the interior anyways, so it's always dark). I've attached a copy of an opaque vrx car [here](https://drive.google.com/open?id=1YJkc5Eavc_DGuXi5I0yxNZmTMRTEZl9t).

Here's a gif of how it could look like:

![ezgif-4-af50d3be26](https://user-images.githubusercontent.com/1904934/37546970-6e18e356-292c-11e8-922f-d8772a7b6a3b.gif)

**Comment by jacobwyn** [comment]
Hi @dthian, thanks for so fast response and solution!

**Comment by jacobwyn** [comment]
Hi @dthian 
Just curious, how did you make the glass black so fast, did load the model from vrx and change it, or  change mtl file and load obj? Please share  If you use some useful tools, thanks in advance!

**Comment by saboteur111** [comment]
Hey @jacobwyn, I imported the model into Maya and changed the value of the transparency on the material using the slider. 
![screen shot 2018-03-19 at 10 07 58 am](https://user-images.githubusercontent.com/23560993/37610670-7763d42e-2b5d-11e8-8267-3a087b6229e6.png)
