### ISSUE TITLE
vrx not show 

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#53]
![image](https://user-images.githubusercontent.com/15622364/37578433-bd0cbab6-2b73-11e8-978a-1ef208d5f61d.png)

**Comment by 544531645** [comment]
the log is show , but tracking model not show ..

**Comment by jacobwyn** [comment]
Try to add an AmbientLight like so 
```
     AmbientLight ambientLight = new AmbientLight();
     ambientLight.setIntensity(500);
     arScene.getRootNode().addLight(ambientLight);
```
