### ISSUE TITLE
Marker/QRcode tracking

### ISSUE THREAD

**Issue by derzu** [viromedia/virocore#54]
Does Virocore support object/marker tracking? Like track a QR code? I wanna move an object at the real world and this movement also moves a virtual object.

Will this function be implemented?

Best regards,

Derzu.

**Comment by dam00n** [comment]
ViroCore does not support image recognition at this time. But we will have it by end of March. This will allow you to detect markers in the real world and place objects relative to them.

We will be working on object/image tracking next, but do not have a timeframe on when this will be available at this time. Will update this issue with more information when it is available.

**Comment by dam00n** [comment]
We added support for image/recognition to ARCore/Android in our latest release, ViroCore 1.6.0. Now you can build cross platform AR apps with image recognition. Release Notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases

Some demos and code samples for you to try it out yourself.

![viro_black_panther_marker_demo](https://user-images.githubusercontent.com/450239/39054745-69992092-4480-11e8-809f-8e50c22c21af.gif)

AR Poster Demo code sample -> https://github.com/viromedia/virocore/tree/master/ARBlackPanther

![ar car marker](https://user-images.githubusercontent.com/450239/39054707-57c4031e-4480-11e8-8735-70463fa01f61.gif)

AR Car Marker Demo code sample -> https://github.com/viromedia/virocore/tree/master/ARTesla

**Comment by derzu** [comment]
Great work. Thanks.

**Comment by SurendiranParasu** [comment]
Hi @dam00n :3D Object is not getting moved or tracked along with the marker when I move. 
I have been trying for a week. but could not found the solution so far. Help it here please,
