### ISSUE TITLE
object3D.getBoundingBox() always return a point

### ISSUE THREAD

**Issue by EricSKCheng** [viromedia/virocore#55]
Call object3D.getBoundingBox() inside the onObject3DLoaded callback always return a point rather a box.
The min value and max value are the same.

**Comment by radvani** [comment]
Hi @EricSKCheng, in order to reproduce this could you send us the file you're loading, either the OBJ or FBX file? You can attach it here or email us at support@viromedia.com. Thanks!

**Comment by radvani** [comment]
Hi @EricSKCheng, we've resolved this bug and it will be available in our forthcoming release. Thanks for the report.

**Comment by dam00n** [comment]
This issue has been fixed in the latest update, ViroCore 1.5. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases

Let us know if you are still having issues after upgrading.
