### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: millis < 0: -432345564227567616

### ISSUE THREAD

**Issue by EricSKCheng** [viromedia/virocore#56]
Getting this issue on Google pixel and note 8 sometimes.
The log:
Fatal Exception: java.lang.IllegalArgumentException: millis < 0: -432345564227567616
       at java.lang.Thread.sleep(Thread.java:346)
       at java.lang.Thread.sleep(Thread.java:314)
       at com.viro.core.internal.keys.KeyValidator$1.run(SourceFile:87)
       at java.lang.Thread.run(Thread.java:764)

**Comment by radvani** [comment]
Hi @EricSKCheng, thanks for this bug report. We've resolved the issue and it will be available in the next release.

**Comment by dam00n** [comment]
This issue has been fixed in the latest update, ViroCore 1.5. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases

Let us know if you are still having issues after upgrading.
