### ISSUE TITLE
Gesture camera when view Sence 3D object 

### ISSUE THREAD

**Issue by hvmien** [viromedia/virocore#59]
Hello everyobdy! Im newbie approach virocore. Im using virocore render file obj for android ui view 3D. i want to gesture on object. Example: one finger to rotate object, two finger drag object. Who can help me? Thanks for all.

**Comment by dam00n** [comment]
You can use any of the sample projects we offer on this github page to do this. ARRetail might be the one you start with. Drag is with 1 finger and rotate with 2 fingers. Here are the samples -> https://github.com/viromedia/virocore
