### ISSUE TITLE
Is it possible to use only sceneKit (or somehow desrease lib size)?

### ISSUE THREAD

**Issue by Svoka** [viromedia/virocore#6]
I don't need the part with AR, I only need a scene API. 
I ask this because compiled library size is 22MB if I understand everything right and this is just way too much.

For example, jpct-ae size _only 3mb_.

**Comment by dam00n** [comment]
We are working in decreasing the lib size now for our next update (targeting early next week). Will update this thread once the new version is live, along with new lib size.

**Comment by achuvm** [comment]
Hi @Svoka,

With our ViroCore 1.1 update, we have reduced the size of the ViroCore library to 4.2 MB!

Check out the release and upgrade instructions here: https://virocore.viromedia.com/docs/releases

Sorry for any inconvenience! Feel free to reach out to us if you have any other issues!

Andy

**Comment by Svoka** [comment]
@achuvm wow! Definitely wanna check it right now :)
