### ISSUE TITLE
Not play video inside portal scene.

### ISSUE THREAD

**Issue by sw-tt-darshanmistry** [viromedia/virocore#60]
Hello,

I have tried below code to play 360 video inside portal scene but anyhow is not working and application gonna to be crashed every time. Below is my code for your reference.

```

    Uri parse = Uri.parse("file:///android_asset/test.mp4");
    VideoTexture videoTexture = new VideoTexture(mViroView.getViroContext(), parse);
    Material material = new Material();
    material.setDiffuseTexture(videoTexture);
    Surface surface = new Surface(10, 10);
    surface.setMaterials(Arrays.asList(material));
    videoTexture.play();

    portalScene.setBackgroundTexture(videoTexture);
```

**Comment by radvani** [comment]
Hi @sw-tt-darshanmistry,

What error are you seeing in the logs? I tried this code locally and it appears to work. Also, you don't need to create a Surface to house the material since you're setting it directly as a Texture on the portal scene. You can do just do this:

```
Uri parse = Uri.parse("file:///android_asset/test.mp4");
VideoTexture videoTexture = new VideoTexture(mViroView.getViroContext(), parse);
videoTexture.play();
portalScene.setBackgroundTexture(videoTexture);
```

**Comment by sw-tt-darshanmistry** [comment]
Hello,
 
Your code works nice. Thanks for the guide.
