### ISSUE TITLE
Black screen on Samsung Galaxy S8 using Oreo

### ISSUE THREAD

**Issue by johngamarra** [viromedia/virocore#62]
I've downloaded latest version of Android Studio, opened the viro core hello world ar sample, put my API KEY, and run it in my Galaxy S8, already installed AR Core 1.0, but I only get a Black Screen when running the sample, what it could be?

**Comment by johngamarra** [comment]
Logcat says AR Core is not installed, I'm sure it is because I can run official AR Core sample without problems:

`03-28 18:55:01.034 12157-12157/com.example.virosample.arcore W/native: session_create.cc:40 LoadDynamite returning AR_UNAVAILABLE_ARCORE_NOT_INSTALLED.
03-28 18:55:01.035 12157-12157/com.example.virosample.arcore I/Viro: Error: ARCore not installed on device`

**Comment by dam00n** [comment]
Can you try the following? Restart your S8 and see if that resolves the issue. If not, try uninstalling ARCore and then redownload from the Play Store. We are not seeing this issue on our S8 device. If neither helps, let us know and we can dive into it more.

**Comment by VikAdvani** [comment]
Hi @johngamarra Google had an issue with ARCore and Oreo devices that they've fixed recently which is why we think reinstalling ARCore may help: https://github.com/google-ar/arcore-android-sdk/issues/198

**Comment by johngamarra** [comment]
disabled instant run as recommended here:
[https://github.com/google-ar/arcore-android-sdk/issues/130](url)
fix the issue

**Comment by hhong0326** [comment]
you have to check build.gradle version
