### ISSUE TITLE
Inflate sub-node parts in 3DModel

### ISSUE THREAD

**Issue by dthian** [viromedia/virocore#63]
I was wondering if the virocore library is unable to detect node tree structures (objects with child objects) and reconstruct them as such when loading the .vrx nested model into an Object3D.

For example, I have:
Scene
* Car
** Door1 
** Door2 
** Door3 
** Door4 
as my structure, and yet when I load the model the resulting Object3D in onObject3DLoaded() seems to return no children when using .getChildNodes(). Did I miss something?

Ultimately, I want to be able to add ClickListener to a number of these sub-node parts. 

I tried creating an ARScene by loading the sub-nodes individually and rendering 3 separate Object3Ds to attach ClickListeners to, and yet it seems only the parent (e.g. Cylinder) is able to get onClick() and onClickState() events.

**Comment by keithmaxx** [comment]
In addition, if the bounding box happens to cover the sub-nodes, then the events are captured by the larger (e.g. car) node and not by its children.

**Comment by dthian** [comment]
Thanks @keithmaxx, situations above where we have concave/complex shapes, or where parent nodes encompasses sub-nodes can get rather complicated. I guess the general idea is this:

If a bounding box (say of the wheel) is covered / encompassed by another bounding box (of the car's body), it would confusing to say: "Trigger events on the encompassing box (wheel), even though it is fully encompassed in by another box (car)". Targeted events should **only** target the firstly hit box (car). There isn't really a valid case where you would want to target both boxes with the same click event anyways. 

Else, if you wish to target encompassed boxes (wheel) that may be covered, it is best to ignore set ignoreEvents for the outer most box (car), such that you can simply click on the wheels. This also helps clarify the order of events and node structure of what should get triggered. 

After this github issue is fixed, you should be able to set events on 3D model's sub nodes. Thus, if you wish to click on the wheels, you can set click listeners on them, and ignoreEvents on the encompassing cars body. 

If you then wish to also have the car's body intersect events at the same time, while having the listeners still set on the wheels, I would suggest (in addition to the above), simply adding an invisible bounding box that represents the car **without encompassing the wheels**. This way, it is very clear who gets the events, and what they should do (Rotate or clicked) as a result of them.

**Comment by dthian** [comment]
Hey all, this issue should have been fixed in Viro Core 1.8, where one can now access the nodes and its properties associated with FBX / GLTF models. As such resolving as fixed. Please refer to our [releases](https://virocore.viromedia.com/docs/releases) documentation for update instructions.
