### ISSUE TITLE
texture not fill out real texture with load file obj.

### ISSUE THREAD

**Issue by hvmien** [viromedia/virocore#64]
Hello everyone, im newbie approach virocore. im facing problem with 3d object. 
im download 3D object at: [https://free3d.com/3d-model/house-19128.html](url)
and now im load using preview in mac. it look like:
flow the link:[ http://imageshack.com/a/img922/7406/LHPojr.png](url)
and after i load model using virocore, it look like
[http://imageshack.com/a/img922/8797/mvrhsh.jpg](url)
who can help me?
Thansk all.

**Comment by saboteur111** [comment]
Hi @hvmien , I took a look at the house model in Maya. The UV's seem to be outside of 1 which may be causing issues. 
![screen shot 2018-04-02 at 1 15 42 pm](https://user-images.githubusercontent.com/23560993/38214004-18277e18-3678-11e8-9ce8-a6f9b65d2855.png)

I re-exported it as FBX using Game Exporter in Maya which may help the issue without having to move around the UV's. You can find instructions how to export properly here: https://blog.viromedia.com/https-blog-viromedia-com-asset-pipeline-optimizing-3d-models-ar-vr-arkit-arcore-d0fb61627aaf
Look under "Export 3D Model."

Here's the exported FBX file.
[house_a.fbx.zip](https://github.com/viromedia/virocore/files/1869201/house_a.fbx.zip)

**Comment by hvmien** [comment]
@saboteur111  Thanks your for reply!
This house is a sample, almost all model dont fill out texture with file obj and mtl. Presently, i have solution fix with virocore load 3d .obj.
anyway, thanks alot.
