### ISSUE TITLE
android studio Emulator dont work

### ISSUE THREAD

**Issue by amirhrezf** [viromedia/virocore#66]
hi
according to google arcore document now we can run ar apps on emulator. So why i get this error when everything is ok for each viro sample projects.
![screenshot 3](https://user-images.githubusercontent.com/15376463/38198921-1a3695c4-36a8-11e8-9af8-e65bbc5994ee.png)

**Comment by radvani** [comment]
Hi @amirhrezf, Viro currently does not support the Android emulator: we provide symbols for armeabi-v7a and arm64-v8a, but the emulator needs x86 symbols. We'll look into adding support for this.

**Comment by dam00n** [comment]
Closing this issue as we have another issue to track this request for Android Emulator Support -> https://github.com/viromedia/virocore/issues/57
