### ISSUE TITLE
Orbit camera not working (1.5.0)

### ISSUE THREAD

**Issue by rgipd** [viromedia/virocore#68]
Hi,

  I tried to copy the example from the Camera docs in website, but after a make a 45 degrees rotation, the orbit camera does not work as supposed. Code is below:
  
```
Node cameraNode = new Node();

Camera camera = new Camera();
camera.setRotationType(Camera.RotationType.ORBIT);
camera.setOrbitFocalPoint(new Vector(0, 0, 0));
cameraNode.setPosition(new Vector(0, 0, 20));
//cameraNode.setRotation(new Vector(0, Math.toRadians(45), 0)); // with this, does not work
cameraNode.setCamera(camera);

Node boxNode = new Node();
boxNode.setPosition(new Vector(0, 0, 0));
Box box = new Box(1, 1, 1);
boxNode.setGeometry(box);

scene.getRootNode().addChildNode(cameraNode);
scene.getRootNode().addChildNode(boxNode);
view.setPointOfView(cameraNode);

```

  So, I tried to develop a Orbit Camera like in iOS SceneKit, the steps are:
  In SceneKit I create a Camera and put inside a CameraNode's camera property (and set as the Point of View for the Scene).
  Then I add the CameraNode as child of OrbitCameraNode.
  The CameraNode has the position of ( 0, 0, 10 ) and the OrbitCameraNode ( 0, 0, 0 ).
  I add a Box ( 1, 1, 1 ) in the origin ( 0, 0, 0 ), so the Camera is always focus on it.
  
  When I rotate the OrbitCameraNode (eulerAngles: 0, 45, 0), the CameraNode (and so the Camera) is affected by this rotation.

  I tried to do the same thing in ViroCore / ViroScene, but the camera seen not to be affected by it's parent node's transforms.

  I already look at the issue #30 , but I want to know if has a way to use the already built-in orbit rotation type in Camera to achieve this simple transformation.

  P.S.: The rotation I want to do is the orbit in Yellow, but with the Camera looking to ( 0, 0, 0 ), like the Orbit.
![b891975-viro_camera_diagram](https://user-images.githubusercontent.com/11277467/38304221-042007a6-37df-11e8-8241-e70ea0c5d974.png)

Thanks in advance.

**Comment by dthian** [comment]
Hi @rgipd, thanks for reaching out. Unfortunately, the built in Viro Orbit Camera currently only works in [VR](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewGVR.html), not for [ViroViewScene](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewScene.html). As mentioned in issue #30, we are aware of this and have a story to build this feature. This issue will be updated as soon as it has been pushed into release.

A mitigation has also been proposed at #30, where you can see in the gif, we are rotating the camera around a fixed focal point in the house.

**Comment by rgipd** [comment]
@dthian Thank you for the reply. I was afraid that I would need to implement this by myself for now.

I think have the point of view (with Camera) using the transforms like the SceneKit in iOS would solve quickly :)

I'm closing the issue and stay tuned for the next version.
