### ISSUE TITLE
Is there any way to add customized GLSurfaceView to the ViroViewScene?

### ISSUE THREAD

**Issue by EricSKCheng** [viromedia/virocore#70]
Want to see if there is any way to render customized GLSurfaceView to the scene? 
Thanks.

**Comment by dthian** [comment]
Hey @EricSKCheng, by the above, do you mean adding another view to be rendered onto of the ViroViewScene? If so, that should be possible, as it is the same as inflating yet another view in the Android xml layout (in this case, your gl surface view).
