### ISSUE TITLE
Crash when re-entering AR repeatedly

### ISSUE THREAD

**Issue by dthian** [viromedia/virocore#73]
Mentioned by: @jacobwyn

After launching 5-10 times app (launch, put some 3d models, press back, repeat few times) I am getting next error

>04-06 10:42:57.072 16549-17330 E/Adreno-GSL: <gsl_memory_alloc_pure:2202>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
>04-06 10:42:57.328 16549-17330 W/Adreno-GSL: <sharedmem_gpuobj_alloc:2318>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory

And app is stuck, can reproduce it even in ARRetail
I have a suspicion that it is somehow connected with bug 4 from here #69
My app https://github.com/jacobwyn/augmentedReality

**Comment by VikAdvani** [comment]
Hi @jacobwyn I was unable to repro this with the ARRetail app on a Pixel 2 phone. I tried entering and exiting the Viro AR Activity about 20 times and the app didn't crash. Are you able to consistently repro this? What device are you using? Thanks!

**Comment by dam00n** [comment]
We recently updated to ViroCore 1.6.0. Release Notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases

Were unable to repro, closing issue. Please reopen if you are still having issues and provide additional information and/or repro steps.
