### ISSUE TITLE
ViroFBX losing material name in conversion.

### ISSUE THREAD

**Issue by rgipd** [viromedia/virocore#77]
Hello,
  
  I used FBX binary and text mode, 2015 and 2018 versions, all exported from Modo.
  In FBX file I have 2 materials, named:
     mymodel_inside
     mymodel_outside

 I convert FBX to VRX with the latest script for OS X.
 Then I load the model in Android and I check for materials name that is now:
     converted_filename5
     converted_filename6

Can someone please maintain the material's name in conversion?

Thanks!

**Comment by manbod** [comment]
Hi rgipd,
Thanks for reaching out. We are seeing this issue for the first time with the FBX script. Would you mind providing more details so we can dive deeper into this?
1. Is the converted VRX unable to load your materials, when you try to render it on virocore? 
2. What error do you see?
3. How are you loading the model to check for `converted_filename5` and `converted_filename6`?
4. Would you mind sharing your FBX model so we can reproduce the same issue on our end?

Thanks!

**Comment by rgipd** [comment]
Hello, @manbod 

  The answers:

  1. The VRX is loaded and materials too.
  2. No errors.
  3. I'm loading the model, getting it materials and checking the name (just like in SceneKit). But, instead "mymodel_inside", it prints converted_filename5.
  4. I could reproduce this issue in all FBXs exported by Maya and Modo (binary or text, 2015 or 2018 versions)

  Again, my problem is the name of material that is not being loaded. Or by converter, or by the Android 1.5.0 version.


Thanks

**Comment by dthian** [comment]
Thanks @rgipd, is it possible to provide us the fbx model that you are using to test with?

**Comment by dthian** [comment]
Hey @rgipd, it seems like it may have been an issue with the FBX Script. I've patched it and verified with a 3D model made from maya with a custom material name - that we are able to read the custom name from the ViroPlatform after a FBX->VRX conversion.

Could you try using this script below and please get back to us if it has worked for you:
https://drive.google.com/open?id=1RClRwuLQBVE0ba9IqFdX0c2nv14FPztc

**Comment by rgipd** [comment]
Hi, @dthian ! It worked without any problems.

  All materials names is unchanged from FBX now :)
  Who closes the issue, you or me?


Thanks.

**Comment by dthian** [comment]
That's good news, I'll close the issue after updating the main FBX script links on our documentation site.

Have a great rest of your day! :)

**Comment by rgipd** [comment]
Maybe you can create a github page with only releases with this script (and a changelog), so users like me can track changes (instead the site). :)

And issues for the tool.

**Comment by dthian** [comment]
Thanks @rgipd, that's a great idea, I'll bring it up with the team to discuss.
