### ISSUE TITLE
Playing Alpha video

### ISSUE THREAD

**Issue by BALUSANGEM** [viromedia/virocore#87]
We wants to play alpha video using ViroCore(remove green background while playing video). Can I use this library to do that?

**Comment by radvani** [comment]
Hi @BALUSANGEM, we don't currently support alpha videos, but this feature has been added to our backlog and we will investigate how to incorporate these. I will keep this issue updated to track the feature.

**Comment by radvani** [comment]
@BALUSANGEM, after a preliminary investigation I can confirm that we will support alpha videos in our next release. The videos will use a chroma key filter (e.g. blue screen or green screen).

**Comment by dthian** [comment]
This has been fixed in the latest release of ViroCore 1.7.2. Please checkout the update instructions here: https://virocore.viromedia.com/docs/releases. Please see https://virocore.viromedia.com/docs/video#alpha-video-chroma-key-filtering
