### ISSUE TITLE
How to config activity camera landscape?

### ISSUE THREAD

**Issue by tuzenvn** [viromedia/virocore#89]
I config the camera activity orientation on Manifest.xml is landscape and camera display error

Configutation line: android:screenOrientation="landscape"

And issue occurred like below screenshot:
![viro-issue_landscape](https://user-images.githubusercontent.com/9345193/39119141-5642d1ae-4715-11e8-99d2-d43fe0b9d68d.png)

**Comment by VikAdvani** [comment]
Hi @tuzenvn, 
Currently if you remove the screenOrientation parameter in the manifest and simply rotate the phone then landscape mode should work.

There is a bug currently where the screenOrientation specified as landscape in the manifest file doesn't work as intended and gives the result you are seeing.

For now if you need to lock the orientation to landscape you can try overloading the following function in your Activity:
```
@Override
   public void onConfigurationChanged(Configuration newConfig) {
       super.onConfigurationChanged(newConfig);
       this.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
   }
```

Let me know if that works! Once the bug with the screenOrientation in the manifest is fixed I'll update this github issue.

**Comment by tuzenvn** [comment]
Thanks a lot @VikAdvani, 

My app required to lock the orientation to landscape, I add _android:screenOrientation="landscape"_ in Manifest and in Activity I isue: 
_mViroViewARCore.setCameraRotation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);_
