### ISSUE TITLE
show model question 

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#91]

**Comment by 544531645** [comment]
I want the 3dmodel to show what should I do in front of my screen, sometimes the Angle is wrong?

**Comment by dam00n** [comment]
We would need more information to help you with this issue. Can you send a screenshot of the issue?

Please read our 3D Object developer guide for assistance -> https://virocore.viromedia.com/docs/3d-objects

Also consider using our sample code as a starting point for your project which might mitigate some of your issues -> https://github.com/viromedia/virocore

**Comment by achuvm** [comment]
Hi @544531645,

See the functions `getLastCameraPositionRealtime()` and `getLastCameraForwardRealtime()`:

https://developer.viromedia.com/virocore/reference/com/viro/core/ViroView.html#getLastCameraForwardRealtime()

https://developer.viromedia.com/virocore/reference/com/viro/core/ViroView.html#getLastCameraPositionRealtime()

If you were to simply place the object at the position + forward, then the object would be in front of the camera at that point in time. However, if you were to move the camera, the object would be positioned where you originally left it. If you'd like for the object to move with the camera, the current way would be to register a `CameraListener` on the `ViroView`:

https://developer.viromedia.com/virocore/reference/com/viro/core/CameraListener.html

And update the position of your model on each callback.

We are looking into adding the ability to position objects relative to the camera to help make adding hud-like components easier in the future.

Thanks,

**Comment by 544531645** [comment]
getLastCameraPositionRealtime() I think this put camera center ,now I can see front , I need back a litter can see model

**Comment by achuvm** [comment]
Right, you need to put the model in front of the camera, so add a multiple of the forward vector to the position vector.

Ie. 

`position.add(forward.scale(3))`
