### ISSUE TITLE
Shadows in screenshots are colored lighter

### ISSUE THREAD

**Issue by achuvm** [viromedia/virocore#92]
Seen on ViroCore 1.5 and 1.6.

See the image below, the shadow should be darker:

<img width="216" alt="screen shot 2018-04-25 at 3 16 15 pm" src="https://user-images.githubusercontent.com/21074927/39268306-4ec25970-4884-11e8-9511-bed9ff5de93e.png">

**Comment by dthian** [comment]
This has been fixed in the latest release of ViroCore 1.7.2. Please checkout the update instructions here: https://virocore.viromedia.com/docs/releases
