### ISSUE TITLE
push _question

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#93]
I show a notification ,but  click  when main page is show happend crash

**Comment by 544531645** [comment]
NotificationCompat.Builder notification = new NotificationCompat.Builder(context,"kydy");
        Intent intent = new Intent(context, ViroActivity.class);
        intent.putExtra("deeplink","noti");
        notification.setSmallIcon(R.mipmap.ic_launcher);
        notification.setContentTitle(title);
        notification.setContentText(message);
        intent.setFlags(Intent. FLAG_ACTIVITY_CLEAR_TOP);


        intent.setAction(String.valueOf(System.currentTimeMillis()));
        notification.setDefaults(Notification.DEFAULT_ALL);
        PendingIntent contentIntent = PendingIntent.getActivity(context, 0,
                    intent, PendingIntent.FLAG_UPDATE_CURRENT);
            notification.setContentIntent(contentIntent);
            Notification build = notification.build();
            Log.i(TAG,"asdasdasd");
            id_tag++;
            nm.notify("kydy",id_tag, build);

**Comment by 544531645** [comment]
I think the eroor log is :04-23 14:21:10.125 488-514/? E/SurfaceFlinger: Failed to find layer (SurfaceView - com.vrexlab.kydy/com.example.kydy.ViroActivity#0) in layer parent (no-parent).
04-23 14:21:10.126 488-514/? E/SurfaceFlinger: Failed to find layer (Background for - SurfaceView - com.vrexlab.kydy/com.example.kydy.ViroActivity#0) in layer parent (no-parent).

**Comment by 544531645** [comment]
when I open other page , click notification go to virocore page , it is work . when backgroud ,it work ,only when main page is virocore page crash

**Comment by achuvm** [comment]
Hi @544531645,

I took a look at the support email w/ the trace:

```
04-23 14:21:08.170 9049-9049/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-23 14:21:08.170 9049-9049/? A/DEBUG: Build fingerprint: 'google/marlin/marlin:8.0.0/OPR3.170623.013/4397526:user/release-keys'
04-23 14:21:08.170 9049-9049/? A/DEBUG: Revision: '0'
04-23 14:21:08.170 9049-9049/? A/DEBUG: ABI: 'arm'
04-23 14:21:08.170 9049-9049/? A/DEBUG: pid: 8680, tid: 8680, name: om.vrexlab.kydy  >>> com.vrexlab.kydy <<<
04-23 14:21:08.170 9049-9049/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x238
04-23 14:21:08.170 9049-9049/? A/DEBUG: Cause: null pointer dereference
04-23 14:21:08.170 9049-9049/? A/DEBUG:     r0 ca1cc831  r1 00000000  r2 00000000  r3 00000000
04-23 14:21:08.170 9049-9049/? A/DEBUG:     r4 0000023a  r5 ffd9c590  r6 00000000  r7 ffd9c568
04-23 14:21:08.170 9049-9049/? A/DEBUG:     r8 ca34483d  r9 ca479b07  sl eaa64390  fp ca1cc831
04-23 14:21:08.170 9049-9049/? A/DEBUG:     ip ca4a2c78  sp ffd9c528  lr ca29f165  pc 00000238  cpsr 600f0010
04-23 14:21:08.190 9049-9049/? A/DEBUG: backtrace:
04-23 14:21:08.190 9049-9049/? A/DEBUG:     #00 pc 00000238  <unknown>
04-23 14:21:08.191 9049-9049/? A/DEBUG:     #01 pc 00107163  /data/app/com.vrexlab.kydy-e1k1M_KSZ-yRcKLWGC4Fdw==/lib/arm/libviro_renderer.so (_Z13log_backtracePjj+162)
04-23 14:21:08.191 9049-9049/? A/DEBUG:     #02 pc 0010704b  /data/app/com.vrexlab.kydy-e1k1M_KSZ-yRcKLWGC4Fdw==/lib/arm/libviro_renderer.so (_ZN15DebugStacktrace13logStacktraceEj+46)
04-23 14:21:08.191 9049-9049/? A/DEBUG:     #03 pc 00176a85  /data/app/com.vrexlab.kydy-e1k1M_KSZ-yRcKLWGC4Fdw==/lib/arm/libviro_renderer.so
04-23 14:21:08.191 9049-9049/? A/DEBUG:     #04 pc 00176af3  /data/app/com.vrexlab.kydy-e1k1M_KSZ-yRcKLWGC4Fdw==/lib/arm/libviro_renderer.so (_Z7_pabortPKciS0_S0_z+50)
04-23 14:21:08.191 9049-9049/? A/DEBUG:     #05 pc 001ac887  /data/app/com.vrexlab.kydy-e1k1M_KSZ-yRcKLWGC4Fdw==/lib/arm/libviro_renderer.so (_ZN19VROThreadRestricted14passert_threadEv+74)
04-23 14:21:08.191 9049-9049/? A/DEBUG:     #06 pc 001fe497  /data/app/com.vrexlab.kydy-e1k1M_KSZ-yRcKLWGC4Fdw==/lib/arm/libviro_renderer.so (_ZN22VROSceneRendererARCoreC2E24VRORendererConfigurationSt10shared_ptrIN3gvr8AudioApiEE+378)
```

This crash should be fixed in ViroCore 1.6.0: https://virocore.viromedia.com/docs/releases

Have you tried upgrading to the latest ViroCore version?

**Comment by 544531645** [comment]
when I update , 
![image](https://user-images.githubusercontent.com/15622364/39343995-84b3c214-4a12-11e8-8e0c-d0fe44f24b4d.png)
the Arcore apk  class can't find

**Comment by 544531645** [comment]
UnavailableArcoreNotInstalledException both can't find
