### ISSUE TITLE
Error: The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.

### ISSUE THREAD

**Issue by Jhonnybsg** [viromedia/virocore#96]
This error occurs in any sample project I try to run. I've properly done everything in the first page of this git repository. Any idea of how to solve this? 

Failed to load native library [packageName=com.google.ar.core,libraryName=arcore_c] from remote:
java.lang.IllegalStateException: java.lang.IllegalArgumentException: The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.

**Comment by Jhonnybsg** [comment]
SOLVED
I Deactivated Instant Run and it started working. Don't know what is the relation with that, but now it's ok.

**Comment by dthian** [comment]
Thanks @Jhonnybsg, apologies for the mishap. There seems to be [issues](https://github.com/google-ar/arcore-android-sdk/issues/130) with Android Studio and Google's latest version of ViroCore that causes the crashes above. 

I've updated both our ViroReact and ViroCore API docs to call this out. Much thanks!
