### ISSUE TITLE
Pixel 1 gen with latest Android 8.1 build and Arcore 1.1 always return "ARCORE_NOT_INSTALLED"

### ISSUE THREAD

**Issue by dementia2029** [viromedia/virocore#99]
Pixel 1 gen with Android 8.1 (build OPM2.171019.029) does not work with any sample with any version of ViroCore. Always returning ARCORE_NOT_INSTALLED

**Comment by derzu** [comment]
Do you have ARCore 1.1 installed?

You can Install from Google Play Store if your device is compatible. 

Try to install from here:
https://play.google.com/store/apps/details?id=com.google.ar.core

**Comment by dementia2029** [comment]
Thank you for replies. Disable instant run fixed the issue.
